### ISSUE TITLE
Discuss: Ionic Router

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic2#179]
Ideas:

1) They use RouteConfig and specify routes with URLs, which we use to determine what components can be navigated to so we can do `nav-push="FirstPage"`.

2) They import all possible Components/IonicViews/ViewControllers and add them to `@App`, which we use to build a map so that `nav-push="FirstPage"` is possible.  They still need to use `@RouteConfig` for URLs though.

```
import {FirstPage, SecondPage, ThirdPage} from './pages';
@App({
  templateURL: 'app/app.html',
  views: [FirstPage, SecondPage, ThirdPage]
})
```

3) At build time, we scan source files for unique tokens that indicate a view controller (@IonicPage or something) and build the map from step 2 automatically.  URLs still come from `@RouteConfig`.

4) We do nothing, `nav-push="FirstPage"` fails, yells at them to do `[nav-push]="page"` and set `this.page = FirstPage`.

**Comment by angeloo** [comment]
Hi,

Sorry for the question, but I begin with ionic 2 and angular 2 too...

Is that possible to add a path for each route with your example implementation?

something like: http://localhost:8101/#/message

**Comment by tlancina** [comment]
Hey @angeloo this will be supported, but I believe is not working with the latest Angular 2 router at the moment.

**Comment by angeloo** [comment]
Ok, thanks!

I'll investigate this point a little further next weeks.

**Comment by tlancina** [comment]
Closing this for now, will revisit when router has settled.
