### ISSUE TITLE
Add the ability to include the Android box-shadow via data uri

### ISSUE THREAD

**Issue by bensperry** [driftyco/ionic2#184]
Sometimes Android uses a box-shadow beneath the navbar. For performance sake, let's try offering this ability with ionic as well, by means of a png (data uri).

I attached it here. Give it a try and let's test this s**t.

![header-box-shadow](https://cloud.githubusercontent.com/assets/519526/10138998/8b1e073c-65c6-11e5-8a01-b69779dd97e5.png)

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5084
