### ISSUE TITLE
Docs: TypeScript syntax highlighting template strings

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic2#202]
The typescript highlighting doesn't do a great job with multi-line template strings:
![image](https://cloud.githubusercontent.com/assets/804331/10149048/bab70882-65fc-11e5-9e3e-b34401c1fff2.png)

Might be nice to look into at some point :)

**Comment by mhartington** [comment]
https://github.com/driftyco/ionic-site/commit/39abbf5f5bdd63be7827636ee06e0e6ff8802805
