### ISSUE TITLE
Docs: syntax highlighting

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic2#231]
![image](https://cloud.githubusercontent.com/assets/804331/10226912/ff622f40-682f-11e5-8c5a-95f2c518a5b1.png)

Maybe we can take a look at https://github.com/driftyco/ionic2/issues/202 while we're at it :)

**Comment by mhartington** [comment]
https://github.com/driftyco/ionic-site/commit/39abbf5f5bdd63be7827636ee06e0e6ff8802805
