### ISSUE TITLE
Text positioned wrong in List Headers [Android] demo

### ISSUE THREAD

**Issue by bensperry** [driftyco/ionic2#273]
![image](https://cloud.githubusercontent.com/assets/519526/10444125/6251c362-7128-11e5-89c9-a524aff575fe.png)

**Comment by brandyscarney** [comment]
@bensperry Does this text position only occur when there is an icon to the left or should it be this padded left no matter what?

**Comment by brandyscarney** [comment]
This is fixed by #437 so I'm closing this issue.
