### ISSUE TITLE
card css: item-center

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic2#279]
We have `item-right` and `item-left`, but no `item-center`. Might be useful to have for cards, eg:

```html
    <ion-item actions>
      <button clear item-left danger>
        <icon star></icon>
        Favorite
      </button>
      <button clear danger>
        <icon musical-notes></icon>
        Listen
      </button>
      <button clear item-right danger>
        <icon share-alt></icon>
        Share
      </button>
    </ion-item>
```

Whether or not `item` is added to the following button, it will not inherit its siblings' font size (`item-right` and `item-left`).
```html
      <button clear danger>
        <icon musical-notes></icon>
        Listen
      </button>
```
<img width="317" alt="nin" src="https://cloud.githubusercontent.com/assets/2018508/10463718/b27db9bc-71ab-11e5-8439-ff20dcd22b14.png">

Do we want to add an `item-center` attribute? Or could an `item` that is between and `item-left` and `item-right` get the same font styles?

**Comment by brandyscarney** [comment]
I think the styling should be applied to the buttons inside of actions, like this:

```
  [actions] {
    button,
    [button] {
      margin: $item-ios-padding-icon-top ($item-ios-padding-right / 2) $item-ios-padding-icon-bottom ($item-ios-padding-left / 2);
      padding: 2px 6px;
      min-height: 26px;
      font-size: 1.3rem;
    }
  }
```

this results in something like this and no extra markup for the user on the middle button:

![screen shot 2015-10-28 at 10 33 41 am](https://cloud.githubusercontent.com/assets/6577830/10791586/626467e0-7d5f-11e5-9c0b-c1e22c6023aa.png)

However this center button inside of the actions is still being placed inside of the `ion-item-content` which gives it extra padding that the other buttons (w/ `item-left` and `item-right`) don't have. Then, maybe we could space it out so they are evenly distributed across the bottom, at least for iOS? Any thoughts, @adamdbradley?

**Comment by adamdbradley** [comment]
Instead of creating a center item, we should make some API to make it easy to do columns. So instead of only allow 3 items, they could have 4 or 27, who knows. So we could use flexbox to divide up the columns evenly.

**Comment by brandyscarney** [comment]
Yeah that's what I was thinking, but in order to do that all buttons without an `item-left` or `item-right` attribute shouldn't be placed inside of `ion-item-content`.

**Comment by adamdbradley** [comment]
I'm thinking it wouldn't use ion-item-content at all. Could we try doing something like:

```
<ion-item>
    <button item-column>1</button>
    <button item-column>2</button>
    <button item-column>3</button>
    <button item-column>4</button>
</ion-item>
```

So ion-item could have another ng-content with `select="[item-column]"`. In general I don't think we should cover the use-case where there are multiple columns that are centered, and having a content area.

**Comment by brandyscarney** [comment]
That might work, and then style the `item-column` in an `<ion-item actions>` just like the `item-left` and `item-right`?

**Comment by adamdbradley** [comment]
Yeah let's give it a shot. Probably could get a new e2e test to cover all the scenarios.

**Comment by brandyscarney** [comment]
Added this as a subtask of #387. Closing this issue as it will be fixed by adding a column attribute.

**Comment by brandyscarney** [comment]
So this is more complicated than we originally assumed. Buttons in cards by default are larger (in terms of font-size, padding, margin, and height) than buttons with the `item-left` or `item-right` attribute. I don't think the right solution is overriding all buttons in cards, since some people may want a full size button in a card. For this reason, using multiple `ion-item-content`'s without any uses of `item-left/item-right` doesn't look good:

![screen shot 2015-12-30 at 2 12 42 pm](https://cloud.githubusercontent.com/assets/6577830/12056269/a533df4a-af02-11e5-8915-810ff608a79e.png)

And using `ion-row/ion-col` turns out even worse out of the box. So we could add a component like `ion-actions` that overrides the size of _everything_ (remember notes, icons) inside, or add back the `actions` attribute, or add an `item-center` which won't be placed inside of an `ion-item-content`...

Not to mention Material Design sometimes has these left and sometimes puts these on the right: 
https://www.google.com/design/spec/components/cards.html#cards-actions

I can't really think of a simple way of doing this.

**Comment by adamdbradley** [comment]
```    <ion-item>
      <ion-item-content>
        <button clear danger>
          <icon star></icon>
          Favorite
        </button>
      </ion-item-content>
      <ion-item-content>
        <button clear danger>
          <icon musical-notes></icon>
          Listen
        </button>
      </ion-item-content>
      <ion-item-content>
        <button clear secondary>
          <icon share></icon>
          Share
        </button>
      </ion-item-content>
    </ion-item>```

And a button within ion-item-content should have largely the same css as `[item-left]`. Maybe there's something there we can do so they do reuse the same css.

**Comment by brandyscarney** [comment]
What about the note? Those are also changed by `item-left/item-right`. Maybe we should be adding a class to these components to change them that way...right now we are changing `item-left` and `item-right` based on the component it's on...and there are a lot of them:

  
![screen shot 2016-01-04 at 12 58 01 pm](https://cloud.githubusercontent.com/assets/6577830/12096353/d21fa424-b2e2-11e5-9cb7-cf7a615101ac.png)

**Comment by brandyscarney** [comment]
Depends on https://github.com/driftyco/ionic2/issues/856

**Comment by brandyscarney** [comment]
So we've decided that we're going to reuse the grid component with the help of some alignment attributes to make this work. This reuses existing components without needing to make new ones and gives the user the most flexibility. We can always tweak this later & add more styling or an attribute.

Some examples on this test:
https://github.com/driftyco/ionic2/blob/master/ionic/components/card/test/advanced/main.html

Here are some of the ways they can be styled:

![screen shot 2016-01-05 at 5 15 02 pm](https://cloud.githubusercontent.com/assets/6577830/12129176/e5f6fd6a-b3cf-11e5-8283-4e5de19d5f4c.png)
