### ISSUE TITLE
es6-shim

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#292]
Now that traceur isn't being used, we need an es6-shim for safari:
https://github.com/angular/angular/issues/4751

Do we provide it in our npm module? Do we just add it to the starter's packagejson and webpack config? Can babel provide the shim itself? Do we need all of the shim, or just a few small pieces?

**Comment by jbavari** [comment]
@tlancina When you get a chance tomorrow, take a look at this. This would be a good time to address this as well as the polyfill needed for the Intl stuff to use the `DataPipes` from Angular 2 in Ionic.

<3

**Comment by tlancina** [comment]
:+1: LGTM, es6-shim added to bundle and package.json as a dependency for the starters.
