### ISSUE TITLE
Slideitems are too sensitive to clicks

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic2#314]
https://github.com/driftyco/ionic2/commit/52aa0548e79d39a0a53c47ad93050aa24bd944bd

Seems if you quickly use the mouse to drag the item, it triggers a click event, which in the tabs-starter triggers a state change.

https://github.com/driftyco/ionic2-starter-tabs/blob/master/www/app/chats/chats.html#L8

**Comment by mlynch** [comment]
I think I fixed this with 71627c327ab0b9f30756110735abf201896c12c3. Try it and let me know, going to close since it's the only oddity I can reproduce with the mouse and the tabs starter.

**Comment by mhartington** [comment]
Looks good, :+1:
