### ISSUE TITLE
android list items do not align properly

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic2#318]
<img width="360" alt="screen shot 2015-10-19 at 11 13 07 am" src="https://cloud.githubusercontent.com/assets/2018508/10583366/1beadef2-7652-11e5-94d6-e3c603d0ef5f.png">

Text inside of toggles seem to align, but not inside items.

**Comment by mhartington** [comment]
Seems like this was what effected it https://github.com/driftyco/ionic2/commit/069ac65e24ca617a7bbb41f808ebcce34874f902


https://github.com/driftyco/ionic2/blob/master/ionic/components/item/modes/md.scss#L153

**Comment by drewrygh** [comment]
Yeah, it looks like that caused it. Let's move this over to #273 (duplicate)
