### ISSUE TITLE
docs: add "what's new in 2.0" 

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#320]
It would be good to have a section in the docs that explains what we've changed/added in 2.0 that differs from 1.0. Maybe this could go in the migration section?

**Comment by adamdbradley** [comment]
Good idea. I think the migration section would be a good location for this. cc/ @mhartington

**Comment by brandyscarney** [comment]
We should list the components that are new, and what has been changed or added to existing components.

For example:

New: segment, searchbar
Changed: menu can now be reveal, overlay, etc.

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-site#338
