### ISSUE TITLE
(questions) List and Virtual Scroll

### ISSUE THREAD

**Issue by danicomas** [driftyco/ionic2#325]
I have some doubts:

- List Virtual Scroll = Collection Repeat (JS Scolling) or has it native scroll too?
- It only render the items shown as Collection Repeat?
- What changes it has?

**Comment by adamdbradley** [comment]
Currently it's a work in progress and doesn't remove items that are not in the viewable area.

**Comment by adamdbradley** [comment]
Closing in favor of https://github.com/driftyco/ionic2/issues/382
