### ISSUE TITLE
Ionic serve uses hard-coded path to app.scss file

### ISSUE THREAD

**Issue by flavordaaave** [driftyco/ionic2#328]
See:
https://github.com/driftyco/ionic-app-lib/blob/v2/lib/transpile.js#L179
var sassFile = path.join(appDirectory, 'www', 'app', 'app.scss‘);

The path to the Sass file is hard coded which means I can't put hte app.scss file anywhere else in my www folder like
www
—app
——styles
———app.scss

=> ionic serve thorws error:

∆ Compiling your SASS to CSS.
Error: File to read not found or unreadable: /Users/USERNAME/Projects/PROJECTNAME/www/app/app.scss
   at Object.module.exports.renderSync (/Users/USERNAME/.node/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/node-sass/lib/index.js:424:22)
   at Object.processSass (/Users/USERNAME/.node/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/transpile.js:163:25)
...

**Comment by tlancina** [comment]
Ah yes this definitely needs to be configurable. I would propose we move sass to gulp or use a webpack loader by default.  @adamdbradley @jbavari thoughts?

**Comment by mhartington** [comment]
There's a lot of movement around using webpack, for this, which would make some sense. Since we have a default webpack.conf in the CLI if one is not detected. Though gulp would make whole process easier. 

Each has some pros and cons.

**Comment by tlancina** [comment]
I honestly like going all in on the webpack config as the single source of configuration, then if you have sass loaders they can be used, but if you prefer you can run a gulp watch task alongside webpack for whatever additional tasks you may need (sass for example).

Only thing I'm worried about is the learning curve for webpack, but since we've already committed to it may as well take advantage of everything it offers and make sure document everything really well.

**Comment by changalberto** [comment]
My apologies to intrude in the middle. Just throwing my 2 cents out here for the sake of hearing options.

Have you guys considered http://www.rollupjs.org

Would like to hear your thoughts.

**Comment by adamdbradley** [comment]
Let's go with the all in on webpack route, and iterate from there.

**Comment by tlancina** [comment]
Should be fixed in the latest `ionic@alpha`, you can configure the Sass paths in `ionic.config.js` which will be autogenerated for you after you run `ionic serve`.
