### ISSUE TITLE
background image card

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic2#329]
<img width="409" alt="screen shot 2015-10-23 at 10 53 53 am" src="https://cloud.githubusercontent.com/assets/2018508/10698236/9ea03862-7975-11e5-9702-db3b8d4e8089.png">

@bensperry put together some pretty slick mocks for a background image card. They are [implemented here](http://ionicframework.com/docs/v2/components/#card-background) with custom CSS. 

**Do we want to create new card components and directives so this can be done without any custom code?** Maybe something similar to this:

```
<ion-card background="myImage.png">
  <ion-card-title>Title</ion-card-title>
  <ion-card-subtitle>Subtitle</ion-card-subtitle>
</ion-card> 
```
cc @adamdbradley

**Comment by adamdbradley** [comment]
prefer just having them use CSS, rather than learning something new that ends up just using css
