### ISSUE TITLE
Don't use 'id' for component registration

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic2#332]
Proposing `ion-id`, since id already has a clearly defined purpose and is confusing for beginners reading the markup.

**Comment by adamdbradley** [comment]
Only 1 `id` should be on a webpage. Same goes for how we want to identify components. For now we'll reuse `id` and re-evaluate if it's causing issues.

**Comment by tlancina** [comment]
http://www.joshmorony.com/ionic-2-first-look-series-your-first-ionic-2-app-explained/#comment-2321533578

When I read the markup, there's nothing telling me that it isn't for CSS.  Googling ion-id is a lot easier than googling id.
