### ISSUE TITLE
Can't create new project

### ISSUE THREAD

**Issue by thangman22** [driftyco/ionic2#334]
After run command ionic create it show response like this

Starting an Ionic v2 application
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip
[=============================]  100%  0.0s
Installing Node Modules

Unable to run exec commandError: Command failed: /bin/sh -c npm install
npm WARN package.json @ No repository field.
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3

npm ERR! Invalid name: "@reactivex/rxjs"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/waratwongmaneekit/Desktop/cutePuppyPics/npm-debug.log
 (CLI v2.0.0-alpha.9)

Your system information:

Cordova CLI: 5.1.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic CLI Version: 2.0.0-alpha.9
Ionic App Lib Version: 0.5.0-alpha.9
ios-deploy version: 1.4.0 
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v4.1.0
Xcode version: Xcode 7.0 Build version 7A220

**Comment by tlancina** [comment]
Do you still get this error with the latest version of the CLI `ionic@alpha`?

**Comment by jvaranam** [comment]
I am also getting the similar error  Plz provide a solution 
E:\wamp\www\>ionic start ionic-todo blank --v2
Downloading: https://github.com/driftyco/ionic2-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic2-starter-blank/archive/master.zi

Installing Node Modules

Unable to run exec commandError: Command failed: npm WARN package.json @ No rep
sitory field.
npm http GET https://registry.npmjs.org/ionic-framework/2.0.0-alpha.31
npm http 304 https://registry.npmjs.org/ionic-framework/2.0.0-alpha.31
npm http GET https://registry.npmjs.org/reactivex/rxjs/5.0.0-alpha.4
npm http GET https://registry.npmjs.org/lodash/3.10.1
npm http GET https://registry.npmjs.org/angular2/2.0.0-alpha.44
npm http GET https://registry.npmjs.org/es6-shim/0.33.6
npm http GET https://registry.npmjs.org/shelljs/0.5.3
npm http GET https://registry.npmjs.org/zone.js/0.5.8
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/inquirer/0.11.0
npm http GET https://registry.npmjs.org/q/1.4.1
npm http GET https://registry.npmjs.org/reflect-metadata/0.1.1
npm http 404 https://registry.npmjs.org/reactivex/rxjs/5.0.0-alpha.4
npm ERR! error rolling back Error: ENOTEMPTY, rmdir 'E:\wamp\www\ionic-todo\node_modules\ionic-framework\dist\js'
npm ERR! error rolling back  ionic-framework@2.0.0-alpha.31 { [Error: ENOTEMPTY
 rmdir 'E:\wamp\www\ionic-todo\node_modules\ionic-framework\dist\
s']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: 'E:\\wamp\\www\\ionic-todo
\node_modules\\ionic-framework\\dist\\js' }
npm ERR! 404 'reactivex' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Windows_NT 6.0.6002
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\no
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! cwd E:\wamp\www\ionic-todo
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! code E404
npm http 304 https://registry.npmjs.org/angular2/2.0.0-alpha.44
npm http 304 https://registry.npmjs.org/lodash/3.10.1
npm http 304 https://registry.npmjs.org/es6-shim/0.33.6
npm http 304 https://registry.npmjs.org/shelljs/0.5.3
npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/zone.js/0.5.8
npm http 304 https://registry.npmjs.org/inquirer/0.11.0
npm http 304 https://registry.npmjs.org/q/1.4.1
npm http 304 https://registry.npmjs.org/reflect-metadata/0.1.1
 (CLI v2.0.0-alpha.18)

Your system information:

Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic CLI Version: 2.0.0-alpha.18
Ionic App Lib Version: 2.0.0-alpha.17
OS: Windows Vista SP2
Node Version: v0.10.22

**Comment by tlancina** [comment]
@jvaranam does updating node to at least 0.12 and npm to 2.0 help? Those are both pretty old, and it seems to be choking on the scoped @reactivex package

**Comment by thangman22** [comment]
Still got problem

**Comment by horochovec** [comment]
Same problem here:

836 verbose stack Error: Invalid name: "@reactivex/rxjs"
836 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:302:15)
836 verbose stack     at Object.module.exports.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:206:5)
836 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:38
836 verbose stack     at Array.forEach (native)
836 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:28:15)
836 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:338:5)
836 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
836 verbose stack     at serverjs_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:166:29)
836 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:161:5
836 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)


Your system information:

Cordova CLI: 5.1.1
Gulp version:  CLI version 0.3.0
Gulp local:  
Ionic CLI Version: 2.0.0-alpha.18
Ionic App Lib Version: 2.0.0-alpha.17
ios-deploy version: Not installed
ios-sim version: 4.1.1 
OS: Mac OS X Yosemite
Node Version: v4.2.1
Xcode version: Xcode 7.1 Build version 7B91b

**Comment by tlancina** [comment]
What version of npm do you have? I'm unable to reproduce this on Windows or OS X.

**Comment by tlancina** [comment]
Was unable to reproduce this on either platform, any updates on this?

**Comment by thangman22** [comment]
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3

**Comment by thangman22** [comment]
This is current error 
Unable to run exec commandError: Command failed: /bin/sh -c npm install --production
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3

npm ERR! Invalid name: "@reactivex/rxjs"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/waratwongmaneekit/Desktop/web/MyIonic2Project/npm-debug.log
 (CLI v2.0.0-alpha.25)

**Comment by tlancina** [comment]
@thangman22 it looks like https://github.com/npm/npm/issues/10344, would you be able to paste your npm-debug.log over there?

**Comment by tlancina** [comment]
Also https://github.com/ReactiveX/RxJS/issues/727 suggests that upgrading to npm 3 might fix it, but I'm not sure if you want to do that necessarily.

**Comment by simsketch** [comment]
Unable to run exec commandError: Command failed: /bin/sh -c npm install
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.

**Comment by simsketch** [comment]
[npm-debug.txt](https://github.com/driftyco/ionic2/files/63805/npm-debug.txt)

**Comment by tlancina** [comment]
Reactive has changed their package name to just rxjs, which hopefully fixes the issue. Please feel free to re-open if this is still a problem.
