### ISSUE TITLE
refactor the platform module to a standalone npm package

### ISSUE THREAD

**Issue by nihgwu** [driftyco/ionic2#336]
I don't think the native plugin related code should be included in the core package

* I also write web app using ionic, there is no need or method to use the native plugin
* some of the included native plugins didn't work well, for example, the `network` plugin, i got `isOnline() = false` when test on a phone support two SIM cards as `navigator.connection.type == 'unknown'`, and for `geolocation`, it doesn't work on some android version, i have to write my own` LocationService` using other plugin too

So i think a standalone package just like `ngcordova` for `ionic1` would be fine

**Comment by mlynch** [comment]
Thanks for the issue. This was a design decision we made with v2 to make it easier to use device plugins and web APIs right from Ionic. Their stability is a separate issue that we should address, but we are keeping them in the core for now.

**Comment by mlynch** [comment]
I should add: I totally get your perspective, and we are currently trying this out but it might end up going into its own module. Don't want to change anything right this second though.

**Comment by nihgwu** [comment]
thank you all for your efforts to make ionic better
BTW, what about the `isOnline() = false` issue i mentioned, should i address it in a new issue or just keep it and create our own implementation?

**Comment by mlynch** [comment]
Hey @nihgwu can you try master? Just pushed a fix.

**Comment by nihgwu** [comment]
thanks a lot for so quick fix, i'll try it later
if's really a rare case that `navigator.connection.type` returns `unknown` when using a phone with dual SIM cards
