### ISSUE TITLE
NO SideNav starter template

### ISSUE THREAD

**Issue by ajayequinix** [driftyco/ionic2#337]
I was trying Angular2 but there is not sidebar template like angular 1, so any Idea when it would be available.

**Comment by tlancina** [comment]
Hey @ajayequinix we're in the process of updating all of the starters right now, including a side menu one.

**Comment by tlancina** [comment]
It should be available now, once you've updated to the latest alpha CLI `ionic@alpha` do `ionic start MyApp sidemenu --v2`
