### ISSUE TITLE
Menu only on root NavController?

### ISSUE THREAD

**Issue by Vargash** [driftyco/ionic2#338]
Trying to recreate my current app from v1 to v2, I've made a first NavController for the Login part (no menu, no nav-header, just a plain page), which then starts a new, nested NavController after the login.
This nested controller contains a sideMenu.

Problem is that, trying to open it, there are lots of errors like this:
__TypeError: Failed to set the 'currentTime' property on 'Animation': The provided double value is non-finite.__

**Comment by adamdbradley** [comment]
Would you be able to put together some pseudo code describing how it works?

**Comment by Vargash** [comment]
Sure... hoping it will not become too cluttered, I'll add down here the main useful parts, just to give an idea of the general structure of the problem :)

**app** is the main component, while **logged** is the component loading the nested NavController, in which I'm trying to put the menu.


/* **app** */
```
import {App, IonicApp, Platform} from 'ionic/ionic';
import {WelcomePage} from './welcome/welcome';

@App({
  template: '<ion-nav id="nav" [root]="rootPage" swipe-back-enabled="false"></ion-nav>'
})
class MyApp {
  constructor(app: IonicApp, platform: Platform) {
    this.app = app;
    this.platform = platform;
    this.rootPage = WelcomePage;
  }
}
```

/* **welcome** */
```
 import {Page, NavController} from 'ionic/ionic';
 import {LoggedPage} from '../logged/logged';

 @Page({
   templateUrl: 'app/welcome/welcome.html'  // Template here is useless, there's a button that calls "goToNext()"
 })

 export class LoginPage {
   constructor(nav: NavController) {
     this.nav = nav;
   }

   goToNext() {
     this.nav.push(LoggedPage);
   }
 }
```

/* **logged** */ 
```
// I think the .ts here is not particularly useful, so I'll just write the template
<ion-menu [content]="content">
 <ion-toolbar>
   <ion-title>Menu</ion-title>
 </ion-toolbar>
 <ion-content>
   <ion-list>
     <button ion-item *ng-for="#p of pages">
       {{ p.title }}
     </button>
   </ion-list>
 </ion-content>
</ion-menu>

<ion-nav id="nav-logged" [root]="rootPage" #content swipe-back-enabled="false"></ion-nav>
 ```

**Comment by adamdbradley** [comment]
Ok, i think i see the issue now and we'll have to make some updates so this works. Basically you're in the first nav and it has one page, and you're transitioning to another "page", but that page is another nav. I don't think any of our examples covered that yet, but that should absolutely work. I'll be sure to update our examples and update the code so this works.

In the meantime, I'd say use one nav that always has the sidemenu. Thanks for creating the issue and pointing this out!

**Comment by adamdbradley** [comment]
This should be fixed now in master: https://github.com/driftyco/ionic2/blob/master/ionic/components/nav/test/nested/index.ts

We'll have an updated Ionic version soon, thanks!
