### ISSUE TITLE
Navigating from page to tabs page

### ISSUE THREAD

**Issue by ydeshayes** [driftyco/ionic2#339]
Hello,
If I try to navigate from a login page to a tab page, there is no animation but everything work fine.
But if I Navigate from a page that have an history to a tab page, the previous page freeze on top of my tab page.

A workaround if to call the push function with these opts:
```javascript 
this.nav.push(TabsPage, {
      item: id
    }, {animate: false, cacheLeavingView:false});
```
But when the page switch, there is a small time where there is no page on screen.

Or add a ion-navbar to the tab page. But a page on a tab already need a ion-navbar so I can't just put a ion-navbar on a tab page because I will have this (since the nav-bar is on the page template when we include it in a tab page):

To reproduce the bug:
- Create a login page
- Create a page with a list of item
- Create a tab page with tabs
- Create the page for each tab
- The login button go to the list of item page (click)
- each item in the list link to the tab page (click)
- Run the app, click on the login button and click on an item in the list

Tell me if I do something wrong !

Thanks a lot !

**Comment by adamdbradley** [comment]
Thanks for the issue, we'll take a look.

**Comment by adamdbradley** [comment]
This should be fixed in master, and we'll be getting the next alpha version out soon. Here's a testing example: https://github.com/driftyco/ionic2/tree/master/ionic/components/tabs/test/advanced

thanks
