### ISSUE TITLE
docs: Add styling for v2 code

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#340]
Code blocks `<code>` aren't styled:

![screen shot 2015-10-26 at 1 58 35 pm](https://cloud.githubusercontent.com/assets/6577830/10737748/468d01ce-7bea-11e5-9bd9-c4ac47d6afc3.png)

This was v1 styling:

```
code {
  margin-left: 3px;
  margin-right: 3px;
  padding: 2px 4px;
  font-size: 85%;
  color: #4D8CF4;
  background-color: whitesmoke;
  white-space: nowrap;
  border-radius: 2px;
}
```

**Comment by mhartington** [comment]
Fixed via https://github.com/driftyco/ionic-site/commit/a00408172d1f33870e4fbd595099fce128a62e44
