### ISSUE TITLE
Create changelog

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#341]
Need to generate a changelog for Ionic2.

**Comment by jbavari** [comment]
Personally I love [github-changelog-generator](https://github.com/skywinder/github-changelog-generator). 

The only catch is, its a Ruby tool.

There's also the nice tool from Andrew Joslin, [conventional-changelog](https://github.com/ajoslin/conventional-changelog).

I think we should just take a look at both (or other options) and just decide as a team which may be more helpful for our users to help navigate through our changes.

**Comment by mhartington** [comment]
https://github.com/semantic-release/semantic-release

https://github.com/semantic-release/semantic-release#default-commit-message-format

https://github.com/commitizen/cz-cli

Just some other tools we could also look into to manually handle the process

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5077
