### ISSUE TITLE
http.get always return "success"

### ISSUE THREAD

**Issue by Miyada2000** [driftyco/ionic2#345]
Hey guys, 

I was just playing around and notice that calling an http.get always returns "success" or 200 even when the server returns 400/401;

Searching around i found some similar error on Angular 2. Just reporting to you guys keep track.

**Comment by adamdbradley** [comment]
Thanks for the report. Do you know the issue number in angular2?

**Comment by adamdbradley** [comment]
Closing for now since this would be an ng2 http issue. We'll keep an eye on it though, thanks
