### ISSUE TITLE
navbar: title text is truncated when unnecessary

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic2#350]
If there are no buttons in a navbar, the title text should be allowed to take most of the space without being truncated.

Eg:
<img width="319" alt="screen shot 2015-10-27 at 10 18 07 am" src="https://cloud.githubusercontent.com/assets/2018508/10762529/6d6c20ae-7c94-11e5-9b28-c2424515fe4c.png">

**Comment by brandyscarney** [comment]
This is caused by the padding that I mentioned here: https://github.com/driftyco/ionic2/issues/356#issuecomment-151660505

**Comment by adamdbradley** [comment]
Gonna group this in with this issue https://github.com/driftyco/ionic2/issues/820
