### ISSUE TITLE
docs: demo doesn't reset when clicking Overview

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#352]
If you click one of the components in the side menu, such as [popups](http://ionicframework.com/docs/v2/components/#popups), and then click overview to go back to the top it will still show that component demo. Should it reset to the Action Sheet demo or maybe none at all? 

![screen shot 2015-10-27 at 3 32 51 pm](https://cloud.githubusercontent.com/assets/6577830/10770127/05308aee-7cc0-11e5-9192-26dcf97409e0.png)

**Comment by drewrygh** [comment]
Good call. I'll change it to load action sheet
