### ISSUE TITLE
item: using ion-note inside of ion-card

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic2#353]
When using `ion-note` inside of `ion-card`:

```
  <ion-item actions>
      <button primary clear item-left>
        Left Button
      </button>
     <ion-note item-right>
       Right Note
     </ion-note>
  </ion-item>
```

the CSS from `ion-note` doesn't seem to get applied.

**Comment by brandyscarney** [comment]
The only CSS `ion-note` gets is the color, is this what you mean?

![screen shot 2015-10-29 at 6 03 16 pm](https://cloud.githubusercontent.com/assets/6577830/10833319/60ad9990-7e67-11e5-8cc8-52031cb7b838.png)
