### ISSUE TITLE
icons don't fall back to default version when outline version is missing

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic2#357]
If we have the following icon:

```html
<icon snow></icon>
```

when used in things like tabs, tabs will expect an `ion-ios-snow-outline` icon to exist. However, not all icons have an outline version, so it should fall back to the non-outline version. See [the Alaska card, tab 2](http://ionicframework.com/docs/v2/components/#card-advanced-weather) for an example.

**Comment by adamdbradley** [comment]
It'll have to be this way. In this exact case we'll make a snow-outline version.
