### ISSUE TITLE
Have to swipe two times in Ion-List with ion-item-sliding to make the option button visible(Ionic View IOS9)

### ISSUE THREAD

**Issue by ajaybeniwal** [driftyco/ionic2#358]
I am using Ion-List with Ion-item-sliding and I have delete button in options but i have to swipe left two times then only the option button is visible . I am testing the app on Ionic view and IOS 9.1

**Comment by brandyscarney** [comment]
I'm not seeing this in the conference app in Ionic View on iOS 9.1. Could you clone the conference app and see if you still have this problem? If not, can you compare your markup to that of the conference app?

https://github.com/driftyco/ionic-conference-app

The sliding items are here:

https://github.com/driftyco/ionic-conference-app/blob/master/www/app/components/schedule-list.html#L6-L19

**Comment by mlynch** [comment]
Not able to reproduce. If you have more info to help us narrow this down, that would help! Thanks.

**Comment by ajaybeniwal** [comment]
There is one more issue which I am facing when i swipe left on list item and click on option button it moves to next page and then shows me the the pop up confirmation which i have added to delete button.

**Comment by mlynch** [comment]
@ajaybeniwal we are going to need a lot more code/examples to narrow this down. Can you paste any snippets or a plunker. Also side note, @adam @mhartington @tlancina any chance we can get a plunker up for people to submit failing cases?

**Comment by ajaybeniwal** [comment]
Okay I will paste some code
