### ISSUE TITLE
Set typings files (.d.ts) for ionic/ionic

### ISSUE THREAD

**Issue by hlehmann** [driftyco/ionic2#360]
With webstorm I can't have the typing information for ionic2.
`tsd install ionic/ionic` seems to be for ionic 1.x

**Comment by mhartington** [comment]
Duplicate of #84

**Comment by jksoftpro** [comment]
For anyone looking for Ionic2 Type Definition please follow this link:
https://github.com/jksoftpro/ionic2-seed/blob/master/tools/typings/ionic2.d.ts

I created this one for version "ionic-framework": "2.0.0-alpha.36". It works well for me. I hope it will help.
