### ISSUE TITLE
Unable to add plugins when creating a new project

### ISSUE THREAD

**Issue by nicoabie** [driftyco/ionic2#362]
Here is the output:

nicoabie@minty ~/Development $ sudo ionic start ionic2test --v2
Starting an Ionic v2 application
Downloading: https://github.com/driftyco/ionic2-starter-tabs/archive/master.zip1
[=============================] 100% 0.0s
Installing Node Modules
Updated the hooks directory to have execute permissions
Adding native plugins

Unable to add plugins. Perhaps your version of Cordova is too old. Try updating (npm install -g cordova), removing this project folder, and trying again. (CLI v2.0.0-alpha.9)

Your system information:

Cordova CLI: 5.3.3
Gulp version: CLI version 3.8.11
Gulp local: Local version 3.9.0
Ionic Version: 2.0.0-alpha.30
Ionic CLI Version: 2.0.0-alpha.9
Ionic App Lib Version: 0.5.0-alpha.9
OS: Distributor ID:	LinuxMint Description:	Linux Mint 17 Qiana 
Node Version: v4.2.1

If you guys need any other information or me to do something would be more than happy to help

**Comment by mhartington** [comment]
You shouldn't need to use sudo to create a new project. This will change the permissions of the directory. 
Try creating a new project without sudo.

**Comment by nicoabie** [comment]
Thanks a lot Mike, will test it as soon as I get home and let you know.

**Comment by irhabi** [comment]
I've got the same issue and I'm not using sudo.

**Comment by mhartington** [comment]
@irhabi please provide the out put from `ionic info`

**Comment by irhabi** [comment]
@mhartington 
Your system information:

Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic CLI Version: 2.0.0-alpha.9
Ionic App Lib Version: 0.5.0-alpha.9
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.10 
Node Version: v4.2.1

**Comment by irhabi** [comment]
Reinstalling npm and all modules helped me.

Your system information:

Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 2.0.0-alpha.30
Ionic CLI Version: 2.0.0-alpha.9
Ionic App Lib Version: 0.5.0-alpha.9
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.10 
Node Version: v4.2.1


Now I've got other issue :P
https://github.com/driftyco/ionic-cli/issues/623

**Comment by nicoabie** [comment]
I installed again ionic@alpha, run ionic start without sudo and it could execute well but now having same issue as @irhabi

**Comment by tlancina** [comment]
I believe the original issue was the `sudo` install, the other issue should be resolved in https://github.com/driftyco/ionic-app-lib/issues/37.  Let us know if this isn't the case, thanks!
