### ISSUE TITLE
docs: add search and segment demo

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic2#368]
Add both to the content menu.

> Also
for both of them we’ll want to show them in a toolbar and one without
right now the not being in a toolbar works the best

**Comment by brandyscarney** [comment]
When the component is in the `toolbar` I think we should use `ng-model` on it, but when it's floating in the `ion-content` it would be good to represent it in a `form`. Just to show the different uses for both components.

**Comment by drewrygh** [comment]
:+1:
