### ISSUE TITLE
click state of list items in cards should not have border radius

### ISSUE THREAD

**Issue by bensperry** [driftyco/ionic2#373]
unless they are the very top or bottom - then the top/bottom corners can still have the border radius.

![image](https://cloud.githubusercontent.com/assets/519526/10820588/00455c96-7e1c-11e5-955a-26ea23303e17.png)

**Comment by brandyscarney** [comment]
hmmm I should've fixed this in https://github.com/driftyco/ionic2/issues/366. @drewrygh do the docs have latest?

**Comment by brandyscarney** [comment]
Yep, this was fixed by #366, Drew updated the docs and it's good now.
