### ISSUE TITLE
Android cards aren't getting border radius in docs

### ISSUE THREAD

**Issue by bensperry** [driftyco/ionic2#374]
![image](https://cloud.githubusercontent.com/assets/519526/10821215/39fae926-7e1f-11e5-81f9-63798073f113.png)

**Comment by brandyscarney** [comment]
Related to this: https://github.com/driftyco/ionic2/issues/346 so I'll work on it

**Comment by brandyscarney** [comment]
I'm not sure what fixed this, but it's working now.
