### ISSUE TITLE
docs: add content/code examples to cards and lists

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic2#375]
- [ ] card/background images
- [x] card/social
- [x] card/map
- [ ] card/weather
- [x] list/dividers
- [x] list/headers
- [x] list/icon
- [x] list/avatar

**Comment by brandyscarney** [comment]
https://github.com/driftyco/ionic-site/commit/0baf57c12a2e04457fbd0840d8779b4352b50955#diff-c38803de830d74d0fb3ebc9dd6fc50da
