### ISSUE TITLE
Ionic2 with JSPM

### ISSUE THREAD

**Issue by vadimpopa** [driftyco/ionic2#379]
I've been trying ionic2 with JSPM and I get:

```javascript
Uncaught (in promise) Error: ionic2_1.Page is not a function(…

// Thrown at @Page

import {IonicApp, Page, NavController, NavParams} from 'ionic2';

@Page({
  templateUrl: 'app/item-details/item-details.html'
})
```
Anyone has any clue what might be the cause of it. Is working fine though with Angular2  + JSPM + Typescript. Is failing only with Ionic2.

The import is mapped to: 
```javascript
"ionic2": "npm:ionic-framework@2.0.0-alpha.30/js/ionic.js"
```

https://github.com/vadimpopa/jspm-ionic2-starter

**Comment by vadimpopa** [comment]
Advanced a little with this, the app is opening fine through the es5/common. The typescript is throwing and error, gonna debug within next days and report it here.

**Comment by tlancina** [comment]
We don't ship TS sources for Ionic anymore, just CJS + definitions so I'm going to close this.
