### ISSUE TITLE
docs: icons are off centered

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic2#384]
![screen shot 2015-10-29 at 4 40 16 pm 1](https://cloud.githubusercontent.com/assets/2835826/10831409/e0d67364-7e5b-11e5-9def-d1daef52e402.png)

**Comment by brandyscarney** [comment]
Where is this? I don't see it here: http://ionicframework.com/docs/v2/components/#floating-action-buttons

**Comment by mhartington** [comment]
In safari. Can't confirm it in chrome, the preview doesn't stick for me.

**Comment by brandyscarney** [comment]
Ah, yes. I see it in Safari but not Chrome.

**Comment by brandyscarney** [comment]
This is no longer an issue.
