### ISSUE TITLE
docs: previews window is not sticking in chrome

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic2#386]
At least for me, but I'm not sure whats up. At least the preview window isn't getting the fixed class

**Comment by mhartington** [comment]
Version 46.0.2490.80 (64-bit)

**Comment by brandyscarney** [comment]
Weird, I have the same version of Chrome and it sticks for me.

**Comment by mhartington** [comment]
Fixed via https://github.com/driftyco/ionic-site/commit/c6f569c86a79907da4b7a6d8959bc29c7c5626ce
