### ISSUE TITLE
docs: tab content is not visible

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic2#390]
<img width="389" alt="screen shot 2015-10-29 at 6 06 26 pm" src="https://cloud.githubusercontent.com/assets/2018508/10834489/bac84e20-7e67-11e5-82c8-de78b5c0fbb8.png">

**Comment by adamdbradley** [comment]
If the tab is supposed to work like a page then it use @Page: https://github.com/driftyco/ionic2/blob/master/ionic/components/tabs/test/basic/index.ts#L11

In general the tabs container should stay transparent to avoid flickers.
