### ISSUE TITLE
active state for android List in Card example is broken

### ISSUE THREAD

**Issue by bensperry** [driftyco/ionic2#391]
Doesn't look right and the ripple is barely visible. Not sure what happened...

**Comment by bensperry** [comment]
actually, this might have something to do with @drewrygh changing the tabs in the weather demo to have a white ripple...

**Comment by brandyscarney** [comment]
Yes, I say Drew did it. ;)

**Comment by bensperry** [comment]
You would. >_>

**Comment by brandyscarney** [comment]
On a serious note, I checked this in the source code and the ripple shows fine, so I think it is related to the docs css.
