### ISSUE TITLE
importing IONIC_DIRECTIVES not working

### ISSUE THREAD

**Issue by stellasoft-will** [driftyco/ionic2#393]
while making a custom component that uses ionic components, my understanding was that i must import the IONIC_DIRECTIVES array from ionic/ionic. this results however in an undefined array. Any ideas?

**Comment by adamdbradley** [comment]
Can you show an example of the code? Importing IONIC_DIRECTIVES should work.

**Comment by stellasoft-will** [comment]
import {Component, View} from 'angular2/angular2';
    import {IONIC_DIRECTIVES} from 'ionic/ionic';
    
    @Component({
        selector:'chat-component',
    })
    @View({
        templateUrl:'app/chat-component/chat-component.html',
        directives: [IONIC_DIRECTIVES]
    })
    
    export class ChatComponent{
        constructor(){
    
        }
    }

this works if in this case I use  "Icon" directive instead of the "IONIC_DIRECTIVES" as i am using icon in the template html.

**Comment by cosmaioan** [comment]
I have the same problem
Any update or workaround how to build a custom component ?

**Comment by stellasoft-will** [comment]
If you want to build a custom component, then load the ionic components individually into the directives array on your component rather than using this IONIC_DIRECTIVES array.

example:

import {Component, View} from 'angular2/angular2';
    import {Icon} from 'ionic/ionic';

    @Component({
        selector:'chat-component',
    })
    @View({
        templateUrl:'app/chat-component/chat-component.html',
        directives: [Icon]
    })

    export class ChatComponent{
        constructor(){

        }
    }

**Comment by adamdbradley** [comment]
Yeah, forgot to export IONIC_DIRECTIVES. Should be fixed now, thanks!
