### ISSUE TITLE
Ionic 2 with Meteor

### ISSUE THREAD

**Issue by ansarizafar** [driftyco/ionic2#395]
Is it possible to use Ionic 2 with Meteor? If yes then how to install Ionic 2 for Meteor.

**Comment by mlynch** [comment]
Yes, it should be, since meteor is doing a lot of ng2 talk right now. However, this is a question for them not us, so I'm going to close. Thanks!

**Comment by jaydenhe** [comment]
it is coming soon. I look forward it.  @mlynch

**Comment by MoeBadr** [comment]
@mlynch Any idea when soon might be ?

**Comment by mlynch** [comment]
@MoeBadr no and I'm not the right person to ask. I'll leave it open for them to jump in if they like. cc @urigo

**Comment by MoeBadr** [comment]
@mlynch Thanks for reopening. Hi @urigo when do you think we will be able to start using Ionic 2 with meteor ?, I'm happy to help with testing etc, please let me know if I can be of any assistance. Thanks :)

**Comment by kyle-007** [comment]
+1

**Comment by adamdbradley** [comment]
Has you taken a look at http://www.angular-meteor.com/angular2 ?

**Comment by kyle-007** [comment]
Yes I did. However I could not find info regarding ionic 2 (with Angular 2). Or did I miss something? Thanks.

**Comment by adamdbradley** [comment]
I personally haven't tried integrating it with Ionic2, however, it being built on top of Angular2 it may not require any integration with Ionic2. Maybe @urigo knows more.

**Comment by Muffasa** [comment]
what must one do in order to start developing with ionic2 and meteor?

**Comment by mhartington** [comment]
This is a question best suited for meteor, not really ionic.

http://www.angular-meteor.com/angular2
