### ISSUE TITLE
Docs: Update the API docs

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#399]
It's pretty out of date: 

http://ionicframework.com/docs/v2/api/config/IonicView/
http://ionicframework.com/docs/v2/api/config/IonicConfig/
http://ionicframework.com/docs/v2/api/net/Http/

**Comment by brandyscarney** [comment]
Also, I'd be interested in knowing how the menu is generated. We aren't calling popup "ionPopup" anymore:

http://ionicframework.com/docs/v2/api/components/popup/ionPopup/

Does there need to be a `@name` or `@description` in here for it to pull from?

https://github.com/driftyco/ionic2/blob/master/ionic/components/popup/popup.ts#L11-L63

**Comment by tlancina** [comment]
When we run gulp docs, it updates nightly unless you specify a version.  To update the 2.0.0 api docs (and menu) do `gulp docs --doc-version=2.0.0` and then make sure that https://github.com/driftyco/ionic-site/blob/master/_includes/v2_fluid/api_menu_flat_2.0.0.html gets updated.  It looks like neither menu is up to date.
