### ISSUE TITLE
bug: Fab button ripple is square

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#400]
The md-ripple is square on the fab button. I did some debugging on it and the height/width is larger than the fab button itself, so I think some calculations may be off. Applying border-radius doesn't do anything because the height/width is larger than the border-radius will cut. 

![screen shot 2015-10-30 at 11 58 24 am](https://cloud.githubusercontent.com/assets/6577830/10850755/b08b36fc-7efd-11e5-9453-9086eb1f1615.png)

**Comment by adamdbradley** [comment]
Probably needs overflow hidden and whatnot

**Comment by nampdn** [comment]
Hi, this issue was repeat in alpha 42 now. Please fix it.

**Comment by drewrygh** [comment]
This also affects buttons with the `round` attribute

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5074
