### ISSUE TITLE
Docs: Android menu isn't hiding

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#401]
The menu isn't hiding all of the way after you show it and then hide it. http://ionicframework.com/docs/v2/components/#menus

![screen shot 2015-10-30 at 1 14 18 pm](https://cloud.githubusercontent.com/assets/6577830/10852749/b925ba16-7f08-11e5-8f0a-220af2735453.png)

**Comment by drewrygh** [comment]
Also, we need to disable it on all other pages.
