### ISSUE TITLE
Modify config.get() so that it will return all keys if a key isn't passed

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#402]
Should just return all the keys for the platform if one isn't passed:
https://github.com/driftyco/ionic2/blob/master/ionic/config/config.ts#L112-L205

**Comment by adamdbradley** [comment]
That's what `settings` is for. I originally had `get` overloaded with many different ways of calling it, but it's just too hard to document. https://github.com/driftyco/ionic2/blob/master/ionic/config/config.ts#L58

**Comment by adamdbradley** [comment]
Plus, the emerging pattern is to not use `arguments` like how jQuery uses them. There's some performance draw backs to using it (barely measurable I know), but throughout the ionic2 code we have explicit gets and sets for one thing.

**Comment by mhartington** [comment]
Calling `settings` though returns an empty object. Shall I open a new issue?

**Comment by adamdbradley** [comment]
I'm confused what you're trying to do though. If it's empty then there's nothing that's been set.

**Comment by brandyscarney** [comment]
Much like get(key) we want to get all of the keys that are set. Imo there should be a getConfig() which returns all of the current settings and a getKey(key) for one particular keys settings.

**Comment by adamdbradley** [comment]
Not following why we'd want get(key) and getKey(key).

**Comment by brandyscarney** [comment]
Sorry, I meant rename it so it makes more sense what it does.

**Comment by adamdbradley** [comment]
But we're not getting a key. `get(key) returns value` is about as simple as we can make it. `settings` returns the settings which the user created. And we're not able to easily figure out every key because settings doesn't know what every possible setting is available.

**Comment by mhartington** [comment]
okay, then how do we go and get the current config? Not a single value, but the whole object

**Comment by adamdbradley** [comment]
Why do you want to do that though? Wouldn't you just want a certain value when you want that value? When would you want to get every possible key/value, rather than just calling for what you need. The thing is settings can't easily figure out all of the possible key/values that have been set in all the different ways they've been set, such as the querystring values. And if we did write the code to do so, I don't see how it'd be more powerful than just `get`.

**Comment by mhartington** [comment]
But how would I know what values there are to begin with? You should be able to just return the config config object and see what everything is set to.


Say I do `config.get('titlePosition')`. How do I know if titlePosition is valid?

**Comment by adamdbradley** [comment]
Docs. Like the same reason you'd know to call `config.settings`
