### ISSUE TITLE
Question: itemTapped() jumping list to top

### ISSUE THREAD

**Issue by robyedlin** [driftyco/ionic2#406]
Hi,

I noticed on all of the demos that when you click an item in a list, the list jumps back to the top. I think that's not ideal behavior. When you click "Back" it should go to the previous position on the list, not the top.

I'm not sure if this is related, but when itemTapped() is executed, not only does it jump the list to the top before navigating to the new view, but there is a flicker before the nav transitions, at least on iOS.

Awesome work so far on Ionic 2. So pumped to get an app going on this.

**Comment by robyedlin** [comment]
I should note that this only happens on iOS when the list has enough items to scroll. The default themes wouldn't catch this because they only have a few items.

**Comment by mlynch** [comment]
Yea, definitely shouldn't be happening! Adding @adamdbradley and @drewrygh on this in case the demo is just mis configured.

**Comment by robyedlin** [comment]
Ok, cool. If there is a hot fix please let me know. I'm almost ready to launch my app in v2!

**Comment by mlynch** [comment]
Tracking this Angular issue that I just filed: https://github.com/angular/angular/issues/5077

Working on a fix in the short term

**Comment by robyedlin** [comment]
Awesome. You guys rock.

**Comment by robyedlin** [comment]
Max, your fix here https://github.com/angular/angular/issues/5077#issuecomment-153177850 seems to solve the problem in the short term. If I can patch, lmk the best place to do it. The function is present on many files outside the www folder, but changing them doesn't seem to update www/app/build/js/app.bundle.js.

Thanks for your help on this.

**Comment by mlynch** [comment]
Okay, our version of ng2 has this fix in so we're good for now and will keep tracking the official angular fix until it gets merged

**Comment by robyedlin** [comment]
Thanks @mlynch
