### ISSUE TITLE
Question: How to disable swipe to sidemenu

### ISSUE THREAD

**Issue by robyedlin** [driftyco/ionic2#407]
Hi,

Is there a way to disable the swipe left to sidemenu feature?

**Comment by changalberto** [comment]
I think if you do

```html
<ion-nav swipe-back-enabled="false" [root]="rootPage"></ion-nav>
```

[http://ionicframework.com/docs/v2/api/components/nav/Nav/](http://ionicframework.com/docs/v2/api/components/nav/Nav/)

That should to it.

**Comment by robyedlin** [comment]
That doesn't do it. That setting is enabled by default in www/app.html. Swiping to reveal the sidemenu still works.

**Comment by adamdbradley** [comment]
Just added that feature and an example is here:
https://github.com/driftyco/ionic2/blob/master/ionic/components/menu/test/multiple/index.ts

It'll be in alpha.31 which we'll release soon.

**Comment by 3dd13** [comment]
@adamdbradley this enable(false) disable the whole sidemenu, but not only the swipe/drag
