### ISSUE TITLE
ionic serve not Working on node 4

### ISSUE THREAD

**Issue by ansarizafar** [driftyco/ionic2#409]
∆ Starting browser sync.

[BS] Access URLs:
 ------------------------------------
       Local: http://localhost:8100
    External: http://192.168.1.3:8100
 ------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.3:3001
 ------------------------------------
[BS] Serving files from: www
[BS] Watching files...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn google chrome ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)

**Comment by beautyfree** [comment]
Yes. For myself, I solved this problem by using:
```
ionic serve -b
```

This can be a temporary solution.

**Comment by tlancina** [comment]
This should be solved in the latest version of the CLI (`ionic@alpha`), please re-open if it's not, thanks!
