### ISSUE TITLE
feature(ion-item-sliding): Allow item also to swipe from left to right

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#411]
I want to swipe my ionic list items to both side. (i.e left-right AND right-left). It work perfectly for right-left swipe but i am not able to swipe my list item left-righ (to see buttons on left side).

Here is an example workaround: http://stackoverflow.com/a/31816296/1975086

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5073
