### ISSUE TITLE
No TouchableHighlight on list-view

### ISSUE THREAD

**Issue by ajaybeniwal** [driftyco/ionic2#413]
When I tap on ion-item in list view there is no feeling of touchable highlight on the row similar to IOS or ionic 1

**Comment by adamdbradley** [comment]
What does your markup look like? Are you using a `<button ion-item>`?

**Comment by ajaybeniwal** [comment]
` <ion-list>
    <ion-item-sliding *ng-for="#chat of chats" (click)="passChat(chat)">
      <ion-row center>
      <h2 class="col">{{chat.name}}</h2>
      <p class="col flex"><span style="margin-right:10px;">{{chat.status}}</span><icon ios="ion-ios-arrow-forward" md="ion-social-android"></icon></p>
      </ion-row>
      <ion-row><p class="col">{{chat.lastText}}, {{chat.shipmentText}}</p></ion-row>
        <ion-row><p class="col">{{chat.dateText}}</p></ion-row>
      <ion-item-options>
        <button light (click)="remove(chat)">Reject</button>
        <button  (click)="accept(chat)">Accept</button>
      </ion-item-options>
    </ion-item-sliding>
  </ion-list>`
