### ISSUE TITLE
Remove need for user to supply ion-overlay

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic2#415]
We know the reasons this is required from the ng2 standpoint, but it's not okay to have to have the user put this in their code.

Some ideas: have ion-app use ng-content, then we can put <ion-overlay> into the index.html for each starter project by default.

Another idea: patch angular 2 to make this work (probably tough especially considering the pushback from upstream)

**Comment by adamdbradley** [comment]
dup https://github.com/driftyco/ionic2/issues/313
