### ISSUE TITLE
Docs: NavController descriptions for all methods

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#417]

**Comment by adamdbradley** [comment]
And make sure there are descriptions for each param and return value

**Comment by mhartington** [comment]
`push`, `pop`, `popTo`,`popToRoot`, `insert`, `remove`, `setViews`, `setRoot`

Should `_transition` be set to private? https://github.com/driftyco/ionic2/blob/master/ionic/components/nav/nav-controller.ts#L433

**Comment by adamdbradley** [comment]
yes

**Comment by mhartington** [comment]
http://ionicframework.com/docs/v2/api/components/nav/NavController/
