### ISSUE TITLE
Should search-bar be renamed?

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#419]
For consistency reasons, we have 

`ion-toolbar`: https://github.com/driftyco/ionic2/blob/master/ionic/components/toolbar/toolbar.ts#L59
`ion-navbar`: https://github.com/driftyco/ionic2/blob/master/ionic/components/nav-bar/nav-bar.ts#L53

and on that note the `nav-bar` directory differs, as well. Search bar is declared as `ion-search-bar` though: https://github.com/driftyco/ionic2/blob/master/ionic/components/search-bar/search-bar.ts#L18

I guess the question is should these all have dashes or all not have dashes?

**Comment by adamdbradley** [comment]
Yeah I hate this one cuz I keep flip floppin. So `toolbar` is one word:
https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=toolbar

Navigation Bar is two words (nav-bar)
Search Bar is two words (search-bar)
Tab Bar is two words (tab-bar)

But all that aside, them being different is annoying. So should the standard be that anything that ends with `bar` should be one word?

**Comment by brandyscarney** [comment]
I'm kind of impartial. My only argument for using the dash is that v1 uses `ion-nav-bar`. I think whichever way we go they should be consistent though.

@drewrygh any thoughts?

**Comment by adamdbradley** [comment]
True, if ionic v1 uses ion-nav-bar then there's not a big enough reason to change it to ion-navbar, especially when it'd be more consistent with ion-search-bar and ion-tab-bar. The odd ball is ion-toolbar, but `toolbar` is a word, it's not two words.

**Comment by drewrygh** [comment]
I'd be fine with either, as long as they are consistent. Hyphenated is preferred since v1 does it. 

`ion-tool-bar` feels fine to me, but it's just a personal preference.

**Comment by adamdbradley** [comment]
```
ion-navbar
ion-searchbar
ion-tabbar
ion-toolbar
```

It is decided.

**Comment by mhartington** [comment]
:+1:  I agree

**Comment by adamdbradley** [comment]
Renamed nav-bar files to navbar: https://github.com/driftyco/ionic2/commit/c19fcd5bed6625e25636ebbab377408d9130033d

**Comment by adamdbradley** [comment]
Renamed tab-bar to tabbar: https://github.com/driftyco/ionic2/commit/3d4aad8eaa5d7fc67021e02241152b46e6151f0e
