### ISSUE TITLE
ionic plugin install for Ionic2

### ISSUE THREAD

**Issue by ajaybeniwal** [driftyco/ionic2#423]
I am trying to install the Camera plugin using ionic plugin install cordova-plugin-camera but nothing happens the command lists only the plugin which are currently available in the list

**Comment by ydeshayes** [comment]
Same problem for me, I add to run 'cordova plugin add cordova-plugin-camera' manually and then it worked fine.

**Comment by mlynch** [comment]
Did you try `ionic plugin add`? `install` isn't the right verb

**Comment by ydeshayes** [comment]
So the documentation is wrong ? http://ionicframework.com/docs/v2/platform/camera/

**Comment by mlynch** [comment]
Ah, yea good catch. @mhartington can you change those to add instead of install? per your commit: https://github.com/driftyco/ionic-site/commit/5ac781c0e7eee24c009d3e210390379ed1f8647e#diff-de4d7472915e179a5fc4671c6091f6fb

**Comment by mhartington** [comment]
Ahh derp, my mistake. Fixed via https://github.com/driftyco/ionic-site/commit/66d67ae3936c807a6439187979618c3fbf11867e
