### ISSUE TITLE
Material Design for iOS

### ISSUE THREAD

**Issue by philmerrell** [driftyco/ionic2#427]
FWIW, it would be great to see a Material Design implementation for iOS that includes things like swipe to go back...

Love me some Material Design. :heart_eyes_cat:

**Comment by adamdbradley** [comment]
You can config it so material design is used for both iOS and Android. Is this what you mean?

**Comment by philmerrell** [comment]
That's awesome... I'll take a look at that.

Since tabs get hidden on detail views, I wasn't sure how Material tabs would act on iOS with the swipe to go back gesture, but I'll give it a try.  The youtube app on iOS is kind of what I had in mind.  It stays pretty faithful to both Material Design and iOS.

The iOS style is beautiful as well, so either way I win.

Ionic2 is amazing already.
