### ISSUE TITLE
Use lodash-modularized

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic2#428]
https://www.npmjs.com/package/lodash.template -> https://github.com/driftyco/ionic2/blob/master/tooling/generate.js#L140 etc.

**Comment by jbavari** [comment]
There's a few other things we use from lodash:

capitalize, camelCase, merge, contains, find, first, isArray, isString, map, filter, and transform.

I suspect if we use just the individual modules, we'll end up having a larger set than the 2.5MB that lodash comes with.

I've installed all that are used, and the file size is as follows:

```
$ du -sh node_modules/lodash.*

2.1M	node_modules/lodash
112K	node_modules/lodash.camelcase
 32K	node_modules/lodash.capitalize
512K	node_modules/lodash.contains
216K	node_modules/lodash.filter
236K	node_modules/lodash.find
 16K	node_modules/lodash.first
 20K	node_modules/lodash.isarray
 16K	node_modules/lodash.isstring
224K	node_modules/lodash.map
288K	node_modules/lodash.merge
228K	node_modules/lodash.template
228K	node_modules/lodash.transform
```

The rough math is - with the individuals, its almost as much as just lodash. We would also nto get the other lodash functionality it provides, until we'd need to install the individual module.

Also, we'd have to refactor the following code:

Generate:

uses lodash.capitalize and lodash.camelCase:
https://github.com/driftyco/ionic2/blob/master/tooling/generate.js#L222

Scripts:

snapshot.tasks.js - uses lodash.merge:
https://github.com/driftyco/ionic2/blob/master/scripts/snapshot/snapshot.task.js#L14

dgeni-config.js - uses lodash.contains, lodash.find, and lodash.first:
https://github.com/driftyco/ionic2/blob/master/scripts/docs/dgeni-config.js#L54
https://github.com/driftyco/ionic2/blob/master/scripts/docs/dgeni-config.js#L64
https://github.com/driftyco/ionic2/blob/master/scripts/docs/dgeni-config.js#L78

createTypeDefinitionFile.js - uses lodash.map, lodash.transform, lodash.forEach, lodash.filter
https://github.com/driftyco/ionic2/blob/master/scripts/docs/typescript-definition-package/processors/createTypeDefinitionFile.js#L22
https://github.com/driftyco/ionic2/blob/master/scripts/docs/typescript-definition-package/processors/createTypeDefinitionFile.js#L35
https://github.com/driftyco/ionic2/blob/master/scripts/docs/typescript-definition-package/processors/createTypeDefinitionFile.js#L42
https://github.com/driftyco/ionic2/blob/master/scripts/docs/typescript-definition-package/processors/createTypeDefinitionFile.js#L51

readTypeScriptModules - uses lodash.isArray, lodash.isString
https://github.com/driftyco/ionic2/blob/master/scripts/docs/typescript-package/processors/readTypeScriptModules.js#L329

**Comment by tlancina** [comment]
I don't care if we use lodash for devDeps, just trying to save room on starters, which is a pretty easy 2Mb we can get rid of.
