### ISSUE TITLE
Add sidemenu generator

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic2#429]

**Comment by ajaybeniwal** [comment]
Any timelines when it will be ready

**Comment by tlancina** [comment]
We discussed this a lot, and because sidemenu is a root navigation component (it goes in your @App template) we are holding off from generating it right now.  

Instead we've added a v2 sidemenu starter, so you can do `ionic start MyApp sidemenu --v2` like v1.  This is the preferred approach for root level tabs navigation as well: `ionic start MyApp tabs --v2`.

As of right now, generated pages are only child navigation pages, since we had concerns about how to generate root level navigation pages without clobbering users' existing root template.

**Comment by ajaybeniwal** [comment]
Is this included in Latest Ionic CLI or how can I use it today

**Comment by tlancina** [comment]
`ionic start MyApp sidemenu --v2`
