### ISSUE TITLE
changing text color with attribute

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic2#430]
How can we change the color of a text element with only an attribute? We can change the background color of various elements easily, but not the text.

i.e. - how do we do this:

```html
<h1 secondary>
```

Should the user add a class?

**Comment by brandyscarney** [comment]
We could loop through all of the colors and add them as an attribute for all of the text components, like:

```
h1, h2, h3, h4, h5, p, span, etc {
   &[#{$color}] {
      color: $value
   }
}
```

then if they wanted to use the attribute on their own custom directive they can do so in their own Sass files the same way. See: https://github.com/driftyco/ionic2/blob/master/ionic/components/segment/modes/ios.scss#L89-L118

**Comment by brandyscarney** [comment]
Added text color styling for:

```
  h1, h2, h3, h4, h5, h6,
  p,
  span,
  a,
  small,
  sub,
  sup
```

Please reopen if you think of any I missed or if any don't work.
