### ISSUE TITLE
Question: Does anyone know what replaces simple search filters in Angular 2/Ionic 2?

### ISSUE THREAD

**Issue by robyedlin** [driftyco/ionic2#433]
It used to be super easy to filter results in a list using `ng-model="query"` on a text input and `ng-repeat="item in items | filter: query"` for the items.

The new demos show function calls and pipes. Do we have to actually write the functions for our search filters now? Is this the right way to do it for a simple search through static data?

**Comment by ajaybeniwal** [comment]
Yes you have to write a search function and filter the values using your own code  angular 2 has moved away from ng-repeat filters

**Comment by robyedlin** [comment]
Ok, does Ionic have any simple demos for this?

**Comment by ajaybeniwal** [comment]
Look at there conference app there is a a demo for search bar in that app you will catch it easily

**Comment by robyedlin** [comment]
Ok, thanks.

**Comment by brandyscarney** [comment]
There's an example of a custom pipe here: https://github.com/driftyco/ionic-conference-app/blob/master/www/app/pipes/convert-date.js
 
The function for the search bar is here: https://github.com/driftyco/ionic-conference-app/blob/master/www/app/schedule/schedule.js

And the function to filter by category is here: https://github.com/driftyco/ionic-conference-app/blob/master/www/app/components/schedule-list.js

I'm not sure if Angular is planning on implementing the filter pipe, but there is a good overview of pipes here: https://auth0.com/blog/2015/09/03/angular2-series-working-with-pipes/

And here: https://angular.io/docs/ts/latest/guide/pipes.html

Note that the DateForm pipe is not working on specific versions of Safari: https://github.com/driftyco/ionic-conference-app/issues/42

Sorry for the lack of line numbers, commenting from mobile.

**Comment by robyedlin** [comment]
Sweet, thanks!
