### ISSUE TITLE
Ions Icon missing in starter template?

### ISSUE THREAD

**Issue by jnosullivan** [driftyco/ionic2#434]
Hello, when running the template the icon would not show.

**Comment by ydeshayes** [comment]
Same problem here ! ionic 2.0.0-alpha.15 (alpha 9 was fine)

**Comment by ydeshayes** [comment]
For those who run into this issue, copy all files in https://github.com/driftyco/ionic2/tree/master/ionic/fonts to yourApp/www/build/fonts

**Comment by maxx0r** [comment]
Ran into the same problem, thanks for the quick solution +ydeshayes

**Comment by jnosullivan** [comment]
Worked thank you!

**Comment by tlancina** [comment]
Re-opening in case someone else has the same issue, tracking https://github.com/driftyco/ionic-app-lib/issues/41

**Comment by tlancina** [comment]
Should be fixed in latest `ionic@alpha`.
