### ISSUE TITLE
(Question) How to update Ionic2 to latest master?

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#438]
What is the proper way to update my project to latest master of Ionic2?

Is it like this?
  npm install -g ionic@alpha
  ionic lib update

Would be good to add on github main page for those who is not too familiar with npm world.

**Comment by astec** [comment]
Getting this error:
$ ionic lib update
Unable to load ionic lib version information
Are you sure you want to replace /Users/astec/DebtsTracker/www/lib/ionic with an updated version of Ionic?
(yes/no): y
Latest version: 1.1.0  (released 2015-08-13)
Downloading: https://github.com/driftyco/ionic-bower/archive/v1.1.0.zip
[=============================]  100%  0.0s
updateFiles Error: ReferenceError: cp is not defined

**Comment by tlancina** [comment]
Doing `npm install ionic-framework` will install the latest published version of ionic2.

**Comment by tlancina** [comment]
To use master, you'll need to download the repo and link it:

```
git clone git@github.com:driftyco/ionic2.git && cd ionic2
npm link
# then go into your project
cd MyIonicApp
npm link ionic-framework
```

**Comment by astec** [comment]
Thanks. Done cloning and linking ionic2:

$npm link
/usr/local/lib/node_modules/ionic-framework -> /Users/astec/ionic2

npm link ionic-framework
/Users/astec/MyIonicApp/node_modules/ionic-framework -> /usr/local/lib/node_modules/ionic-framework -> /Users/astec/ionic2

But started to get an error on "ion server". Please let me know if I should move this to StackOverflow. I just feel it can be useful for many people.

ionic serve
∆ Compiling your SASS to CSS.
 Error: file to import not found or unreadable: ionic
Current dir: /Users/astec/MyIonicApp/www/app/
    at Object.module.exports.renderSync (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/node-sass/lib/index.js:424:22)
    at Object.processSass (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/v2/transpile.js:203:25)
    at Object.serve (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/v2/serve.js:53:17)
    at /usr/local/lib/node_modules/ionic/lib/ionic/serve.js:87:15
    at _fulfilled (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:407:9)

Seems like trying to execute from old ionic? Before it worked fine.

**Comment by tlancina** [comment]
You might need to update your `webpack.config.js`:

```
  resolve: {
    modulesDirectories: [
      "node_modules",
      "node_modules/ionic-framework/dist/src/es5/common", // ionic-framework npm package (stable)
      "node_modules/ionic-framework/node_modules", // angular is a dependency of ionic
      "node_modules/ionic-framework/dist/js", // for web-animations polyfill
    ],
    extensions: ["", ".js", ".ts"]
  }
```

**Comment by tlancina** [comment]
Ah you'll also need to run 

```
npm install
gulp src
```

To build the source files in the ionic2 repo :)

**Comment by astec** [comment]
Should "npm install" go before "npm link" of after?

**Comment by tlancina** [comment]
After, once you're linked you should be good to go (you don't need to run link again).

**Comment by astec** [comment]
"npm install" and "gulp src" completed successfully.

Now am getting error that ionic executable not found (I've reinstalled node & npm in meantime to get rid of all old mess).

$ ionic
-bash: /usr/local/bin/ionic: No such file or directory

Any suggestions on how to fix that? Where is it located?

ionic2 astec$ ls
GUIDE.md	LICENSE		README.md	demos		dist		gulpfile.js	ionic		node_modules	package.json	scripts		tooling		tsconfig.json

**Comment by tlancina** [comment]
Sounds like you need to reinstall ionic as well: `npm install -g ionic@alpha`

**Comment by astec** [comment]
That helped. But now it's not starting because of babel. Running "npm install --save-dev babel", "npm install babel" and "npm install babel-cli" successfully completes but did not help.

ionic serve
∆ Compiling your SASS to CSS.
√ Sass compiled to CSS.
∆ Running postcss and autoprefixer on compiled CSS.
∆ Compiling and bundling with Webpack...

√ Using your webpack.config.js file: /Users/astec/MyIonicApp/webpack.config.js 
√ CSS processed to: /www/build/css/app.css 
 ✗ 

Babel compiler cannot be found, please add it to your package.json file:
    npm install --save-dev babel

Alex-MacBook:MyIonicApp astec$ sudo npm install --save-dev babel
npm WARN package.json @ No repository field.
npm WARN package.json @ No license field.
babel@6.0.15 node_modules/babel
Alex-MacBook:MyIonicApp astec$ ionic serve
∆ Compiling your SASS to CSS.
√ Sass compiled to CSS.
∆ Running postcss and autoprefixer on compiled CSS.
∆ Compiling and bundling with Webpack...

√ Using your webpack.config.js file: /Users/astec/MyIonicApp/webpack.config.js 
√ CSS processed to: /www/build/css/app.css 
 ✗ 

Babel compiler cannot be found, please add it to your package.json file:
    npm install --save-dev babel

**Comment by tlancina** [comment]
Ok we're too deep to give up now! Next time, don't install with sudo.  But you don't need Babel, change this line in your webpack.config.js:
`loader: "awesome-typescript-loader?doTypeCheck=false&useBabel=true&useWebpackText=true"`
to
`loader: "awesome-typescript-loader?doTypeCheck=false&useWebpackText=true"`

**Comment by astec** [comment]
Did not know it would be that hard...

$ ionic serve
∆ Compiling your SASS to CSS.
√ Sass compiled to CSS.
∆ Running postcss and autoprefixer on compiled CSS.
∆ Compiling and bundling with Webpack...

√ Using your webpack.config.js file: /Users/astec/MyIonicApp/webpack.config.js 
√ CSS processed to: /www/build/css/app.css 
There were some errors with webpack
multi main
Module not found: Error: Cannot resolve module 'web-animations.min' in /Users/astec/MyIonicApp
resolve module web-animations.min in /Users/astec/MyIonicApp
  looking for modules in /Users/astec/MyIonicApp/node_modules
    /Users/astec/MyIonicApp/node_modules/web-animations.min doesn't exist (module as directory)
    resolve 'file' web-animations.min in /Users/astec/MyIonicApp/node_modules
      resolve file
        /Users/astec/MyIonicApp/node_modules/web-animations.min doesn't exist
        /Users/astec/MyIonicApp/node_modules/web-animations.min.js doesn't exist
        /Users/astec/MyIonicApp/node_modules/web-animations.min.ts doesn't exist
  looking for modules in /Users/astec/MyIonicApp/node_modules/ionic-framework/node_modules
    /Users/astec/MyIonicApp/node_modules/ionic-framework/node_modules/web-animations.min doesn't exist (module as directory)
    resolve 'file' web-animations.min in /Users/astec/MyIonicApp/node_modules/ionic-framework/node_modules
      resolve file
        /Users/astec/MyIonicApp/node_modules/ionic-framework/node_modules/web-animations.min doesn't exist
        /Users/astec/MyIonicApp/node_modules/ionic-framework/node_modules/web-animations.min.js doesn't exist
        /Users/astec/MyIonicApp/node_modules/ionic-framework/node_modules/web-animations.min.ts doesn't exist
  looking for modules in /Users/astec/node_modules
    /Users/astec/node_modules/web-animations.min doesn't exist (module as directory)
    resolve 'file' web-animations.min in /Users/astec/node_modules
      resolve file
        /Users/astec/node_modules/web-animations.min doesn't exist
        /Users/astec/node_modules/web-animations.min.js doesn't exist
        /Users/astec/node_modules/web-animations.min.ts doesn't exist
[/Users/astec/MyIonicApp/node_modules/web-animations.min]
[/Users/astec/MyIonicApp/node_modules/web-animations.min]
[/Users/astec/MyIonicApp/node_modules/web-animations.min.js]
[/Users/astec/MyIonicApp/node_modules/web-animations.min.ts]
[/Users/astec/MyIonicApp/node_modules/ionic-framework/node_modules/web-animations.min]
[/Users/astec/MyIonicApp/node_modules/ionic-framework/node_modules/web-animations.min]
[/Users/astec/MyIonicApp/node_modules/ionic-framework/node_modules/web-animations.min.js]
[/Users/astec/MyIonicApp/node_modules/ionic-framework/node_modules/web-animations.min.ts]
[/Users/astec/node_modules/web-animations.min]
[/Users/astec/node_modules/web-animations.min]
[/Users/astec/node_modules/web-animations.min.js]
[/Users/astec/node_modules/web-animations.min.ts]
 @ multi main,./www/app/app.js
Module build failed: Cannot resolve module 'ionic/ionic' in /Users/astec/MyIonicApp/www/app
    Required in /Users/astec/MyIonicApp/www/app/app.js
 @ multi main

Here is a conent of ionic-framework/node_modules:

$ cd node_modules/ionic-framework/node_modules/
$ ls
@reactivex		dgeni			gulp-babel		gulp-sass		inquirer		lazypipe		reflect-metadata	systemjs
angular2		dgeni-packages		gulp-cached		gulp-shell		jasmine-core		lodash			request			through2
canonical-path		es6-shim		gulp-concat		gulp-typescript		jasmine-node		lunr			run-sequence		typescript
colors			event-stream		gulp-connect		gulp-util		js-yaml			minimist		semver			vinyl
connect			glob			gulp-if			gulp-watch		karma			node-html-encoder	serve-static		webpack
cpr			gulp			gulp-insert		html-entities		karma-chrome-launcher	node-libs-browser	shelljs			yargs
del			gulp-autoprefixer	gulp-rename		htmlparser2		karma-jasmine		q			source-map-support	zone.js

**Comment by tlancina** [comment]
Does your webpack.config.js file have this?
```
  resolve: {
    modulesDirectories: [
      "node_modules",
      "node_modules/ionic-framework/dist/src/es5/common", // ionic-framework npm package (stable)
      "node_modules/ionic-framework/node_modules", // angular is a dependency of ionic
      "node_modules/ionic-framework/dist/js", // for web-animations polyfill
    ],
    extensions: ["", ".js", ".ts"]
  }
```

**Comment by astec** [comment]
It was:
  resolve: {
    modulesDirectories: [
      "node_modules",
      "node_modules/ionic-framework/src/es5/common", // ionic-framework npm package (stable)
      "node_modules/ionic-framework/node_modules", // angular is a dependency of ionic
      "node_modules/ionic-framework/js", // for web-animations polyfill

      // "node_modules/ionic2/dist/src/es5/common", // driftyco/ionic2 repo (master)
      // "dist/src/es5/common",
      // "node_modules/ionic2/node_modules",
      // "node_modules/ionic2/dist/js"
    ],
    extensions: ["", ".js", ".ts"]
  }

Replaced with yours and got huge list of errors like this:
There were some errors with webpack
../ionic2/dist/src/es5/common/ionic/components.js
Module not found: Error: Cannot resolve module 'ionic/components/app/app' in /Users/astec/ionic2/dist/src/es5/common/ionic
resolve module ionic/components/app/app in /Users/astec/ionic2/dist/src/es5/common/ionic
  looking for modules in /Users/astec/node_modules
    /Users/astec/node_modules/ionic doesn't exist (module as directory)
  looking for modules in /Users/astec/ionic2/node_modules
    /Users/astec/ionic2/node_modules/ionic doesn't exist (module as directory)
[/Users/astec/node_modules/ionic]
[/Users/astec/ionic2/node_modules/ionic]
 @ ../ionic2/dist/src/es5/common/ionic/components.js 11:29-64,../ionic2/dist/src/es5/common/ionic/components.js

I'm giving up to update the current project. Created a new project and it worked. will copy "www" there.

$ ionic start MyIonicV2App --v2

**Comment by tlancina** [comment]
Glad you got it working.  The main problem I think was having a project started with an older version of the CLI, which shouldn't be an issue going forward.

**Comment by astec** [comment]
Thanks a lot for your help. I can say I'm pretty impressed with Ionic2, Angular2 & TypeScript.

Hope you guys get to beta soon - I would be eager to publish my app in January 2016.

By the way does Ionic Push, Ionic Analytics & Ionic Deploy are working with Ionic2 or is it to be supported?

**Comment by ajaybeniwal** [comment]
I updated the Ionic cli and cloned the master repository but still cant get the newly generated app with master branch

**Comment by tlancina** [comment]
Hey guys, I've just updated the ionic2-app-base repo with instructions on developing against master locally: https://github.com/driftyco/ionic2-app-base/blob/master/README.md#notes

Running `ionic start MyApp --v2` should now include these instructions in the README, along with the necessary line in `webpack.config.js`: https://github.com/driftyco/ionic2-app-base/blob/master/webpack.config.js#L47

We are working on making this MUCH easier.  Thanks for sticking with it!

**Comment by astec** [comment]
Thanks. How often do you upgrade to the latest Angular2?

**Comment by boboldehampsink** [comment]
Should'nt [this line in gulpfile.js](https://github.com/driftyco/ionic2-app-base/blob/master/gulpfile.js#L18) also be updated to /dist?

**Comment by tlancina** [comment]
@boboldehampsink yes if you're using gulp! We're moving away from gulp however, and the build process is still undergoing some changes right now as we try and make it as dead simple as possible.  What that means is that some configurations from previous versions of starters or `ionic start` from previous versions of the alpha CLI will be stale as we change things.  Thanks for hanging in there with us :)

**Comment by boboldehampsink** [comment]
Mmm, I loved gulp because it was more configurable (we used css globbers etc.) - can't get it to work with webpack because the actual sass compiling is done in transpile.js by node-sass instead of webpack...

**Comment by tlancina** [comment]
I've locked this because it will most likely just confuse people, please refer to the app-base instructions on developing against master: https://github.com/driftyco/ionic2-app-base/blob/master/README.md#notes.
