### ISSUE TITLE
refactor ion-item-sliding component

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#439]
I'm working on ion-item-sliding, and noticing some areas that could make it easier on CSS, and click event bubbling.

```
<ion-item-sliding>
  <ion-item (click)="clickOnItem()">
    My Item
  </ion-item>
  <ion-item-options>
    <button (click)="button1()">Speaker<br>Info</button>
    <button (click)="button2()">Add to<br>Favorites</button>
  </ion-item-options>
</ion-item-sliding>
```

For CSS, what if the outer `ion-item-sliding` element really didn't provide much at all, and it would not get the `.item` CSS class. However, the inner item `<ion-item>` would already come as the same ion-item component we all know and love, to include adding `.item` for its styling. Less CSS to manage which essentially does the same thing already.

Second, when the user puts `(click)` on the outer `ion-item-sliding` this causes issues of when, and when not to cancel a click (especially with the tap polyfill). So instead of wrapping option buttons in two clicks events (one on the button itself, and one on the outer ion-item-sliding), why not only put the click on the inner ion-item, and the inner buttons. This way we don't even have to mess with clicks messing with each other. I also think it'd make more sense documenting how item clicks work, where it's always on ion-item. Additionally, the ion-item could rightfully use `<button ion-item>` unlike now where you can't have button elements inside of button elements. This also makes it easier on the activator code because it'll already know how to activate ion-item, and it wouldn't activate ion-item-sliding which is currently buggy.

Pretty sure i talked myself into it. Any reason not to do this? @mlynch @brandyscarney

**Comment by mlynch** [comment]
Sounds great to me. Only question would be: does the user put (click) on their option buttons or is it one even on the whole item? The former seems a lot more intuitive

**Comment by adamdbradley** [comment]
Well both would work, which is good. How I have the first comment written is how I'd see it being the most intuitive, by putting the click on the part that doesn't wrap everything. But again, both ways would work.

**Comment by adamdbradley** [comment]
Going forward with this

**Comment by brandyscarney** [comment]
Sorry, I didn't see my tag on this. I like it!
