### ISSUE TITLE
Example of Infinite scroll and Pull To refresh

### ISSUE THREAD

**Issue by ajaybeniwal** [driftyco/ionic2#440]
Any Examples of Infinite scroll and pull to refresh in list view is it already implemented ?

**Comment by adamdbradley** [comment]
Yes, just haven't documented it yet. We'll work to get that up, thanks

**Comment by ajaybeniwal** [comment]
Hi ,

Any updates as when the docs will be updated or could you provide any link to working example

Regards,
Ajay Singh

**Comment by drewrygh** [comment]
Hey @ajaybeniwal - we will have working demos and documentation for these components soon.

In the meantime, you could refer to our end-to-end test examples:
- [scroll/pull-to-refresh e2e](https://github.com/driftyco/ionic2/tree/master/ionic/components/scroll/test/pull-to-refresh)
- [list/infinite e2e](https://github.com/driftyco/ionic2/tree/master/ionic/components/list/test/infinite)

**Comment by qiongshusheng** [comment]
’list/infinite e2e‘ is not work，import {ProtoViewRef, ViewContainerRef} from 'angular2/core'， ProtoViewRef is not found from 'angular2/core'

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5072
