### ISSUE TITLE
How to add third party angular 2 plugins to Ionic2 app?

### ISSUE THREAD

**Issue by softBarbarian** [driftyco/ionic2#442]
Tried to get some responses on Ionic's forum but was unsuccessful, so posting here.

How to add third party angular 2 plugins to Ionic2 app?

Thanks @mhartington for your great work!

**Comment by softBarbarian** [comment]
@adamdbradley could you please find a minute to answer the question above? Our company is dependent on this in determining when to start adopting Ionic2. thanks

**Comment by tlancina** [comment]
Do you have any specific examples? I'm unsure of what plugins refer to for angular2. I don't see any reason they would not be supported as long as they are modules.

**Comment by softBarbarian** [comment]
@tlancina I am looking for an advice how to install modules to ionic2 app in general. I looked up moment2-angular for example and it looks like all i need to do is run `npm install <module name>` and than import it in needed file.
I am just starting to learn angular2/ionic2 and was wondering if there is a ionic2 specific way of doing this.

**Comment by softBarbarian** [comment]
Another question, what is the best approach to add a cordova plugin like [TouchId](https://github.com/Telerik-Verified-Plugins/TouchID) since ng-cordova is not relevant anymore?

**Comment by tlancina** [comment]
Yep, 3rd party libraries work just fine with Ionic, for the most part simply doing `npm install` and then `import` just as you said. Nothing Ionic specific yet :)

Not sure what our current recommendation is on plugins not wrapped in the framework, cc @mlynch.

**Comment by mlynch** [comment]
Like tim says, works fine and all the code in the world is available to you just like any other JS app

**Comment by softBarbarian** [comment]
Thanks a lot! Keep up the awesome work
