### ISSUE TITLE
two pages simultaneously visible

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic2#444]
Using setRoot to change pages in the preview app:

<img width="405" alt="screen shot 2015-11-05 at 2 15 01 pm" src="https://cloud.githubusercontent.com/assets/2018508/10980431/8d6a98f6-83c7-11e5-94b0-8cca2441ae57.png">

The pages occasionally get stuck. Calling setRoot again fixes the problem.

**Comment by adamdbradley** [comment]
How do I recreate this?

**Comment by drewrygh** [comment]
Not sure how to recreate this atm -- it was seen when scrolling through the [docs](http://ionicframework.com/docs/v2/components/#cards). It seems to only affect iOS.

**Comment by drewrygh** [comment]
Same problem -- but in the form section on iOS:

<img width="401" alt="screen shot 2015-11-09 at 11 00 39 am" src="https://cloud.githubusercontent.com/assets/2018508/11040265/0362101e-86d1-11e5-8fa8-e04fabd622be.png">

**Comment by adamdbradley** [comment]
is this still an issue? I haven't seen it do this yet

**Comment by drewrygh** [comment]
yeah, just saw it recently. It happens pretty rarely though, and there doesn't seem to be any consistency in how to reproduce it

**Comment by adamdbradley** [comment]
how large of a debounce is set on changing the pages?

**Comment by adamdbradley** [comment]
Can't reproduce, but will also put a debounce on the the docs demo.
