### ISSUE TITLE
docs: standardize tab root variable

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#447]
Instead of:

```
    this.tabOne = TabIconCtrl;
    this.tabTwo = TabIconCtrl;
    this.tabThree = TabIconCtrl;
    this.tabFour = TabIconCtrl;
```

use a number at the end, not a word, like `this.tab1`

**Comment by mlynch** [comment]
Also let's not use "Ctrl" in the name of any component or class. That's a relic of ng1 we want to move away from
