### ISSUE TITLE
docs: spice up dat modal

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#449]
Can we do more with the modal that slides up?

**Comment by brandyscarney** [comment]
Just an idea, but you could do a filter type modal similar to the conference app: https://github.com/driftyco/ionic-conference-app/tree/master/www/app/modals

![slack for ios upload-1 png](https://cloud.githubusercontent.com/assets/6577830/10981686/338a09d8-83d7-11e5-8501-f572cb99246c.jpeg)
