### ISSUE TITLE
How to use ngCordova?

### ISSUE THREAD

**Issue by felangga** [driftyco/ionic2#457]
Is it possible to use ngCordova in ionic 2?

**Comment by estephan** [comment]
I believe that Ionic 2 already provides some interfaces for core cordova plugins, so not sure we should be using ngCordova with it.
A more detailed answer can be found [here](http://forum.ionicframework.com/t/ionic-2-with-ng-cordova/36103/4).

**Comment by mhartington** [comment]
So you shouldn't need to use ng-cordova anymore. All the core plugins have been moved into the framework. 

http://ionicframework.com/docs/v2/platform/applinks/
