### ISSUE TITLE
IOS fab button icon position

### ISSUE THREAD

**Issue by ydeshayes** [driftyco/ionic2#461]
Hello,

In iOS I have an issue with the fab icon position: 

![capture d ecran 2015-11-06 a 11 51 44](https://cloud.githubusercontent.com/assets/3427645/10995413/eb736c60-847c-11e5-88c0-973aac50a3d7.png)

![capture d ecran 2015-11-06 a 11 51 49](https://cloud.githubusercontent.com/assets/3427645/10995414/ef40e412-847c-11e5-963c-f4444063b7dd.png)

Can you tell me if it's an issue or I got to do something for the iOS platform ?

I use 2.0.0-alpha.31 version,
Thanks !

**Comment by roonie** [comment]
I'm having the same issue. Seems that the icon has a min-width of 64px, where the button is 56px. 
temp fix
```
button[fab] icon, [button][fab] icon {
  min-width: 56px;
}
```

**Comment by brandyscarney** [comment]
Thanks for letting us know! It should be fixed in the next release. :)
