### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by ydeshayes** [driftyco/ionic2#462]
Hello,

when i tap the android (hardware or not) back button, the app closed. I see in the code that a function is predicted but not implemented (https://github.com/driftyco/ionic2/blob/076dc7645edfd2d216a8f0f7bf52abca6b6be35e/ionic/platform/platform.ts line 161). 

Did you think about integrate this back button with the navigation behavior ? (touching the android back button call navigation.pop() for example) or do we have to implement it ourselves ?

thanks !

**Comment by adamdbradley** [comment]
Yes Ionic be able to handle this like it did in v1, just haven't completed it yet.

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5071
