### ISSUE TITLE
forms: <form ng-submit="..."> handler is not triggered

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#463]
Handler is not triggered on `button[type=submit]` click or "Enter" key press inside a text input.

```
<form (ng-submit)="console.log('onSubmit')">
  <input type="text">
  <button type="submit"></button>
</form>
``` 

It worked before and stopped after updating to latest master.

**Comment by Tiagojdferreira** [comment]
isn't the correct syntax (^submit) ?
http://learnangular2.com/forms/

**Comment by astec** [comment]
I tried the (^submit) but it did not help. Would be good to have an working example. (in docs?)

**Comment by agnellvj** [comment]
I am seeing the same issue with the submit.

**Comment by mhartington** [comment]
I've just updated the forms example on learn-angular 2

http://learnangular2.com/forms/

Form submission uses the standard way of form handling.

```
<form [ng-form-model]="loginForm" (submit)="doLogin($event)">
    <input ng-control="email" type="email" placeholder="Your email">
    <input ng-control="password" type="password" placeholder="Your password">
  <button type="submit">Log in</button>
</form>
```

**Comment by agnellvj** [comment]
thanks, looks like I had to update ionic from alpha.31 to alpha.33 and that fixed my issues with the form submit.
