### ISSUE TITLE
feature: ion-sliding-item: Do not slide ion-item or part of it

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#464]
Is there possibility to have a parameter do not slide the ion-item and just roll over the options buttons?Or is it against design guidelines?

Just sometimes I have situation when there is a short text on left and not wide option button(s) - when swiping the row become white-empty - looks a bit weird.
The item looks like
```
[ User                          $12]
```
and after swipe:
```
[                  $12 [btn1][btn2]]
```

**Comment by adamdbradley** [comment]
Down the road I think this would be a good option to add, or at least make it easier to config this yourself. At the alpha stage though I'd like to focus on just getting the core sliding items 100%. Thanks
