### ISSUE TITLE
docs: links are broken

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#465]
See: http://ionicframework.com/docs/v2/getting-started/installation/

All of them are broken.

On that note, where we say run `ionic serve` we should tell them to switch into the directory first:

```
$ cd cutePuppyPics
$ ionic serve
```

**Comment by felipereis** [comment]
Platform -> Device Orientation -> Cannot GET /docs/v2/platform/device-orientation/
Components -> Popups -> API docs -> Cannot GET /docs/v2/api/popup/ionPopup

**Comment by drewrygh** [comment]
Fixed. Thanks for pointing out these additional links @felipereis
