### ISSUE TITLE
Screen trembling when scroll down and swipe ion-sliding item

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#468]
iOS: If you start to scroll down (*being at top of a page*) by pressing on <ion-sliding-item> and you finger swipes a bit left and you keep holding the finger pressed content starts annoyingly trembling with every little movement of a finger - content jumps to top (*as not scrolled*) and back to scrolled position.

If you 1st start to swipe then scrolling is disabled and there is no trembling what is good.

Expected: Either get rid of trembling on simultaneous scroll+swipe or disable swipe while scrolling.

**Comment by mlynch** [comment]
Thanks, @adamdbradley has some new list item swiping code landing soon so that should solve this.

**Comment by adamdbradley** [comment]
@astec can you check if this has been fixed in alpha32?

**Comment by astec** [comment]
Updated to alpha23 - now it works nicely!

**Comment by astec** [comment]
So it works better but still somewhat noticeable. A bit annoying. May be linked to https://github.com/angular/angular/issues/5077
