### ISSUE TITLE
iOS toolbar in modal: text isn't vertically aligned

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic2#469]
<img width="318" alt="screen shot 2015-11-06 at 4 15 24 pm" src="https://cloud.githubusercontent.com/assets/2018508/11009976/22376cdc-84a1-11e5-9e03-c1ec9b0e6a71.png">

Android looks fine.

**Comment by drewrygh** [comment]
```html
<ion-toolbar>
  <ion-title>Modals</ion-title>
</ion-toolbar>

<ion-content padding>
    <button block danger (click)="closeModal()">
      <icon close></icon>
      Close Modal
    </button>
</ion-content>
```

**Comment by brandyscarney** [comment]
I believe this is because `ion-navbar` is being targeted instead of `.toolbar` here, so that *should* fix it:

https://github.com/driftyco/ionic2/blob/master/ionic/platform/cordova.scss#L11

**Comment by brandyscarney** [comment]
@drewrygh Can you check this for me whenever you get a chance and close if fixed. I tested navbars, multiple toolbars in menus, and multiple toolbars in modals and only the first one should get the padding top. Just want some extra confirmation. :)
