### ISSUE TITLE
[start] - provide starter template listing for v2

### ISSUE THREAD

**Issue by jbavari** [driftyco/ionic2#471]
In the CLI, we have a command to view the starter templates available:

`ionic templates`

```
Downloading Starter Templates - http://code.ionicframework.com/content/starter-templates.json
Ionic Starter templates


blank ................ A blank starter project for Ionic
complex-list ......... A complex list starter template
maps ................. An Ionic starter project using Google Maps and a side menu
salesforce ........... A starter project for Ionic and Salesforce
sidemenu ............. A starting project for Ionic using a side menu with navigation in the content area
tabs ................. A starting project for Ionic using a simple tabbed interface
tests ................ A test of different kinds of page navigation
```

For v2, only tabs, sidemenu, and blank are implemented.

@adamdbradley @mlynch @tlancina We need to decide - do we implement all v1 starters?

Or how we want to show v2 templates? (`ionic templates --v2`)

**Comment by championswimmer** [comment]
Might be related https://github.com/driftyco/ionic2/issues/470 

templates should have versioning info, and be cached and not redownloaded on each app creation.

**Comment by adamdbradley** [comment]
For right now, let's just implement blank, and the conference app. We can re-evaluate which ones to build out later.

**Comment by jbavari** [comment]
Currently we have tabs, sidemenu, and blank.

Are you suggesting we add conference app as a starter as well?

**Comment by adamdbradley** [comment]
Yes, please add the conference app. But do not add complex-list, maps, salesforce, or tests. And actually, tests should be completely removed from v1's list too, that was never meant to be a starter.

**Comment by jbavari** [comment]
On it now. Thanks.
