### ISSUE TITLE
platform and build commands should work without argument

### ISSUE THREAD

**Issue by championswimmer** [driftyco/ionic2#472]
`ionic build` and `ionic platform` should work as wrappers for `cordova build` and `cordova platform`. 

As of now they MUST take a string argument, without which it fails. 

What I expect - 
* `ionic build` builds for all platforms
* `ionic platform` shows installed and available platforms in cordova

**Comment by jbavari** [comment]
@championswimmer I've got this fixed in v2. We will publish it later in the week. 

Thanks for reporting.

**Comment by jbavari** [comment]
This should be done in alpha.23. Thanks for reporting.
