### ISSUE TITLE
Run gulp build before_prepare

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic2#473]
We should run gulp build using cordova hooks. Alternatively we could use the cli to run the build process, but using a hook is pretty simple.

```
#!/usr/bin/env node
var gulp = require('gulp');
require('../../gulpfile.js');
gulp.start('build');
```

Added PR https://github.com/driftyco/ionic2-app-base/pull/1 to address this.

Will test this on windows later today.

**Comment by mhartington** [comment]
Updated for possible path issues on windows.

```
#!/usr/bin/env node
var gulp = require('gulp');
var path = require('path');
var rootdir = process.argv[2];
require(path.join(rootdir, 'gulpfile.js'));
gulp.start('build');
```

**Comment by adamdbradley** [comment]
As much as possible, I'd rather not have cordova involved in the build steps. Thinking of those only building for the web, or building for electron, we shouldn't tie our build step too much to one tech.

**Comment by mhartington** [comment]
Hmm, makes sense then. Maybe we could just call `ionic transpile` from run/build then?

**Comment by jbavari** [comment]
Yes, we can easily wire that step in there, as I think it was wired in before.

**Comment by tlancina** [comment]
Files get built as part of `ionic build`, this can also easily be done with hooks in `ionic.config.js` if the user wants.
