### ISSUE TITLE
sub-header/toolbar? 

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic2#474]
With MD, your toolbar and sub-toolbars get a small shadow, similar to cards. Could be a nice addition? 

I got it working locally with 

```
$toolbar-box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14) !default;
.md {
  ion-navbar {
    box-shadow: $toolbar-box-shadow;
  }
  ion-toolbar[sub-header] .toolbar-background {
    box-shadow: inset $toolbar-box-shadow;
  }
}
```

![screenshot_20151107-165700](https://cloud.githubusercontent.com/assets/2835826/11017561/1a1d194a-8571-11e5-9192-4156d67bebda.png)
![screenshot_20151107-165706](https://cloud.githubusercontent.com/assets/2835826/11017562/1a24cba4-8571-11e5-88bc-914f8e17ce06.png)

**Comment by adamdbradley** [comment]
Are you just talking about the box-shadow at the bottom? I'm holding off on adding that at the moment because it causes scroll performance issues. We'll probably end up using a png datauri, but needs more testing.
