### ISSUE TITLE
Item-Sliding should reset state when destroyed

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic2#478]
If you delete a sliding item, the next touch event on any item in the same list will try and `closeOpenItem()`, which calls https://github.com/driftyco/ionic2/blob/master/ionic/components/item/item-sliding.ts#L105 and https://github.com/driftyco/ionic2/blob/master/ionic/components/item/item-sliding.ts#L141 and fails because `this.itemSlidingContent` has been removed.

You can see this in the tabs starter currently: delete a friend item and then click any of the other items in the list.

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5067
