### ISSUE TITLE
Script tag added after ion-list

### ISSUE THREAD

**Issue by robyedlin** [driftyco/ionic2#481]
Pretty small issues, but a script tag is added after ion-list, which makes nth-child css targeting more cumbersome for ion-items.

![screen shot 2015-11-10 at 2 02 11 pm](https://cloud.githubusercontent.com/assets/10917203/11074131/a4cb83d0-87b3-11e5-92dc-b74c4c879771.png)

**Comment by brandyscarney** [comment]
Hey, thanks for mentioning this. This is being tracked on Angular's repo: https://github.com/angular/angular/issues/4805

Hopefully it will be fixed soon. :) In the meantime I am using the script to target the first item like this:

```
.list script + .item {

}
```

**Comment by robyedlin** [comment]
Ok, cool.
