### ISSUE TITLE
What is alternative of location change start and state change start to check for authentication.

### ISSUE THREAD

**Issue by ajaybeniwal** [driftyco/ionic2#482]
In Ionic1 we used location change start or stage change start to check token and redirect to login screen if there is no token available , so how we will achieve the same thing in Ionic 2.

**Comment by Luchillo** [comment]
Well, i for example have a config service with a `checkAccessToken()` method that i call in each constructor of each page, but that's a lot of boilerplate for checking if user is logged in on each page.

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5066
