### ISSUE TITLE
Screen re-render or tremble when navigating to another page

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#485]
On iPhone 6s when I click button/item and navigate to another page `this.nav.push(OtherPage)` it looks like current page is refreshed or just jumps a little down & back and then animation starts.

There is no such effect when I click the "Back" button. Also not noticeable on desktop browser.

It takes just may be 1/10s of a second but very annoying.

**Comment by astec** [comment]
App ID to see the effect: 7e549a1b => Tab: Chats, click contact.

**Comment by adamdbradley** [comment]
duplicate of https://github.com/driftyco/ionic2/issues/406
