### ISSUE TITLE
Is the proxy working?

### ISSUE THREAD

**Issue by Miyada2000** [driftyco/ionic2#486]
Hey guys, trying to port an app to v2. Is the CLI proxy working? I´m using the same configs I had in my working V1 but getting the CORS error when calling from browser.

Module.exports = {
  "name": "IonicPPM",
  "proxies":  [
    {
      "path": "/ppm/rest/v1/projects",
      "proxyUrl": "http://cappm143-ps01/ppm/rest/v1"
    }
  ],
  ....
  
class
 return  this.http.get('/ppm/rest/v1/projects', {headers:headers});

**Comment by jbavari** [comment]
Looking into this now.

**Comment by jbavari** [comment]
This has been fixed. This issue will close when the team releases the CLI.

**Comment by Miyada2000** [comment]
Great!
