### ISSUE TITLE
bug: Have to click twice on <textarea> to get focus & keyboard

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#487]
On second page I have a simple form. If I click on text input I get keyboard and a flashing cursor immediately. For textarea I need to click twice. On 1st click to textarea keyboard starts to scroll up and then hides. On 2nd it shows just fine. This is in iOS in Ionic View app.

```html
<ion-card>
 <ion-card-content>
  <form [(ng-model)]="...">
   <ion-list>
    <ion-input fixed-label>
     <ion-label>Username</ion-label>
     <input type="text" value="">
    </ion-input>
    <ion-input fixed-label>
     <ion-label>Note</ion-label>
     <textarea></textarea>
    </ion-input>
   </ion-list>
  </form>
 </ion-card-content>
</ion-card>
```

**Comment by adamdbradley** [comment]
fixed in master
