### ISSUE TITLE
bug-iOS: Navbar is scrolling up with rest of page hiding under status bar on keybord rollup

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#488]
When I have a page with navbar and long enough form (taking more then half screen) when I click an input an iOS keyboard is rolling up and it is scrolling content of the page with navbar as well.

Actually it's not fully hidden, just a top pudding disappear. But get back to normal if you scroll page down.

**Comment by adamdbradley** [comment]
On what device? Can you provide some markup so I can try to replicate this?

**Comment by astec** [comment]
It's on iOS 9.01 iPhone 6s.

I have a feeling it can be linked with doble-click issue #487  - when I click 1st time the keyboards trying to show up and slide content up correctly - navbar in place but keyboard fails to show up and text box is not getting control. When I click 2nd time the keyboard shows fine & control get focus but the navbar is scrolled under the status bar - title & nav buttons are under the status text.

I'l l'll try to make a small sample and will update the issue.

**Comment by adamdbradley** [comment]
This has been fixed in master
