### ISSUE TITLE
docs: navbar color not is not being set

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic2#489]
<img width="391" alt="screen shot 2015-11-12 at 12 19 42 pm" src="https://cloud.githubusercontent.com/assets/2018508/11126967/374d0646-8937-11e5-9370-a3be32260212.png">

**Comment by adamdbradley** [comment]
do you have a code example?

**Comment by drewrygh** [comment]
```html
<ion-navbar *navbar hide-back-button>
  <ion-title>
    Search
  </ion-title>
</ion-navbar>

<ion-content>
...```

**Comment by drewrygh** [comment]
This is probably specific to some of the custom styling for the docs -- snapshot looks fine.
