### ISSUE TITLE
Cannot use cordova plugins

### ISSUE THREAD

**Issue by seraphpl** [driftyco/ionic2#501]
I get this error while trying to use cordova-plugin-device:

```
Plugin for Device not installed. For native functionality, please install the correct plugin for your platform:
cordova: cordova-plugin-device
```

I try with other plugin such as `StatusBar`, it also shows similar error.

**Comment by mlynch** [comment]
Closing since we're moving to a new companion project, https://github.com/driftyco/ionic-native
