### ISSUE TITLE
Add meta tags to starters

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#503]
Cordova starts index.html files with these meta tags, we should too in all our starters.
```
<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *">
<meta name="format-detection" content="telephone=no">
<meta name="msapplication-tap-highlight" content="no">
```

**Comment by jbavari** [comment]
This is completed.

Tabs:
https://github.com/driftyco/ionic2-starter-tabs/commit/892b67b1be286026c6e711f96d95f57379728997

Sidemenu:
https://github.com/driftyco/ionic2-starter-sidemenu/commit/e2d975ddd8430d7c232e54c4cfa05c3650387fcf

Blank:
https://github.com/driftyco/ionic2-starter-blank/commit/6ce33501d1c3a1bdcba7895a5dfde5a7ea98c268
