### ISSUE TITLE
Using primary or secondary on a menu-toggle in a toolbar changes the color

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#504]
Since we're using `primary` and `secondary` to position the menu-toggle in the toolbar, should these attributes be applying the color change? What if the user doesn't want the icon to change color but wants the menu button on the right, or what if they do want both? 

This causes issues with #91 because by default for MD we want the icons to be a dark grey or white. 

![screen shot 2015-11-13 at 10 52 41 am](https://cloud.githubusercontent.com/assets/6577830/11150185/b821fdd6-89f4-11e5-87ae-ecf12c33aa94.png)

**Comment by adamdbradley** [comment]
I'm thinking ion-nav-items should just use `left` and `right` attributes, and ditch `primary` and `secondary`. Yes on Android the "left" on will still be on the right side of the screen, but it'd still be left of the right. 

Right?

Right.

**Comment by brandyscarney** [comment]
Right.

**Comment by astec** [comment]
May be it make sense to use start/left instead of left/right as in bootstrap? Good for RTL (right-to-left) UI support.

https://github.com/twbs/bootstrap/issues/17279#issuecomment-146416929

**Comment by brandyscarney** [comment]
@astec did you mean start/end?

**Comment by astec** [comment]
Yes, sorry. `start/end` instead of `left/right`.

**Comment by brandyscarney** [comment]
Hmm maybe. I think we should have `left` always align to the left, since some users will want a left menu on Android, and `right` would always align right, again for the menu. Then some other attributes for the icons that get put on the left and right for iOS but all on the right for Android.

**Comment by adamdbradley** [comment]
I do like the `start/end` idea, which is the same as how flexbox works (and named this for the same RTL reasons). But like @brandyscarney pointed out, there should also be an absolutely "left" (start LTR) and a left that goes in the platform specific area. So I think we need 4 attributes like this (but not these names): Far left, left, far right, right. Ideas?

**Comment by adamdbradley** [comment]
I also think we can remove the need for the wrapper `<ion-nav-items>` and just have each button get the attribute. @mlynch thoughts?

**Comment by mlynch** [comment]
start end: :+1:

**Comment by adamdbradley** [comment]
Thinking that maybe we should have the same attribute names as `ion-item`, with `item-left` and `item-right`.

We can also get rid of grouping by `<ion-nav-items>`, and let the ng-content selector place the buttons in the correct location. Here's some examples

```
<ion-navbar>
  <button item-left/>
  <ion-title/>
  <button item-right/>
</ion-navbar>

iOS:
-------------------------
 B        Title        B
-------------------------

MD:
-------------------------
 Title               B B
-------------------------
```

```
<ion-navbar>
  <button item-left/>
  <button item-left/>
  <ion-title/>
  <button item-right/>
</ion-navbar>

iOS:
-------------------------
 B B      Title        B
-------------------------

MD:
-------------------------
 Title             B B B
-------------------------
```

```
<ion-navbar>
  <a menu-toggle/>
  <button item-left/>
  <ion-title/>
  <button item-right/>
</ion-navbar>

iOS:
-------------------------
 M B      Title        B
-------------------------

MD:
-------------------------
 M  Title            B B
-------------------------
```

```
<ion-navbar>
  <ion-title/>
  <button item-right/>
  <a menu-toggle item-right/>
</ion-navbar>

iOS:
-------------------------
          Title      B M
-------------------------

MD:
-------------------------
 Title               B M
-------------------------
```

Thoughts?

So the question remains, if `item-left` and `item-right` still represent only the placement of buttons for the platform, how would someone place a button to always be on the left side no matter what, even if it was material design?

**Comment by astec** [comment]
> So the question remains, if item-left and item-right still represent only the placement of buttons for the platform, how would someone place a button to always be on the left side no matter what, even if it was material design?

`<button item-left force-left>` ?

**Comment by brandyscarney** [comment]
@adamdbradley I'm kind of opposed to using `item-left` and `item-right`, only because they aren't actually in an item, nor are they items themselves and I think this may be confusing. If we're dropping the `start`/`end` idea then yeah something like @astec said could work. Probably something more general though that works on both like `force-placement` (or whatever word).

**Comment by adamdbradley** [comment]
I see "item" as a thing that goes in the navbar, like a button, image, input, back arrow, menu icon, etc. But I see you're point that using the same words may be confusing, but also may help since that's how you line up objects in an item too.

Suggestions for better attribute names?

**Comment by astec** [comment]
@adamdbradley I like the `placement` term as @brandyscarney suggested.

What about:
* `<button placement-start>` - for placing left or right depend on RTL
* `<button placement-force-start>` - for placing left or right regardless if it is MD or not.
* `<button placement-force-left>` - for placing left ignoring RTL

If `start`/`end` not going to be used then:

* `<button placement-left>` - for placing depending on MD
* `<button placement-force-left>` - for placing left regardless if it is MD or not.

**Comment by adamdbradley** [comment]
```
<ion-navbar>
    <ion-buttons start/>
    <ion-title/>
    <ion-buttons end/>
</ion-navbar>
```

**Comment by brandyscarney** [comment]
:+1: and

```
<ion-navbar>
    <ion-buttons left/>
    <ion-buttons start/>
    <ion-title/>
    <ion-buttons end/>
    <ion-buttons right/>
</ion-navbar>
```

**Comment by adamdbradley** [comment]
![image](http://i.imgur.com/KUh9Pbw.gif)
