### ISSUE TITLE
Discuss CSS selectors

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#505]
Right now we are wrapping the CSS selectors for a specific mode in the mode's class, i.e. a material design button selector looks like this:

```
.md button {
  ...
}
```

because of this, if a user adds a class to the button and tries to override a property that is set in the above selector, it will ignore the property because the `md` class wrapping it makes it take priority.

Having the users use the `!important` flag isn't a solution, and as it stands right now they will have to wrap their selector in the mode in order to override it.

At the same time, if the user wants to add a class to `button[large]` for example, they will have to target the button to override it. i.e. the following markup:

```
<button large class="small"></button>
```

will require the user to write:

```
button.small {
  ...
}
```

in order to override the properties in `button[large]`. Basically everything becomes more specific.

@adamdbradley and I discussed only including the css for the mode, and not wrapping it in the mode class, but leaving the mode class on the body in case the user wants to use it. Also, maybe pulling out more specific properties like font size.

Related to #466

Open discussion. Go.

**Comment by ackerdev** [comment]
My 2¢:

I'd love to see ionic adopt a CSS methodology that emphasizes low specificity selectors. Currently, ionic 1 uses a lot of selectors like `.bar.bar-positive .title`, which makes overriding styles more difficult as you often will need to look up what selectors are being used on a given element before you can effectively write your own selector to override it. With a high-specificity selector like `.bar.bar-positive .title` in the ionic css, it becomes very messy to try to override properties of .title elements: changing the text color of all titles for all bar colors requires either a large list of selectors, or `!important`, which is of course no good.

There are some documented CSS methodologies out there like BEM that emphasize using flat selectors, and one example in the wild you're probably aware of is Bootstrap. With the example of our `button.small`, one might instead use the class `.button-small`, and use only that selector when writing the styles for the small buttons. This means that any uninitiated developer can easily write overriding rules just by using the selector `.button-small`, making it much simpler to override the cascading styles.

For the particular scenario of the "global" styles (eg. `.md`), you unfortunately still leave yourself with some potential specificity issues:

```
.button {
  display: inline-block;
  font-size: 18px;
}

.foo .button {
  border: 1px solid;
}

.md .button {
  font-weight: bold;
}
```

In this example, it is still difficult to override something like `border` for every style, as the foo-style button will override a generic `.button` selector. However, given the limited scope and given that you're most likely using a single style class and only concerned with it's effects, this is mostly forgivable. The most ideal solution would be to have a pattern like `button-md`, but obviously this makes it much more work to style your entire application in one style or another, so I can at least understand the use of a nested selector here.

With these practices, customizing the styles of ionic components as an end-user becomes much more accessible and straightforward.

**Comment by adamdbradley** [comment]
All great points and we agree. We'll start making the changes for simpler css. The progress can be tracked here: https://github.com/driftyco/ionic2/issues/689

Thanks for the feedback!
