### ISSUE TITLE
docs(menu): menu is being hidden

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic2#509]
<img width="374" alt="screen shot 2015-11-13 at 1 49 21 pm" src="https://cloud.githubusercontent.com/assets/2018508/11155707/d5c9eb60-8a0c-11e5-81ca-8742e90611e0.png">

**Comment by adamdbradley** [comment]
What's different between the test examples and the docs demo? http://localhost:8000/e2e/menu/reveal/
