### ISSUE TITLE
-webkit prefixes aren't being applied for iOS simulator 8.x

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#516]
This messes up all flex properties. You can see this on any of the starters and the conference app. To reproduce:

```
ionic start test tabs --v2
cd test
ionic serve
ionic run ios
```

![screen shot 2015-11-13 at 6 36 05 pm](https://cloud.githubusercontent.com/assets/6577830/11160280/bd5bca66-8a35-11e5-839b-7a288b9318d4.png)

**Comment by adamdbradley** [comment]
use the same autoprefixer config as the ionic2 repo

**Comment by jbavari** [comment]
Fixed in CLI alpha.23.

**Comment by brandyscarney** [comment]
For anyone with an existing app update your webpack.config.js to match this: https://raw.githubusercontent.com/driftyco/ionic2-app-base/master/webpack.config.js
