### ISSUE TITLE
reduce left margin from item-left within an item

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#517]
http://ionic-snapshot-go.appspot.com/ionic2/snapshots/i2sl/vgfd/chrome_400x800#f3156f5c

![image](https://cloud.githubusercontent.com/assets/452425/11161543/7addb8c4-8a45-11e5-8a12-72401cded92b.png)

**Comment by adamdbradley** [comment]
Related: 
![image](https://cloud.githubusercontent.com/assets/452425/11161546/98b1b5ee-8a45-11e5-8c41-de22347ae9aa.png)

http://ionic-snapshot-go.appspot.com/ionic2/snapshots/i2sl/vgfd/chrome_400x800#284249da

**Comment by adamdbradley** [comment]
![image](https://cloud.githubusercontent.com/assets/452425/11161561/f263a570-8a45-11e5-9b8a-ba6806c6236d.png)

**Comment by brandyscarney** [comment]
http://ionic-snapshot-go.appspot.com/ionic2/snapshots/i2sl/xhga/chrome_400x800#b96eaf50
