### ISSUE TITLE
reduce left margin from stacked labels

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#518]
http://ionic-snapshot-go.appspot.com/ionic2/snapshots/i2sl/vgfd/chrome_400x800#92efdb5b

![image](https://cloud.githubusercontent.com/assets/452425/11161569/2acbd374-8a46-11e5-8d4a-9d01acb961f0.png)

Probably a question for @bensperry though, should it be reduced????

**Comment by bensperry** [comment]
Well, yeah on the text it should be flush with the line. But why is do the lines now not go the full width on the right/left? Is that intentional?

**Comment by brandyscarney** [comment]
Yis @bensperry the left is intentional, right was not

**Comment by bensperry** [comment]
Okay then yeah, we should make the right edge of the line flush with the edge
