### ISSUE TITLE
bug: Angular2 & ionic 2 blank screen Samsung

### ISSUE THREAD

**Issue by romanornr** [driftyco/ionic2#519]
Type: bug

Platform: android 4.x webview

Recently I noticed that apps written with ionic 2 alpha have some problems.

Samsung devices have problems with opening the app. The app will load & show a blank screen. 
Other devices just showed the app.

Not sure but there seems to be a case that ionic 2 is slightly slower too.

The app failed to load on a Samsung device 
But succeeded to open on a HTC smartphone.

**Comment by adamdbradley** [comment]
What version of android is it? There large differences between 4.0, 4.1 - 4.3 and 4.4. Are there any errors? What version of Ionic2 is it?

**Comment by kbytesys** [comment]
I've got same error with android 4.0 devices.

Same app with 5.x android works fine.

**Comment by adamdbradley** [comment]
What's the error?

**Comment by kbytesys** [comment]
This is the android log output.

[android.txt](https://github.com/driftyco/ionic2/files/36803/android.txt)

**Comment by mhartington** [comment]
Hmm, the log does't tell a whole lot. This sounds pretty familiar to https://github.com/driftyco/ionic2/issues/794 which was fixed a few days ago. Mind giving it a shot with alpha48

**Comment by kbytesys** [comment]
Nope. How I could give you more debug info?

**Comment by mhartington** [comment]
@kbytesys is this still broken with the latest alpha49?

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#4964
