### ISSUE TITLE
Ionic2: Can we have app.ts instead of app.js?

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#527]
I've created a tabs project and it has "app.js" as main file but contains TypeScript code in it.

Should/can it be renamed to "app.ts"?

I tried to do and got error:
```
$ ionic serve
∆ Compiling and bundling with Webpack...
√ Using your webpack.config.js file: /Users/astec/DebtsTracker/ionic_app/webpack.config.js 

multi main
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/astec/MyApp/ionic_app/www/app/app.js in /Users/astec/MyApp/ionic_app
resolve file
  /Users/astec/MyApp/ionic_app/www/app/app.js doesn't exist
  /Users/astec/MyApp/ionic_app/www/app/app.js.js doesn't exist
  /Users/astec/MyApp/ionic_app/www/app/app.js.ts doesn't exist
resolve directory
  /Users/astec/MyApp/ionic_app/www/app/app.js doesn't exist (directory default file)
  /Users/astec/MyApp/ionic_app/www/app/app.js/package.json doesn't exist (directory description file)
[/Users/astec/MyApp/ionic_app/www/app/app.js]
[/Users/astec/MyApp/ionic_app/www/app/app.js.js]
[/Users/astec/MyApp/ionic_app/www/app/app.js.ts]
 @ multi main (CLI v2.0.0-alpha.22)
```
Renaming to "app.js.ts" did not help - a lot of errors.

**Comment by tlancina** [comment]
Yep app.ts should work just fine, you'll need to update your webpack entry file: https://github.com/driftyco/ionic2-app-base/blob/master/webpack.config.js#L9.

**Comment by astec** [comment]
@tlancina,Thanks for pointing to the config - I'll try it.

But should the base app have contains the "app.ts" instead of "app.js" by default? It looks strange that JS file contains TS code.

**Comment by tlancina** [comment]
Good question! We left it as .js because we want TS to be optional; we support it, but don't want to force people to use it if they don't want to.  I believe the only TS code in there is constructor types that Angular needs to do dependency injection.

There is an alternate syntax, instead of `constructor(thing: Thing)` you can do `constructor(@Inject(Thing) thing)`, but because we have to use the typescript compiler for Angular anyways we decided to use the less verbose syntax.

**Comment by astec** [comment]
Imports and the @ attributions does not look like a JS either. May be it's a part of ES6 which I am not familiar with.

Anyway I would suggest at least to add some comments to the file regards how to change it from JS to TS as it's very handy for IDE to have it as TS. And would be good for newcomers.

**Comment by arun0009** [comment]
renaming extension to .ts doesn't work (with update in webpack.config.js to app.ts). Webstrom shows weird errors on page because the file isn't really a javascript file. Any alternative way to rename files to typescript extensions?

**Comment by tlancina** [comment]
Re-opening, I'll take a look at this tomorrow.

**Comment by prolink007** [comment]
Also, seeing the same issue. Tried re-naming and getting the same issues as reported. Would love to see this fixed soon. =D

**Comment by jgw96** [comment]
IMO shouldn't all the starter templates be setup for Typescript by default? I understand not wanting to force Typescript, but all the angular2 docs point towards Typescript first, with es6 and es5 as optional so shouldn't ionic do the same?

**Comment by jgw96** [comment]
This also causes issues in visual studio code too using the starter tabs template. Since all the extensions are .js, but the project uses a tsconfig.json file instead of a jsconfig visual studio code complains about not having a jsconfig file and marks the whole Components in red. Since its using a tsconfig file that just reinforces that it should be set up for Typescript by default.

**Comment by juristr** [comment]
@jgw96 :+1:

**Comment by Dorkside** [comment]
+1

**Comment by rohirrin** [comment]
Please fix this, in IDE's like webstorm also cause issues with the .js extension in a .ts file. Will be great if you let the user choice what extension to use.

**Comment by Dorkside** [comment]
As a temporary fix for Webstorm and surely other IDEs you can change the extension to *.ts.js and add that into file type extensions for typescript.
This allows for code completion and styling which is the feature I was looking for.

**Comment by tlancina** [comment]
Hey all, this is on our roadmap in the very near future, and will most likely happen after https://github.com/driftyco/ionic2/issues/619.

**Comment by prolink007** [comment]
@tlancina Thanks, looking forward to this feature.

**Comment by jgw96** [comment]
@tlancina Just have to say this issue and the quick response really shows how awesome of a community the ionic community is

**Comment by astec** [comment]
I have a following workaround for now - moved all code to "my-app.ts" and in "app.js" I have just:
```
import {MyApp} from './my-app.ts';
export MyApp;
```

**Comment by juristr** [comment]
@astec nice 😁. Thx for sharing 👍

**Comment by giagar5** [comment]
Do you have issues making the ionic-cli understand that a ts file has been updated? In my case I don't see updates to ts files (after the first one)

**Comment by tobiasmuecksch** [comment]
@giagar5 Yes. That is one of the problems related to this issue.

**Comment by giagar5** [comment]
Don't ask me why, but seems that a workaround is to use in the webpack.config.js (line 31):
"test: /\.ts(x?)$/"
instead of
"test: /\.js$/"

**Comment by tlancina** [comment]
With the latest `ionic@beta` you can do do `ionic start myapp --v2 --ts` to download the Typescript version of the starter.

**Comment by jgw96** [comment]
@tlancina Very nice! Ive been waiting for this for a while. Tell the whole team thanks please!
