### ISSUE TITLE
bug: <ion-radio-group> does not handle change events with dynamic options

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#530]
The code below renders fine but does not update value of `currenciesControl`.
```
<ion-radio-group ng-control="currenciesControl">
  <ion-radio *ng-for="#currency of currencies" [checked]="currency==selectedCurrency" [value]="currency">{{currency}}</ion-radio>
</ion-radio-group>
```

If options hardcoded in template it is working almost as expected:
1. On click control value is updated - OK
2. But on initial render until clicked the controls value is empty even if I specify checked for an option and for control in TS file as well.
```
<ion-radio-group ng-control="currenciesControl">
  <ion-radio value="USD">USD</ion-radio>
  <ion-radio value="EUR">EUR</ion-radio>
</ion-radio-group>
```

**Comment by brandyscarney** [comment]
Thanks for reporting this! The next release will have this fix (2.0.0-alpha.37). Also, #650 will cause some changes to the markup. :)
