### ISSUE TITLE
Platform doc section

### ISSUE THREAD

**Issue by ydeshayes** [driftyco/ionic2#531]
In the http://ionicframework.com/docs/v2 platform section, everything is gone except storage.

And when I deploy my app with the @32 Device, Camera, Geolocation are not working anymore ...
Did you remove all the ionic wrappers API ?

Thanks

**Comment by nihgwu** [comment]
yes, u have to write your own implementation right now
https://github.com/driftyco/ionic2/commit/803d73606a6358213f4778503c09b995c7537389

**Comment by adamdbradley** [comment]
We're reorganizing the wrappers right now, but the ultimate goal will be to make it easier on you by allowing these plugins to be easily maintained and added.

**Comment by mlynch** [comment]
Closing since we are moving over to Ionic Native https://github.com/driftyco/ionic-native
