### ISSUE TITLE
docs: update segment code

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#540]
The segment code doesn't match the demo, and it is outdated. http://ionicframework.com/docs/v2/components/#segment

Also, there should be an example of a segment in a toolbar.

**Comment by drewrygh** [comment]
The segment in toolbar example could possibly be added to the API docs when we have demos there? 

The main reason it wasn't used in the components demo section was for design/consistency (every other section has the title of the component in the toolbar).

**Comment by brandyscarney** [comment]
hmm ok. I just want the users to know they shouldn't put it in the `ion-title` when it's in a toolbar.
