### ISSUE TITLE
bug: ripple on a[ion-item] is huuuuge

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#548]
http://localhost:8000/e2e/item/buttons/

**Comment by adamdbradley** [comment]
explain yourself. Is it not supposed to fill the length of the button?

**Comment by brandyscarney** [comment]
It fills buttons fine, anchors it is much larger than the anchor. a huge circle.

**Comment by brandyscarney** [comment]
![screen shot 2015-11-16 at 4 04 17 pm](https://cloud.githubusercontent.com/assets/6577830/11194742/d239661c-8c7b-11e5-82cf-40b177108316.png)

**Comment by brandyscarney** [comment]
If you look at this example you can see that it shows up at the top no matter which one you click: http://ionicframework.com/docs/v2/components/#card-list
