### ISSUE TITLE
bug: click-block preventing switching between inputs 

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#550]
View the demo at http://localhost:8000/e2e/text-input/floating-labels/

When you click on the second input and then try to click on another input the div with click-block shows up and you have to click ~ 3 times to get it to switch focus. 

Also, these errors are showing up, not sure if related:

![screen shot 2015-11-16 at 7 07 22 pm](https://cloud.githubusercontent.com/assets/6577830/11198725/49b695b6-8c95-11e5-886f-a8b788eab53b.png)

**Comment by adamdbradley** [comment]
This was just fixed in master: https://github.com/driftyco/ionic2/commit/3ec39c51b5859c566e40c7ceeb4445990f342bb9
