### ISSUE TITLE
ion-sliding-item: On iOS 9.1 need to click twice to push to another view.

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#551]
Works fine&stable in browser but on device need to click 2-3-4 times to get action but sometimes it works from 1st time. Before updating to alpha32 it worked fine. Tried to apply (click) to both `ion-item-sliding` & `ion-item` - did not help.

```
		<ion-item-sliding detail-push *ng-for="#contact of contacts" (click)="showContact(contact)">
			<ion-item>
				<div class="item-right">
					<div *ng-for="#balance of contact.balances">
						<h3  class="balance-credit"> {{balance.amount}} {{balance.currency}}</h3>
					</div>
				</div>
				<h2><a href="javascript:false">{{contact.name}}</a>
					<sup *ng-if="contact.isDemo" class="demo">demo</sup></h2>
				<p>Some text</p>
			</ion-item>
			<ion-item-options>
				<button danger (click)="recordBorrowing(directionFromUser, contact)" >Opt#1</button>
				<button secondary (click)="recordBorrowing(directionToUser, contact)">Opt#2</button>
			</ion-item-options>
		</ion-item-sliding>
```

@adamdbradley By the way the tabs starter does not reflect the new layout for sliding item so it's broken at the moment.

**Comment by juliendecoster** [comment]
Hi,

Same problem here. Actually it seems like you need to wait 3 or 4 seconds after a back before clicking the next item. When you're "too quick" it ignores the first clicks, that's why it seems like you need to click 3 or 4 times.

**Comment by adamdbradley** [comment]
@astec I wouldn't recommend using `<a href="javascript:false">` within the item, but instead just style the `h2` element. Also, the `ion-item-sliding` should not have the click handler on it, but instead `<button ion-item>` should. What's happening is that you're wrapping buttons with buttons and it's causing issues.

**Comment by adamdbradley** [comment]
This is a good example for the structure, we'll have to get this documented: https://github.com/driftyco/ionic2/blob/master/ionic/components/item/test/sliding/main.html#L12 cc/ @drewrygh
