### ISSUE TITLE
Error when initializing tabs

### ISSUE THREAD

**Issue by frederikschubert** [driftyco/ionic2#556]
When a page with tabs is pushed to the `NavController` the tabs are being initialized one after another with an interval of 1s (https://github.com/driftyco/ionic2/blob/master/ionic/components/tabs/tab.ts#L106). This leads to problems in case that the page is popped from the stack before all tabs have been initialized.
It also seems that the tabs are not being reused. When the tab page is pushed and popped several times the tab identifier is incremented. Example with 3 tabs:
`nav.push(TabPage);` => select tab 0: 46.343ms
`nav.pop();`
`nav.push(TabPage);` => select tab 3: 9.123ms
`nav.pop();`
`nav.push(TabPage);` => select tab 6: 3.786ms

**Comment by adamdbradley** [comment]
If you pop the entire tabs page, then push on a new one, then yes, it'll get recreated each time. Also, you can disable preloading tabs by using `<ion-tabs preload-tabs="false">`. Does that help?

**Comment by frederikschubert** [comment]
I tried disabling the preload but it does not work. The tabs are still preloaded and the following error is shown:
```
TypeError: Cannot read property 'nestedView' of null
    at ElementInjector.getNestedView (app.bundle.js:24551)
    at AppView.getNestedView (app.bundle.js:23799)
    at AppViewManager_.getNamedElementInComponentView (app.bundle.js:25231)
    at DynamicComponentLoader_.loadIntoLocation (app.bundle.js:34172)
    at Tab.loadPage (app.bundle.js:63567)
    at Tab.loadPage (app.bundle.js:67156)
    at Tab._stage (app.bundle.js:63550)
    at Tab._transition (app.bundle.js:63485)
    at Tab.push (app.bundle.js:63231)
    at Tab.load (app.bundle.js:67139)
```

**Comment by adamdbradley** [comment]
Yup you're right, the preload tabs doesn't work and I can fix it quick ("false" is a string and I'm doing some bad boolean checking there). As for the nestedView error, do you get that with and without preload-tabs="false"?

**Comment by frederikschubert** [comment]
I get the error both times when popping the page before the other tabs have been initialized.

**Comment by adamdbradley** [comment]
Ok so it's probably unrelated to the preloading, but just the tab itself. Does it have a navbar? What does the structure look like for that tab?

**Comment by adamdbradley** [comment]
So preloading tabs should be fixed in master, and we'll be getting out the next version of alpha out today: https://github.com/driftyco/ionic2/commit/47f505a66a681dbdc0a0907b8dea4e6feee58fc9

Still debating if preloading tabs should be the default, and I'm starting to lean toward not preloading tabs by default. Thoughts?

**Comment by frederikschubert** [comment]
Great! I would also disable preloading the tabs by default because the gains of a smaller initial delay when opening the tabs does not outweigh the confusion that might be introduced by that feature.

**Comment by adamdbradley** [comment]
Great point and I fully agree. I just made the change here: https://github.com/driftyco/ionic2/issues/556#issuecomment-157400715

**Comment by adamdbradley** [comment]
What does your markup look like for that Page that's being loaded into the tabs?

**Comment by frederikschubert** [comment]
I will post it tomorrow :) Basically it is just a ion-navbar with an ion-content that contains a searchbar and a list of cards.

**Comment by frederikschubert** [comment]
```html
<ion-navbar *navbar id="overview-navbar">
	<ion-nav-items primary>
		<button class="back-button show-back-button" (click)="logout()">
			<icon class="back-button-icon" arrow-back></icon>
			<span class="back-button-text">
				<span class="back-default">
					Logout
				</span>
			</span>
		</button>
	</ion-nav-items>
	<ion-title>Elevators</ion-title>
	<ion-nav-items secondary>
		<button (click)="openFilter()">
			<icon ios="funnel-outline" md="funnel"></icon>
		</button>
	</ion-nav-items>
</ion-navbar>
<ion-content>
	<form [ng-form-model]="form">
		<ion-toolbar>
			<ion-searchbar primary ng-control="searchQuery"></ion-searchbar>
		</ion-toolbar>
		<ion-card *ng-for="#elevator of elevators | async" (click)="showDetails(elevator)">
			<ion-card-header>
				{{ elevator.elevatorNumber }}
				<span style="float: right;">
					<icon arrow-forward></icon>
				</span>
			</ion-card-header>
			<ion-card-content>
				<p style="display: inline-block;">
					{{ elevator.postalCode }} {{ elevator.city }}, {{ elevator.street }}
				</p>
			</ion-card-content>
		</ion-card>
	</form>
</ion-content>
```

**Comment by adamdbradley** [comment]
I'm not able to get any errors. Can you remove markup until you don't get an error to help narrow this down? Also, why not just use `<icon funnel></icon>`? And I see you're recreating the back button, can you just use a normal button in the top?

**Comment by frederikschubert** [comment]
I can not recreate the issue with the newest version. I recreated the back button because I wanted a custom label on it (Logout).

**Comment by adamdbradley** [comment]
Cool, I'll close this one then. Please reopen if you're still having issues, thanks.
