### ISSUE TITLE
Add more margin to left side of md card avatar

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#559]
http://ionic-snapshot-go.appspot.com/ionic2/snapshots/i2sl/wwhl/chrome_400x800#f19f19f3

![image](https://cloud.githubusercontent.com/assets/452425/11216601/a16a3480-8d11-11e5-842f-d11d321427cf.png)

**Comment by brandyscarney** [comment]
So I don't know what was going on with the snapshot this morning, but this isn't an issue anymore: http://ionic-snapshot-go.appspot.com/ionic2/snapshots/i2sl/h8lk/chrome_400x800#2b1e0117

![screen shot 2015-11-17 at 3 06 32 pm](https://cloud.githubusercontent.com/assets/6577830/11223226/dcaad678-8d3c-11e5-93d7-8a5203a9de7a.png)
