### ISSUE TITLE
Vertical top item text w/ avatar/thumbnail

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#561]
http://ionic-snapshot-go.appspot.com/ionic2/snapshots/i2sl/wwhl/chrome_400x800#2ef8c609

![image](https://cloud.githubusercontent.com/assets/452425/11216672/143470ac-8d12-11e5-9444-9241b84a57ec.png)

probs double check with @bensperry

**Comment by brandyscarney** [comment]
I aligned it to the top. Easy to remove if Ben says otherwise. :)

**Comment by adamdbradley** [comment]
@bensperry never checks github issues. I think we're good.
