### ISSUE TITLE
ion-item: Add/return touch effect on list item click

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#562]
I may be wrong but I have a feeling that until recently (*before ionic:alpha23/framework:alpha32*) if you click on a list item it changed appearance like "pressed" while navigating to another view.

Now nothing is indicating the pressing and feels unresponsive (iOS 9.1).

Expected like here (*background change*):

<img src="http://forum.ionicframework.com/uploads/default/original/3X/c/5/c5c4ecf916667723c7551465ca18910b92d1b2f1.gif" alt="Ionic list item press animation">

**Comment by adamdbradley** [comment]
Can you provide some markup?

**Comment by adamdbradley** [comment]
Closing for now. Please feel free to reopen with some example code, thanks.
