### ISSUE TITLE
grid (col+row) components need attributes

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic2#563]
At the moment, it's only possible to set the offset using classes.

**Comment by brandyscarney** [comment]
See [grid/test/basic/main.html](https://github.com/driftyco/ionic2/blob/master/ionic/components/grid/test/basic/main.html) for examples and [grid.scss](https://github.com/driftyco/ionic2/blob/master/ionic/components/grid/grid.scss) for all attributes
