### ISSUE TITLE
Replace the .item-group selector for ion-item-group

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#568]
The `ItemGroup` directive doesn't provide anything other than adding the `.item-group` css class, and it should use an element selector instead.

**Comment by adamdbradley** [comment]
Same goes for `.item-group-title` css being moved to `ion-item-group-title`

**Comment by brandyscarney** [comment]
@adamdbradley do you want me to remove the class being added by the selector too or just change the css selectors?

**Comment by adamdbradley** [comment]
Just change the css so it only uses the element selectors, then we can get rid of the directives

**Comment by brandyscarney** [comment]
Ok then this is done
