### ISSUE TITLE
Missing components

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic2#569]
- [ ] Infinite-Scroll
- [ ] Pull to refresh
- [ ] Popover
- [ ] SVG Spinners
- [ ] Loading service
- [ ] Range slider
- [ ] Select Boxes
- [ ] Search Bar #247

**Comment by frederikschubert** [comment]
A TextArea wrapper would also be nice to have. Currently when using a `<textarea>` element in an Ionic 2 App an Exception is thrown.
```
TypeError: Cannot read property 'hasValue' of null
    at TextInputElement.onInit (http://localhost:8100/build/js/app.bundle.js:86596:26)
...
```

**Comment by adamdbradley** [comment]
We're tracking these just fine and this issue is too vague.

@frederikschubert are you using an `ion-input`? http://ionicframework.com/docs/v2/components/#inputs Also, if you're using textarea outside of ion-input and receiving that error, then yes that's a bug. I'll fix that quick, thanks for the report.

**Comment by frederikschubert** [comment]
Yes I am using the textarea outside of an ion-input in an ion-list.

**Comment by adamdbradley** [comment]
Fixed it here: https://github.com/driftyco/ionic2/commit/c420c0d72680cdd1b23bc3562227d3cd6bb3e97d

**Comment by frederikschubert** [comment]
Great! Thank you!

**Comment by thiphariel** [comment]
Hi, just for my knowledge (and other's too), there is no milestone for these "missing components", so, is there some blocking part from angular2 or you just prefer to wait more until release them ?

Just asking it 'cause I'm interested with "Loading service", which is really awesome on v1.

Thanks
