### ISSUE TITLE
feat(tabs): add ability to override text-color and highlight-color(md)

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#570]
Users should be able to declare when they want the background, text, or highlight-color to be changed. See md docs: https://www.google.com/design/spec/components/tabs.html#tabs-usage

**Comment by drewrygh** [comment]
Maybe we could we just have a general text-color attribute? This would be useful for other components as well.

**Comment by drewrygh** [comment]
I also agree that highlight color should be easier to set. 

(From the components preview app):
```
body.md .cards-bg tab-highlight {
  background-color: #fff !important;
  top: 0;
}
```

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5061
