### ISSUE TITLE
ion-list: Bottom border left margin if last item is hidden

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#572]
@brandyscarney 
```
<ion-list>
 <ion-item>Item #1</ion-item>
 <ion-item>Item #2</ion-item>
 <ion-item *ng-if="false">Item #3</ion-item>
</ion-list>
```
Item 2 would not have bottom border from very left as expected.

I use last item to show buttons related to the list that is visible at certain conditions. May be there is a better way to do it?

**Comment by brandyscarney** [comment]
So this is happening because of the `<script></script>` tag that gets added by Angular. It will be removed when this is released: https://github.com/angular/angular/pull/5227 and that should fix it. 

I can't think of a quick fix for this right now, but I can look into it more tomorrow.

**Comment by astec** [comment]
That's not urgent. I can wait for the Angular's fix. Thanks.

**Comment by brandyscarney** [comment]
This is now fixed in 2.0.0-alpha.44 with the latest release of Angular. Thanks for the issue. :smile:

**Comment by astec** [comment]
@brandyscarney Cool! Can we expect to get https://www.npmjs.com/package/ionic updated today or I need to switch to git/master to verify?

**Comment by brandyscarney** [comment]
The npm package called `ionic` is for the CLI. The package for v2 of the SDK is called `ionic-framework` and this was released yesterday: https://www.npmjs.com/package/ionic-framework

There's a good description on this here: http://ionicframework.com/docs/v2/getting-started/concepts/
