### ISSUE TITLE
bug: Using *ngIf on item-left, item-right places it in ion-item-content

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#574]
If you use a *ngIf on a thumbnail in an item it will place it inside of the `ion-item-content` instead of of outside of it.

![screen shot 2015-11-17 at 7 07 57 pm](https://cloud.githubusercontent.com/assets/6577830/11228954/a4a21fbc-8d5e-11e5-93ed-0440c4666758.png)

**Comment by brandyscarney** [comment]
Opened an issue with angular for this after discussing with Igor: https://github.com/angular/angular/issues/5363

**Comment by brandyscarney** [comment]
Changing the priority on this since there is a temporary workaround:

```
<template [ng-if]="true" item-left>
  <ion-avatar item-left>
    <img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAAAAACH5BAAAAAAALAAAAAABAAEAAAICTAEAOw==">
  </ion-avatar>
</template>
```

cc @advany

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5060
