### ISSUE TITLE
Menu doesn't close in android

### ISSUE THREAD

**Issue by vamsivarikuti** [driftyco/ionic2#580]
http://ionicframework.com/docs/v2/components/#menus

![screen shot 2015-11-18 at 11 55 46 pm](https://cloud.githubusercontent.com/assets/7098541/11249974/13cd8ac4-8e50-11e5-893e-351557c09ddb.png)

**Comment by drewrygh** [comment]
@adamdbradley - the android demo is set to `display: none` initially and the menu width uses the initial width of `0`
