### ISSUE TITLE
SqlStorage error with prefilled sqlite db

### ISSUE THREAD

**Issue by gachen95** [driftyco/ionic2#587]
I modified the demo code in https://github.com/driftyco/ionic2/blob/master/demos/storage/index.ts

Bug 1:

     this.sql = new Storage(SqlStorage, {name: "planner.db", existingDatabase: true});

always opened default db DB_NAME = '__ionicstorage'

Solution:
Modified https://github.com/driftyco/ionic2/blob/master/ionic/platform/storage/sql.ts

       /*var dbOptions = util.defaults({
            name: DB_NAME,
            backupFlag: SqlStorage.BACKUP_LOCAL,
            existingDatabase: false
        }, options);*/
        var dbOptions = util.defaults(options,
          {
            name: DB_NAME,
            backupFlag: SqlStorage.BACKUP_LOCAL,
            existingDatabase: false
        });
        
        
Bug 2:

      this.sql.query('INSERT INTO test_tab(name) values('test_123456')');

in app.bundle.js, it become
      
      this.sql.query('INSERT INTO test_tab(name) values(', test_123456, ')');

Solution:
add a varible before this sql. Not a good soultion

      var test_123456='test_123456'

Bug 3:

      this.sql.query('select * from test_tab') got error
      ORIGINAL EXCEPTION: ReferenceError: Can't find variable: key

       Bug 2 after applying solution, got the same error,too.

**Comment by mlynch** [comment]
Hey @gachen95 thanks for the report. I applied your first for the first one. The last two don't seem like Ionic errors but possibly issues with the build? That last one doesn't make sense since key isn't even in the query function. Any more info or code to share?

**Comment by gachen95** [comment]
Hey @mlynch thanks for the quick reply. I created a test project on https://github.com/gachen95/SqliteProject.

For bug#2, you can find it at www/build/js/app.bundle.js
line 73569 this.sql.query('INSERT INTO test_tab(name) values(', test_123456, ')');

For bug#3, I test it on IOS simulator. Clicking Select and Insert buttons can reproduce it by monitoring by Safari. The Get/Set/Remove could successfully get/save/delete data from default table in the prefilled db

Please let me know what other information you needs. Thanks again.

**Comment by mlynch** [comment]
The first is an incorrect copy paste, and I'm fixing the comment. 7db1ded

**Comment by mlynch** [comment]
Can you file an issue for the last one? I can't figure out what you're referring to exactly
