### ISSUE TITLE
Swipe left on list item and click on option button it moves to next page and then shows me the the pop up confirmation which i have added to delete button

### ISSUE THREAD

**Issue by ajaybeniwal** [driftyco/ionic2#588]
This issue was fixed in previous version but I am using alpha 34 and issue is reoccurring again in the new version

**Comment by adamdbradley** [comment]
Can you provide the markup you're using please?

**Comment by ajaybeniwal** [comment]
`<ion-content>
<ion-searchbar  [(ng-model)]="searchQuery" placeholder="SearchRequest"></ion-searchbar>
  <ion-list>
    <ion-item-sliding *ng-for="#chat of getFilterChats()" (click)="passChat(chat)">
    <button ion-item (click)="openSession(session)">
   <ion-row center>
      <h2 class="col">{{chat.name}}</h2>
      <p class="col flex"><span style="margin-right:10px;">{{chat.status}}</span></p>
      </ion-row>
      <ion-row><p class="col">{{chat.lastText}}, {{chat.shipmentText}}</p></ion-row>
        <ion-row><p class="col">{{chat.dateText}}</p></ion-row>
    </button>
    
      <ion-item-options>
        <button light (click)="remove(chat)">Reject</button>
        <button  (click)="accept(chat)">Accept</button>
      </ion-item-options>
    </ion-item-sliding>
     <ion-item-group [class.hide]="getFilterChats().length > 0">
    <ion-item-group-title class="no-results">
      No Request Found
    </ion-item-group-title>
  </ion-item-group>
  </ion-list>
</ion-content>`

**Comment by adamdbradley** [comment]
You have multiple click handlers wrapping the same buttons, so it's difficult for Ionic to guess which click you are meaning to run. For example, the entire item has passChat() around it, then the inner button has openSession() on it, and the option buttons have remove() and accept(). When you click any of the inner buttons, it's not able to easily tell which one you mean, especially during swipe actions and fast taps on touch when some of the elements are buttons, and some aren't. I'd recommend not putting any clicks on the outer ion-item-sliding. Only buttons should have click events.

**Comment by ajaybeniwal** [comment]
Sorry My mistake copy pasted from conference app at wrong place yes,  it works fine apart from the issue that pop up is blank which is logged as another issue so closing this issue now

**Comment by adamdbradley** [comment]
Cool good to hear. We'll have to make sure we document this well, thanks! cc/ @mhartington
