### ISSUE TITLE
Inputs with addons (aka input group in bootstrap)

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#590]
Is it possible or planned to have inputs with addons like in bootstrap?

http://v4-alpha.getbootstrap.com/components/input-group/#button-addons

For example I want to have an "amount" input with a button that changes currency (*either dropdown or a modal*).
```
<ion-input>
  <ion-label>Amount</ion-label>
  <input type="number">
  <button right>USD</button>
</ion-input>
```
I think it is a must have. Miss them a lot.

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5058
