### ISSUE TITLE
Auto-complete component 

### ISSUE THREAD

**Issue by forkmind** [driftyco/ionic2#594]
The [current ionic search component](http://ionicframework.com/docs/v2/components/#search) in ionic 2 allow you to search through a list in the current tab (visible to the user). It would be great to be able to search from a collection or a javascript array as well. This option would be particularly useful for API requests or for a quick search through your whole application.
I think what does this [plugin](https://github.com/guylabs/ion-autocomplete) should be a native component in ionic 2.

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5057
