### ISSUE TITLE
Standardize config setting names

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#60]
Make sure they all make sense and follow some sort of pattern

**Comment by adamdbradley** [comment]
@mhartington would you be able to collect up all config names used within `config.get()` and put them in the config docs? Once we see them all lined up next to one another it might be easier to figure out what needs to be standardized.

**Comment by mhartington** [comment]
So far the basic ones from modes.ts

Action
actionSheetEnter
actionSheetLeave
actionSheetCancelIcon
actionSheetDestructiveIcon

Navigation
backButtonText
backButtonIcon
viewTransition
tabSubPages
type

Icons
iconMode

Modal
modalEnter
modalLeave

Tabs
tabbarPlacement
'tabbarIcons'
'tabbarStyle'
'preloadTabs'

Popups
popupPopIn
popupPopOut

Misc
mdRipple

**Comment by adamdbradley** [comment]
I'm going to change mdRipple to instead be 'activator' == 'ripple'.

**Comment by mhartington** [comment]
There are still some other ones like 

```
'root',
'tabTitle',
'tabIcon'
```
for tab.ts, want those as well?

**Comment by adamdbradley** [comment]
No for the tab attributes of root, tabTitle and tabIcon. Those are specific to just that one element.

**Comment by brandyscarney** [comment]
I think we should rename `tabSubpages` to `tabbarSubpages` to be more consistent with 

```
tabbarPlacement
tabbarIcons
tabbarStyle
```

Or rename all the `tabbar`'s to `tabs`. Either way.

**Comment by adamdbradley** [comment]
I think it's that `tabSubpages` just isn't a good name at all. The `tabbar` is specifically for the tabbar, such as the style and where the tabbar itself is placed. Tab subpages means that when your on the first page in tabs, and navigate to the second page, the second page goes over the tabbar. IOS doesn't do this and you always see the tabbar, but material design's second page will cover the tabbar. What's that called??

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5056
