### ISSUE TITLE
List Dividers don't have a background different from the list

### ISSUE THREAD

**Issue by richardshergold** [driftyco/ionic2#601]
I think a list divider is supposed to be automatically coloured with a different background from the list its in (I think?) but I'm not seeing that (alpha 34)

```
<ion-list>
<div class="item item-divider">
      <h2>My Divider</h2>
</div>
</ion-list>
```

**Comment by brandyscarney** [comment]
There is no styling for the `item-divider` class anymore. Right now it is done by using an `ion-header` in a list, but that is also not styled. See the docs here: http://ionicframework.com/docs/v2/components/#list-headers

I agree though, there should be a list divider with a colored background, even if it is just putting an attribute on an `ion-header`. 

Related: #418

cc @adamdbradley

**Comment by adamdbradley** [comment]
Let's go with `ion-item-divider` to stay consistent with v1.

**Comment by brandyscarney** [comment]
Added the `ion-item-divider` element with this commit: https://github.com/driftyco/ionic2/commit/c2a4b70d310244b34b156f480f439f8bb9b128a3

It will be in the next release. Thanks for letting us know. :)
