### ISSUE TITLE
Add docs for npm, node_modules, etc

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#602]
There has been a lot of confusion around npm in general. Would be good to add some docs on it. I think we discussed adding it in Resources and linking to it in the installation/getting started?

http://forum.ionicframework.com/t/updating-ionic2-alpha/36671/9

**Comment by adamdbradley** [comment]
:+1:

**Comment by tlancina** [comment]
dup of #538 fyi

**Comment by brandyscarney** [comment]
Dang - I tried finding the issue, too! Closing.

**Comment by tlancina** [comment]
Yeah the title was bad (not easily searchable) feel free to change.
