### ISSUE TITLE
Modal - how to pass data and handle closing event?

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#604]
We tried to get and answer in http://forum.ionicframework.com/t/ionic-tabs-app-with-login-screen/37258 without success.

Looking to the Modal code I don't see how I can pass parameters the same way as I do with nav.push() and also don't see how I can handle changes when modal closes.

I was thinking may be it should be somehow done via overlay https://github.com/driftyco/ionic2/blob/master/ionic/components/modal/modal.ts#L34 - but I think there should be more simple & direct way for such a trivial & common task.

Any tips? Would be good to add it to docs for Modal - http://ionicframework.com/docs/v2/components/#modals

**Comment by adamdbradley** [comment]
Good point, we were missing out on passing params to a modal so it's recently been updated. What's in master and for the next release, the second parameter of `modal` you can give it params just like with `nav.push`. Here's an example: https://github.com/driftyco/ionic2/blob/0df42a903d6608a87583822901dfe2c2760a671e/ionic/components/modal/test/basic/index.ts#L33

We'll also get the modal docs updated, thanks. cc/ @mhartington @drewrygh

**Comment by astec** [comment]
https://github.com/driftyco/ionic2/commit/68ee8065c81023a475ff19bfc18e1cf957a3c601#diff-18a2989dde0d336325b3214f4127beb3R16

Accessing parameters throw `modal._defaults` looks counter-intuitive. I would assume `_defaults` are common data and `params` passed to the `open()` method are instance specific.

**Comment by adamdbradley** [comment]
@astec you're correct, it was poorly documented. I'll update it quick.

**Comment by astec** [comment]
BTW it would be good to document that `open()` returns a `Promise` that is resolved to a Modal instance. When I got it I understood that I can assign parameters & event handlers director to the instance. So this kinda eliminates the need for original request to pass parameters explicitly. Though I still believe it is a nice to have feature.

**Comment by adamdbradley** [comment]
You'd still probably wan to pass parameters and use NavParams, since the promise won't resolve until the animation completes. And if you don't update the modal until the animation completes you might see some jank once the data updates in the page.

**Comment by adamdbradley** [comment]
I've updated the docs and we'll get them pushed to the docs site soon, thanks: https://github.com/driftyco/ionic2/commit/d7e85fb380f27c3d73894447f4a207bb9e8ac16a

**Comment by aschwartz-satcom** [comment]
I always thought UI-Bootstrap did a good job of making sensible modals that follow the promise model:
https://angular-ui.github.io/bootstrap/#/modal

I wrote a simple wrapper that will allow you to launch ionic modals using the ui-bootstrap's .open() method syntax, define a controller for the modal, and receive a result/dismissal reason via promise.  You can also use 'resolve' parameters to pass additional data to the modal's controller.

If you want to try it out, include the attached .js file 
[ionic-bootstrapmodalwrapper-provider.js.txt](https://github.com/driftyco/ionic2/files/43996/ionic-bootstrapmodalwrapper-provider.js.txt)
 in your project, add a dependency to the 'ionic-bootstrap-modal-wrapper' module, and inject the $modal provider into your controller.
