### ISSUE TITLE
bug: Svg

### ISSUE THREAD

**Issue by felipereis** [driftyco/ionic2#605]
Ionic Version: "2.0.0-alpha.31"

![svg](https://cloud.githubusercontent.com/assets/2862216/11306422/cd6f9050-8f98-11e5-933a-55c0ef0def79.png)

```html
<ion-content padding>
  <svg viewBox="0 0 200 200">
      <circle cx="100" cy="100" r="100" fill="red" />
  </svg>        
</ion-content>
```

----------------------------------------------------
svg.html

![captura_de_tela-1](https://cloud.githubusercontent.com/assets/2862216/11306855/8f1967e2-8f9b-11e5-9298-9f26f37a33ce.png)

```html
<html>
<head>
</head>
<body>
<svg viewBox="0 0 200 200">
		<circle cx="100" cy="100" r="100" fill="red" />
</svg>
</body>
</html>
```

**Comment by adamdbradley** [comment]
Can you explain more of what you are expecting to happen? Also, I do know that angular2 itself hasn't completed full SVG support, but it's on their todo list before it releases.

**Comment by felipereis** [comment]
I want to scale my Svg but viewBox doesn´t work.

**Comment by adamdbradley** [comment]
When I do the same in the nav/basic test I get this:
![image](https://cloud.githubusercontent.com/assets/452425/11316463/b8421bc8-8fcd-11e5-90fa-6ac570321668.png)

https://github.com/driftyco/ionic2/tree/master/ionic/components/nav/test/basic

**Comment by felipereis** [comment]
Thanks Adam, I've been really enjoying working with ionic 2.

I removed node_modules folder from my project, updated package.json using the latest commit from github and run sudo npm install and ionic serve, works fine updating dependencies.

However, if i run sudo npm install -g ionic@alpha ionic-framework and create a new project, svg doesn´t work because angular2.alpha44, this version has namespace problem.

So I removed node_modules folder from my new project and updated dependencies using latest package.json,  and svg doesn´t appear, doesn´t make sense.

It would seem more logical to change the "ionic" package to "ionic-cli".


------------

Your system information:

Cordova CLI: Not installed
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.8.11
Ionic CLI Version: 2.0.0-alpha.23
Ionic App Lib Version: 2.0.0-alpha.22
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X Yosemite
Node Version: v4.2.2
Xcode version: Xcode 7.0.1 Build version 7A1001

**Comment by adamdbradley** [comment]
To update Ionic you change the version inside of your package.json file. For example, the ionic-conference-app is using the latest ionic npm module: https://github.com/driftyco/ionic-conference-app/blob/master/package.json#L10

Ionic is currently using Angular2 alpha.46.

**Comment by felipereis** [comment]
![captura de tela 2015-11-21 as 16 46 53](https://cloud.githubusercontent.com/assets/2862216/11319915/8720f4ae-906f-11e5-8ca8-57147a641ca3.png)

Updating Angular to alpha.46 fix the problem. 

I think this is something users are really going to use, it should be documented how to update Ionic.

It would seem more logical to change ionic package to ionic-cli, to prevent the user confuse them with ionic-framework.

Thank you @adamdbradley

**Comment by adamdbradley** [comment]
You're absolutely correctly, we'll get this documented, thanks. cc @mhartington @drewrygh
