### ISSUE TITLE
bug: floating labels disappear after opening and closing keyboard iOS

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#613]
![slack for ios upload-3 png](https://cloud.githubusercontent.com/assets/6577830/11313432/c42aa572-8faa-11e5-86e2-82565a38d037.jpeg)
![slack_for_ios_upload](https://cloud.githubusercontent.com/assets/6577830/11313434/c75be652-8faa-11e5-8dda-8d266c810a14.jpeg)

**Comment by adamdbradley** [comment]
There's also some jank from the cloned input bumping down the label while it's scrolling into place. When the cloned input is removed it then goes back to normal.
