### ISSUE TITLE
iOS: remove border from toolbar containing segment

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic2#614]
<img width="321" alt="screen shot 2015-11-20 at 4 55 38 pm" src="https://cloud.githubusercontent.com/assets/2018508/11313984/f7e18d8a-8fa6-11e5-9ac7-a0e9a5c267c5.png">

**Comment by brandyscarney** [comment]
So this is tricky because on iOS there is no border between the title and the segment in the next toolbar, but we can't use the segment to select a previous sibling in order to change it.

**Comment by adamdbradley** [comment]
Note: See if we can cleanly select and place an ion-toolbar inside of an ion-navbar

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5055
