### ISSUE TITLE
Alpha35 Keyboard Close issue

### ISSUE THREAD

**Issue by richardshergold** [driftyco/ionic2#616]
My app kicks off with a Login Screen with a Login Button on it.  Logging in then opens up the Tabs.

This all worked ok yesterday using Alpha34.

I upgraded to Alpha35 and now when I enter credentials and click the Login Button the popup keyboard does not close - my tabs open up behind it and I have to click "Done" in the keyboard header to close it.

**Comment by adamdbradley** [comment]
Does the login button preventDefault at all? Also, is the login screen the first page in the ion-nav, and the ion-tabs container is the second page?

**Comment by richardshergold** [comment]
In app.js I open up the login page i.e

this.root = LoginCtrl;

and then when the user has logged in (via the Login Button on that page) I push the TabsPage i.e

this.nav.push(TabsPage);

In alpha34 this worked fine i.e the keyboard closed and the Tabs displayed.  In alpha35 the keyboard stays displayed over the tabs and I have to click Done to remove it.

I don't specify preventDefaiult - not sure what that is. My button is coded like this:

<ion-list no-lines>
      <ion-item>
          <button block (click)="go()">Sign In</button>
      </ion-item>
  </ion-list>

It happens to be in a list but I doubt that's the cause?

**Comment by richardshergold** [comment]
my code didn't paste in then.  The button code is:

<ion-list no-lines>

      <ion-input>
          <ion-label>Username</ion-label>
          <input type="text" value="" [(ng-model)]="credentials.username">
      </ion-input>

      <ion-input>
          <ion-label>Password</ion-label>
          <input type="password" value="" [(ng-model)]="credentials.password">
      </ion-input>

  </ion-list>

**Comment by richardshergold** [comment]
ahh, wrong bit of code!  Here it is:

 <ion-list no-lines>
      <ion-item>
          <button block (click)="go()">Sign In</button>
      </ion-item>
  </ion-list>

**Comment by adamdbradley** [comment]
Should be fixed in the next release, thanks
