### ISSUE TITLE
Error on slide

### ISSUE THREAD

**Issue by patrickpereira** [driftyco/ionic2#617]
I get the following error on alpha35 "ERROR: EXCEPTION: TypeError: done is not a function. (In 'done()', 'done' is undefined)" when I try to slide the ion-menu.

My quick fix was to change this function in the js build file:

function parallel(tasks, done) {
	    var l = tasks.length;
	    if (!l && typeof done != 'undefined') {       //BEFORE it was :   if (!l){
	        return done();
	    }
	    var completed = 0;
	    function taskCompleted() {
	        completed++;
	        if (completed === l) {
	            done();
	        }
	    }
	    for (var i = 0; i < l; i++) {
	        tasks[i](taskCompleted);
	    }
	}

my system info is:

Your system information:

Cordova CLI: 5.2.0
Ionic Version: 2.0.0-alpha.35
Ionic CLI Version: 2.0.0-alpha.23
Ionic App Lib Version: 2.0.0-alpha.22
ios-deploy version: 1.8.2 
ios-sim version: 4.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 7.2 Build version 7C46t

**Comment by adamdbradley** [comment]
Thanks for the report. I'll add the fix in my next commit, thanks!
