### ISSUE TITLE
Re-organize npm package

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic2#619]
- [x] Add typings for CJS files
- [ ] ~~ionic.d.ts bundled typings~~ (see https://github.com/angular/angular/issues/5248#issuecomment-156886060)
- [x] Move CJS files to root directory
- [x] Add sass entry to root?
- [x] remove SystemJS and TS files
- [x] remove `dist` directory, have `bundles`,`es6`, `sass`, `tooling`, `fonts`
- [ ] move web.animations to bundledDependencies

**Comment by vadimpopa** [comment]
Would be great also to have by default the ionic2.d.ts file like angular2 has, in the bundles folder.

**Comment by agnellvj** [comment]
would it be possible to tag commits too with the npm version number so we can see what changed between alpha releases? :+1:

**Comment by tobiasmuecksch** [comment]
@agnellvj +1

**Comment by dmackerman** [comment]
Going to be watching this one closely. :+1:

**Comment by tlancina** [comment]
Closing this, tracking the rest in https://github.com/driftyco/ionic2/issues/724.
