### ISSUE TITLE
List on ios very slow

### ISSUE THREAD

**Issue by doabit** [driftyco/ionic2#622]
I followed http://ionicframework.com/docs/v2/getting-started/tutorial/, after run `ionic emulate ios`, when click list item, it becomes so slow, and style is not correct.

List.js

```
import {IonicApp, Page, NavController, NavParams} from 'ionic/ionic';

import {ItemDetailsPage} from '../item-details/item-details';

@Page({
  templateUrl: 'app/list/list.html'
})
export class ListPage {
  constructor(app: IonicApp, nav: NavController, navParams: NavParams) {
    this.nav = nav;

    // If we navigated to this page, we will have an item available as a nav param
    this.selectedItem = navParams.get('item');

    this.icons = ['flask', 'wifi', 'beer', 'football', 'basketball', 'paper-plane',
    'american-football', 'boat', 'bluetooth', 'build'];

    this.items = [];
    for(let i = 1; i < 11; i++) {
      this.items.push({
        title: 'Item ' + i,
        note: 'This is item #' + i,
        icon: this.icons[Math.floor(Math.random() * this.icons.length)]
      });
    }
  }

  itemTapped(event, item) {

     this.nav.push(ItemDetailsPage, {
       item: item
     });
  }
}
```

![1 pic](https://cloud.githubusercontent.com/assets/330368/11330303/6b2f18fe-91e4-11e5-8067-25ac699d41be.jpg)
![3 pic](https://cloud.githubusercontent.com/assets/330368/11330305/7392534e-91e4-11e5-906d-2e1acd76bfae.jpg)
![2 pic](https://cloud.githubusercontent.com/assets/330368/11330304/6fb12732-91e4-11e5-9972-1ed190271a5e.jpg)

**Comment by richardshergold** [comment]
I have the same problem on the simulator (if you are talking about he odd lines between some of the rows). Everything is ok when I run on a device though.

**Comment by doabit** [comment]
@richardshergold I've not tried on device, i found  click list row item, show ItemDetailsPage very slow, do you have the same problem? Thanks.

**Comment by richardshergold** [comment]
It seems ok to me - not bullet fast but not unreasonably slow.  Try the app on a device.

**Comment by doabit** [comment]
Thanks, i'll try.

**Comment by adamdbradley** [comment]
Regarding the performance issue we're actively looking into it with the angular team, thanks.
