### ISSUE TITLE
documentation for Modal is currently incorrect

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic2#624]
@Page({
      template: `
      <ion-content padding>
        <h2>I'm a modal!</h2>
        <button (click)="close()">Close</button>
      </ion-content>`
    })
    class MyModal Modal {
       constructor() {
       }
    }

should be

    @Page({
      template: `
       <ion-content padding>
        <h2>I'm a modal!</h2>
        <button (click)="close()">Close</button>
      </ion-content>`
    })
    class MyModal extends Modal {
      constructor() {
      }
    }

Also there should probably be something in the documentation about having to have ion-overlay in the root component. I know that ion-overlay is supposed to be removed in the future, but maybe there should be something in the docs about it until it is actually removed.

**Comment by drewrygh** [comment]
Thanks for pointing this out. It looks like the `Modal` keyword was never removed (`extends Modal` is no longer required.)

**Comment by adamdbradley** [comment]
The docs have been updated, thanks for pointing this out: https://github.com/driftyco/ionic2/commit/d7e85fb380f27c3d73894447f4a207bb9e8ac16a
