### ISSUE TITLE
How to restart App or destory tabs when i log-out?

### ISSUE THREAD

**Issue by jimmyrogue** [driftyco/ionic2#625]
I want to log-out 
button in tab --> loverPage---> subpage
I  try this 
```javascript
this.nav.setRoot(LoginPage);
this.nav.popToRoot();
```
but tabs still there 
I cant destory tabs
```
<ion-tabs tabbar-placement="bottom">
    <ion-tab tab-title="" tab-icon="calendar" [root]="eventPage"></ion-tab>
    <ion-tab tab-title="" tab-icon="paper" [root]="newsPage"></ion-tab>
    <ion-tab tab-title="" tab-icon="compass" [root]="postPage"></ion-tab>
    <ion-tab tab-title="" tab-icon="heart" [root]="loverPage"></ion-tab>
</ion-tabs>
<ion-overlay></ion-overlay>
```

how should I do?
thanks

**Comment by richardshergold** [comment]
I'm having a very similar issue - I want to add a Login Page to my app and have a button that takes me back to it (removing the tabs) but I haven't managed it.  It looks like the Ionic team are adding something similar to the conference app so I'm keen to see what they do in there.

https://github.com/driftyco/ionic-conference-app/tree/master/www/app

**Comment by richardshergold** [comment]
Maybe re-starting the app with

document.location.href = 'index.html';

would do the trick?

**Comment by patrickpereira** [comment]
I'm having issues as well in my sidemenu app after logout:

The nav cycle is: 

this.rootPage = StartPage -> nav.push(LoginPage) -> nav.setRoot(AppPage) -> nav.setRoot(StartPage) -> nav.push(LoginPage)

So on the 2nd run reaching the LoginPage, I can see the page perfectly but nothing is clickable or responsive, like there's an invisible layer on top. Been trying to inspect for it, but haven't been able to find anything.

For now my "ugly" work around is to use location.reload(); in my logout function, but would have preferred to just be able to setRoot instead.

**Comment by felipereis** [comment]
In ionic1 we can use tag ```tabs-item-hide```, It would be nice to see this in Ionic2.

**Comment by adamdbradley** [comment]
This sounds similar to https://github.com/driftyco/ionic2/issues/621

@patrickpereira are there any JS errors? Do you see an element with the css class `.click-block` anywhere in the page?

**Comment by adamdbradley** [comment]
Also, I use this app for navigation testing. Are you able to recreate the issue with this testing app? https://github.com/driftyco/ionic2/tree/master/ionic/components/nav/test/basic

thanks

**Comment by patrickpereira** [comment]
@adamdbradley yes the <div class="click-block"></div> is there and there no JS errors

**Comment by adamdbradley** [comment]
@patrickpereira With these steps `this.rootPage = StartPage -> nav.push(LoginPage) -> nav.setRoot(AppPage) -> nav.setRoot(StartPage) -> nav.push(LoginPage)`

Do they all happen from user clicks? Or are they programmically set one after another? I'm trying to figure out how to reproduce your issue. The actual problem is that the click block isn't being told that a transition has completed.

**Comment by patrickpereira** [comment]
They all happen within functions that gets triggered by user clicks, and only one nav interaction per user click. 

One of the clicks trigger a http request, where the nav.setRoot is then triggered when the promise is resolved. The logout event erases the the user in sqlite and then sets the root back to StartPage.

**Comment by adamdbradley** [comment]
@patrickpereira I added an e2e test in the ionic2 repo here: https://github.com/driftyco/ionic2/tree/master/ionic/components/nav/test/basic

I added in a path that recreates your steps like so:

```
this.rootPage = FirstPage
nav.push(PrimaryHeaderPage)
nav.setRoot(AnotherPage)
nav.setRoot(FirstPage)
nav.push(PrimaryHeaderPage)
```

I tested in the browser and iOS simulator, but I'm still unable to get the click block to stay open. Do you also have any routes setup with the angular2 router? Are there any additional options being passed to each method, like enabling animations for setRoot calls?

**Comment by jimmyrogue** [comment]
@patrickpereira thanks 
location.reload() works for me

@richardshergold  may be you can try location.reload()?

**Comment by adamdbradley** [comment]
Since alpha.37 you should be able to get a reference to the parent nav controller of the tabs and use setRoot to reset the entire app's navigation:

https://github.com/driftyco/ionic2/blob/54e40da9adbfac59601bc8d770dad0a702895eb0/ionic/components/tabs/test/advanced/index.ts#L78
