### ISSUE TITLE
Not all item lines showing up on iOS simulator

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#629]
From https://github.com/driftyco/ionic2/issues/622 @doabit

![image](https://cloud.githubusercontent.com/assets/452425/11347833/ce7ecaf4-91e8-11e5-9df2-1e9be0047046.png)

**Comment by adamdbradley** [comment]
@doabit was the simulator being scaled at all?
![image](https://cloud.githubusercontent.com/assets/452425/11348023/ab4b2a36-91e9-11e5-88bc-0f9b8467bccc.png)

**Comment by doabit** [comment]
@adamdbradley Thanks, you're right, scale to 75% or 100% looks well.

**Comment by adamdbradley** [comment]
What does your markup look like? Are you using `<button ion-item (click)="doSomething()>`?

**Comment by doabit** [comment]
I followed http://ionicframework.com/docs/v2/getting-started/tutorial/, and only modified app/list.js 

```javascript
import {IonicApp, Page, NavController, NavParams} from 'ionic/ionic';

import {ItemDetailsPage} from '../item-details/item-details';

@Page({
  templateUrl: 'app/list/list.html'
})
export class ListPage {
  constructor(app: IonicApp, nav: NavController, navParams: NavParams) {
    this.nav = nav;

    // If we navigated to this page, we will have an item available as a nav param
    this.selectedItem = navParams.get('item');

    this.icons = ['flask', 'wifi', 'beer', 'football', 'basketball', 'paper-plane',
    'american-football', 'boat', 'bluetooth', 'build'];

    this.items = [];
    for(let i = 1; i < 11; i++) {
      this.items.push({
        title: 'Item ' + i,
        note: 'This is item #' + i,
        icon: this.icons[Math.floor(Math.random() * this.icons.length)]
      });
    }
  }

  itemTapped(event, item) {

    // console.log('You selected:', item.title);

     this.nav.push(ItemDetailsPage, {
       item: item
     });
  }
}

```

**Comment by brandyscarney** [comment]
Changing the html markup from this:

```
<ion-item *ng-for="#item of items" (click)="itemTapped($event, item)">
  ...
</ion-item>
```

to this:

```
<button ion-item *ng-for="#item of items" (click)="itemTapped($event, item)">
  ...
</button>
```

Fixes the click issues. We need to update the starters (sidemenu & tutorial) to reflect this.

**Comment by brandyscarney** [comment]
I updated the above starters to use `<button ion-item>`. Please update your markup to the same and reopen this issue or open a new issue if there are still issues. Thanks for letting us know!

**Comment by doabit** [comment]
@bensperry Thanks, that works.
