### ISSUE TITLE
Handling framework updates

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic2#630]
There are multiple ways to handle updating the local framework project. 

Option 1) Use NPM
https://github.com/npm/npm/issues/3417

Currently we have this 

```
  "dependencies": {
    "ionic-framework": "2.0.0-alpha.35"
  },
```

Now if we switched that to 
```
"ionic-framework": "~2.0.0-alpha.35"
```

Running `npm update --save` will automatically bump the version in the package.json. 

Option 2) Use NPM-Check-Updates
https://www.npmjs.com/package/npm-check-updates 

We could wrap this in the CLI or export it from the framework side and create a dependency updater. Similar to `ionic lib` but more for npm. 

I'm more inclined to use npm-check-update since we could bump the package version more reliably. Thoughts?

**Comment by adamdbradley** [comment]
I'd rather not introduce another dependency, such as `npm-check-updates`. Let's go with the tilde `~` option. @mhartington can you update all of our starters?

**Comment by mhartington** [comment]
Updated
