### ISSUE TITLE
App gets stuck - and back button won't work.

### ISSUE THREAD

**Issue by richardshergold** [driftyco/ionic2#634]
I have a simple Tab application that is working pretty well.  I have noticed however that every so often one of the navigation stacks gets stuck and the back button doesn't do anything.  The other tabs all work ok at this point but the tab with the problem is then unusable until I kill the app and re-start.

The navigation stacks on my Tabs consist of a List and then a Detail Page - nothing more.

This is using alpha34 (not using alpha35 yet because of the keyboard-close issue I raised)

**Comment by brandyscarney** [comment]
I think this is related to this issue because I see the same thing happening: #641

**Comment by richardshergold** [comment]
Yes, this happens in my app too so I suspect that's what I was seeing.

**Comment by adamdbradley** [comment]
Closing because this may have been fixed with https://github.com/driftyco/ionic2/commit/f4d82f05ead5b79ed54bf8e5f7a244dd0e2f9fec
