### ISSUE TITLE
NavController insert breaks stack

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic2#638]
If you have a 2 view navigation stack, then use navController.insert and insert a new view, it breaks navigation. 

home -> detail, detail inserts info to index 1

```
  insertView(){
    this.nav.insert(Info, 1)
  }
```

Hit the back button from detail view, go to info, but now the back button is gone completely.
It should have a back button going back to home.

**Comment by mhartington** [comment]
Only an issue on iOS

**Comment by mhartington** [comment]
Looks like the back button is getting added to the DOM, but for some reason, isn't being displayed.

![screen shot 2015-11-24 at 2 57 29 pm](https://cloud.githubusercontent.com/assets/2835826/11378964/e70dee64-92bb-11e5-951f-760d8a5ba741.png)

**Comment by adamdbradley** [comment]
`show-back-button` isn't getting added when you insert a view on ios
