### ISSUE TITLE
bug: clicking close to edge of tab selects tab next to it

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#639]
The first few times it works fine but then when I click a certain spot you can see the tab is getting the ripple but it is selecting the next tab.

![zbltp78sma](https://cloud.githubusercontent.com/assets/6577830/11380537/ab8b6c28-92c4-11e5-8c08-5a1fa006320a.gif)

**Comment by adamdbradley** [comment]
this on the phone or android emulator?

**Comment by brandyscarney** [comment]
It's on the emulator. I don't have a nexus 6 to test on and can't reproduce it on my nexus 5 though, so maybe it's not a big deal.

**Comment by adamdbradley** [comment]
emulator is screwy and is no friend of mine
