### ISSUE TITLE
Don't stop CLI build on TS errors

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic2#646]
Right now the CLI won't build if webpack encounters any errors, we should emit TS errors but still build.

**Comment by sjclemmy** [comment]
I just wanted to clarify, `ionic serve` does do the build, but due to the errors it doesn't launch the watchable server.

**Comment by tlancina** [comment]
Ah yes you are right! But it still shouldn't kill the task, and should print the build stats.
