### ISSUE TITLE
SqlStorage is unable to select data from the existing sqlite table

### ISSUE THREAD

**Issue by gachen95** [driftyco/ionic2#647]
below is the code. test_tab is a table in planner.db

this.sql = new Storage(SqlStorage, {name: "planner.db", existingDatabase: true});
this.sql.query('select * from test_tab').then((data) => {
      alert('Your data is: ' + data);
    }), (errResult) => {
      alert('Unable to get item from SQL db:', errResult);
    });
	
	
After executing the above code, I didn't see it returned any data or errors on IOS.  Alert like Your data is:  or Unable to get item from SQL db: never popup-ed

Test project is https://github.com/gachen95/SqliteProject.
Thanks,

**Comment by mlynch** [comment]
Hey @gachen95, what version of ionic2 are you using? I fixed this a few days ago and would love you to try it.

**Comment by gachen95** [comment]
Hey @mlynch, I still got this issue. 

ionic info

Your system information:

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 2.0.0-alpha.31
Ionic CLI Version: 2.0.0-alpha.25
Ionic App Lib Version: 2.0.0-alpha.24
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X Yosemite
Node Version: v5.0.0
Xcode version: Xcode 7.1.1 Build version 7B1005

**Comment by frederikschubert** [comment]
Your ionic version is 2.0.0-alpha.31 whereas the newest version with @mlynch's fix is probably 2.0.0-alpha.37.

**Comment by gachen95** [comment]
yes, 2.0.0-alpha.37 works.

BTW, insert sql should like
this.sql.query("INSERT INTO test_tab(Column1) values('test_123456');");

Not like the current comments in sql.ts.

But insert couldn't return anything or any errors like unique index violation by below code
    this.sql.query("INSERT INTO test_tab(Column1) values('test_123456');").then((data) => {
      alert('Your data is: ' + data);
    }), (errResult) => {
      alert('Unable to get item from SQL db:', errResult);
    });  

By running above code, it didn't popup any alerts.

Thanks,

**Comment by mlynch** [comment]
Can you try with master (or the next release?)
