### ISSUE TITLE
v2 docs header being cut off

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#649]
On initial load you can't see the top of the left menu, or the search bar when you scroll down.

![image](https://cloud.githubusercontent.com/assets/452425/11409529/3fedc6f6-9386-11e5-88be-7d3590d88f98.png)

**Comment by adamdbradley** [comment]
Why was this closed: http://ionicframework.com/docs/v2/

**Comment by adamdbradley** [comment]
And on the staging site I'm not seeing the search bar

**Comment by perrygovier** [comment]
The search bar was removed until the search functionality is built. ETA 2 weeks.

I promoted the fix to production.

Safe to close now?
