### ISSUE TITLE
Change ion-radio-group to be an attribute of ion-list

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#650]
Change:
`<ion-radio-group>`

to:
`<ion-list radio-group>`

Also change css so it styles `ion-list` instead of `.list`.

**Comment by adamdbradley** [comment]
And remove adding `.list` to `ion-list`

**Comment by adamdbradley** [comment]
And hopefully only use `[radio-group]` as the selector rather than `ion-list[radio-group]` so we can keep the specificity low. And have a nice day.

**Comment by brandyscarney** [comment]
You have reached the limit of comments on this issue.

**Comment by adamdbradley** [comment]
:dancer:

**Comment by brandyscarney** [comment]
See this file for the new markup: https://github.com/driftyco/ionic2/blob/master/ionic/components/radio/test/basic/main.html
