### ISSUE TITLE
bug: Issue with opening and closing of modals

### ISSUE THREAD

**Issue by frederikschubert** [driftyco/ionic2#652]
Since the update to alpha-37 the opening and closing of modals takes three calls to `open()` to either open or close the modal. The events get fired but the modal only shows up after the third event.

**Comment by adamdbradley** [comment]
Sounds like ghost cilcks are getting through. Which browser/platform/device/version are your seeing this on?

**Comment by frederikschubert** [comment]
Latest Chrome, Mac OS X 10.11 and ionic-framework@2.0.0-alpha-37. I will test it in the other browsers as soon as I can.

**Comment by adamdbradley** [comment]
I'm not able to replicate the issue with this example: https://github.com/driftyco/ionic2/blob/master/ionic/components/modal/test/basic/index.ts

What does your markup look like?

**Comment by frederikschubert** [comment]
The issue exists only if the `<ion-overlay></ion-overlay>` is placed in the app.html file. I thought that this would be the right way. When I place the overlay in the file where I open the modal, the modal is opened and closed by the first click as expected.
So should I put an `<ion-overlay></ion-overlay>` in every view from which I open a modal?

**Comment by frederikschubert** [comment]
Ok I found out what is causing the problems. In my application I have 2 `<ion-nav>` elements to separate the navigation. Now when I place the `<ion-overlay>` in the file next to the second `<ion-nav>` where the modals are opened then everything works as expected.
But when I place it in the app.html next to the first `<ion-nav>` then the issue exists. I don't know if that is the expected behavior but I think it should be documented somewhere.

**Comment by adamdbradley** [comment]
So you have two ion-overlays in the app? Also, do your modals depend on a certain provider?

**Comment by frederikschubert** [comment]
I have one `<ion-overlay>` but two `<ion-nav>` elements. And I need to place the overlay next to the second nav when I want to open a modal from a page that is pushed on the second nav.

**Comment by adamdbradley** [comment]
With the new Modal API this will no longer be an issue, and will land in the alpha47 release: https://github.com/driftyco/ionic2/blob/master/CHANGELOG.md#modal-refactor
