### ISSUE TITLE
Webpack not work when build for android (CLI alpha 25)

### ISSUE THREAD

**Issue by nampdn** [driftyco/ionic2#656]
Currently, I follow the [Installation guide](http://ionicframework.com/docs/v2/getting-started/installation/) and create a ionic v2 project.
It works fine with `ionic serve`.
But when I debug or deploy it into real android device. There is two case:
- If I run `ionic run android -lcs`:
    - The message box pop-up and alert No connection to my laptop's IP. This box won't appear if I run it in Ionic 1 project.
    - Device and my laptop are connect to the same wifi.
    - What I have try to do? _Re-run command above again, but it has same problem. Then I notice that some service of webpack is not running when I use `ionic run android -lcs` command._
- If I run `ionic run android`:
    - Blank white screen appear.
    - I have try to get asset folder built (transpiled to bundle.js file) before run this command. Then run it again but same problem. I also check this [fag](http://ionicframework.com/docs/v2/faq/) for blank screen, it is well configured.

I'm confusing about the document, is it old date for lasted ionic2?

**Comment by nampdn** [comment]
Hi, I try to add crosswalk to project and it works fine.
It's about old android browser issue (Android 4.2.2 on Lenovo A680 device.)

**Comment by tlancina** [comment]
Should be fixed in https://github.com/driftyco/ionic2/commit/faee5fcdba76de026d83ffff8629bfd7916e9be3. Livereload was a separate issue that was fixed in the CLI in a recent release.
