### ISSUE TITLE
Making searchbar.ts template a form

### ISSUE THREAD

**Issue by dorontal** [driftyco/ionic2#661]
Right now when using <ion-searchbar> (ionic2/ionic/components/searchbar/searchbar.ts) in a cell phone the virtual keyboard does not disappear upon form submission (e.g. when clicking the icon on the bottom right of the virtual keyboard in Android).

It would be useful if we could do something like
    `<ion-searchbar (submit)="onSubmit()"></ion-searchbar>`
when we want to grab the search query's value only when the Enter key is pressed or when one clicks the submit button in the virtual keyboard.

The way it is now, one has to go through hoopla to make the virtual keyboard disappear on a cell phone - e.g. touch any part of the app other than the searchbar input field, to defocus it, which causes the keyboard to disappear.  There is no other way to make the keyboard disappear.

The only way the searchbar's query value can be grabbed right now is via data-binding, or by capturing the (keyup) event on the searchbar and testing for Enter (e.g. `<ion-searchbar (keyup)="onKeyup($event)"></ion-searchbar>`), which is good for real-time filtering of data already available, but sometimes we just want to type a whole search query in while our app does nothing, and only do a (typically expensive) search when either 'Enter' key is pressed or the submit button on the virtual keyboard is clicked - there is no way to do that today with this searchbar.

One way to solve this, perhaps, is to make the template enclosed as a `<form>` rather than as a `<div>`.

**Comment by dorontal** [comment]
Hmm.. just solved the issue - with no change required to searchbar.ts.  It involved
1) using (keyup.enter) event instead of just (keyup) - keyup.enter does get fired when the cell phone virtual keyboard submit button is pushed, but keyup does not fire.
2) in order to hide the keyboard, a hack is to add `document.activeElement.blur()` as the last line of the function that was handling (keyup.enter), since the active element is the input field of the searchbar at the time and since blurring it automatically hides the virtual keyboard.

**Comment by adamdbradley** [comment]
What version are you using? Also, you can inject `Keyboard`, and on that instance there's a `close()` method.

**Comment by dorontal** [comment]
Using Ionic Framework v 2.0.0-alpha.37.  Thanks for the note on Keyboard injection.
