### ISSUE TITLE
CLI: don't bundle on every build

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic2#665]
Should maybe do it if bundle in webpack config doesn't exist, but it adds unnecessary startup time.

**Comment by nampdn** [comment]
Currently, I couldn't find any command to get the webpack run the buiding process for android build. If I want to build for an android, I have to run `ionic serve` before, then `ionic run android`. This mean I can't run livereload (`ionic run android -l`) on android device.

**Comment by tlancina** [comment]
You can now opt out using the `-b` or `--nobundle` flag for commands that bundle before running by default.
