### ISSUE TITLE
Method/example on how to dynamically change the back button text

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#672]
Defaults to "Back", can be config'd. But you should also be able to change it per every page, and dynamically update it. For example, iOS Messages will update `< Messages` to `< Messages (1)` when a message comes in.

**Comment by adamdbradley** [comment]
This is possible now and should be documented: https://github.com/driftyco/ionic2/blob/master/ionic/components/nav/test/basic/index.ts#L170

**Comment by mhartington** [comment]
Added via be4601319b5f4543c68409c4366ce32eba6008ee

Live at:
http://ionicframework.com/docs/v2/api/components/nav/ViewController/
