### ISSUE TITLE
bug: clicking on input throwing error

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#675]
Clicking in an input field when it is already selected throws the following error:

```
Uncaught TypeError: Cannot read property 'runOutsideAngular' of undefined
```

**Comment by adamdbradley** [comment]
Any input? Stand alone or one that's in ion-input?

**Comment by brandyscarney** [comment]
Sorry, so far I confirmed on the e2e tests: floating-labels and fixed-inline-labels
