### ISSUE TITLE
MD: inputs should be highlighted

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#677]
Refer to: https://www.google.com/design/spec/components/text-fields.html

![screen shot 2015-12-01 at 11 55 20 am](https://cloud.githubusercontent.com/assets/6577830/11507585/ab3b7282-9822-11e5-9872-0d016d728301.png)

**Comment by adamdbradley** [comment]
something must have broke, cuz it at one point it was highlighting. The css class `has-focus` gets added to `ion-input` when it...has focus. So something in the css might need a look.
