### ISSUE TITLE
MD: inputs should have success/error highlighting

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#678]
![9914f97f2de4e723b833f175785bb85c0ecbb587](https://cloud.githubusercontent.com/assets/6577830/11507625/e53d21ec-9822-11e5-8f4d-35944919247b.png)

**Comment by brandyscarney** [comment]
Looking at the sass variables they need to be renamed so MD is in them and it comes after text-input. Do that.

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5052
