### ISSUE TITLE
Add a gulp task for publishing new releases

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#680]
Currently we have to manually update the CDN with the latest code, would be nice to do all of this automagically. Steps for release:

1. update package.json version
2. gulp src
3. npm publish
4. copy contents of ionic2/dist folder to ionic-v2.0.0/
5. add ionic2/README.md and ionic2/package.json to this folder
6. zip this folder and move the zip inside of it
7. copy to https://github.com/driftyco/ionic-code/tree/gh-pages/2.0.0
8. commit & push this to gh-pages

**Comment by perrygovier** [comment]
Note, this should be done by a new file in `scripts/cdn/release.sh` and called by https://github.com/driftyco/ionic2/blob/master/scripts/ci/deploy.sh#L34

**Comment by agnellvj** [comment]
can we get git tags for the releases too?

**Comment by tlancina** [comment]
The gulp task is done, although I think we may want to move this to a full release script that integrates with CircleCI.

Going to close for now, I've created issues for the git tags (https://github.com/driftyco/ionic2/issues/850) and the CircleCI script.
