### ISSUE TITLE
docs(api): version dropdown defaults to nightly, but doesn't update url

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic2#691]
**nightly** is selected by default, but if we click on any section, the url will be: `http://ionicframework.com/docs/v2/api/components/searchbar/SearchBar/`

This seems to load the latest stable version, instead of the nightly version, even though nightly is selected. Also, the only way update the url to `docs/v2/nightly` is to switch to an older version, and then select nightly again.

**Comment by mhartington** [comment]
There is no nightly dir anymore. Nightly builds now are the default and sit at the top level v2 directory.
