### ISSUE TITLE
Question: something similar to LoggedInOutlet

### ISSUE THREAD

**Issue by vadimpopa** [driftyco/ionic2#692]
I would want to implement in an Ionic2 app this check: https://github.com/auth0/angular2-authentication-sample/blob/master/src/app/LoggedInOutlet.ts, so will only let authenticated users access the home. But I've seen that ion-nav has the NavRouter which extends the RouterOutlet. So wondering what could work or if is there any other better approach. Here some thoughts:

1. Extend RouterOutlet like guys did in that blog, and have in the app 2 directive LoggedInRouterOutlet & Ion-Nav
2. Or extend NavRouter and on same Ion-Nav directive.

**Comment by mhartington** [comment]
Right now, we're not setup to use the new router, so going down this path is not recommended.

Another option instead is to create an Auth provider that handles the state of your authentication, then before you push to the home page, check against that auth service. If it returns true, push page, if not, don't.

**Comment by Luchillo** [comment]
I'm doing it the other way around, i push and in the constructor i check for the accessToken in `kv` table in SqLite.

**Comment by vadimpopa** [comment]
@mhartington  Yes, that's how I did: auth provider/class + nav controller. Thanks anyways for suggesting.
