### ISSUE TITLE
Default Xcode Project name incorrect?

### ISSUE THREAD

**Issue by dmackerman** [driftyco/ionic2#693]
I did an `ionic build ios`, and I think the name of the Xcode Project is hardcoded. See screenshot:

![s](https://dl.dropboxusercontent.com/spa/pkr1d5uhq1t8wz1/6l-awsd4.png)

**Comment by mhartington** [comment]
Hmm, shouldn't be hardcoded. What do you have for a name in config.xml?

**Comment by dmackerman** [comment]
Ah, yeah. Maybe that gets set by default when you create the project. Changed it, removed the platform, and all is well.
