### ISSUE TITLE
EXCEPTION: Hammer.js is not loaded, can not bind swipe event

### ISSUE THREAD

**Issue by wulfsolter** [driftyco/ionic2#696]
Trying to add swipe events to an image like 
```<img (swipe)="swipe()" (click)="click()" src="{{imgPath}}"```

and getting error of
```EXCEPTION: Hammer.js is not loaded, can not bind swipe event```

Have tried adding Hammer to top of the page's JS and main app.js to no avail
```import {Hammer} from 'ionic/gestures/hammer';```

**Comment by kitkimwong** [comment]
Same problem here +1

**Comment by wulfsolter** [comment]
I downloaded Hammer to `www/lib/Hammer.js/hammer.min.js` and added it to index.html with `  <script src="lib/Hammer.js/hammer.min.js"></script>` to work around
