### ISSUE TITLE
CLI: build the app prior to ionic upload

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#700]
If the user uploads an app without generating the build (`ionic build`, `ionic serve`, etc) and then they upload it to View they will get a white screen.

**Comment by nampdn** [comment]
This also happen with `ionic run [platform] -lcs` (1 week ago)

**Comment by tlancina** [comment]
This was added in the last release, and can be opted out with the `-b` or `--nobundle` flags.
