### ISSUE TITLE
(concern) Inconsistent use of `detail-push` directive

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#706]
May be not an issue but a bit confusing that `detail-push` directive is applicable to both [`<ion-item-sliding>`](https://github.com/driftyco/ionic2/blob/master/ionic/components/item/test/sliding/main.html#L38) and [`<ion-item>`](https://github.com/driftyco/ionic2/blob/master/ionic/components/item/test/sliding/main.html#L26) - see examples by following links.

Would not it be better to require to specify it just on `ion-item` level? (*as `ion-item-sling` can be missing*)

**Comment by adamdbradley** [comment]
Yes you're right, `detail-push` should only go on `ion-item`. Do we have it documented somewhere to put it on ion-item-sliding?

**Comment by astec** [comment]
I have not seen `<ion-item-sliding>` to be documented so am using the test samples as a documented examples. Probably it make sense to document it at [Lists](http://ionicframework.com/docs/v2/components/#lists) section.

Don't know how directives are working but may be it should throw an error if applied in wrong place.

Also [difference between `<button ion-item>` & `<ion-item>`](https://forum.ionicframework.com/t/ion-list-button-ion-item-vs-ion-item/38763) looks unclear.

**Comment by adamdbradley** [comment]
Sure sounds good. @mhartington would you go further in depth about using a button for ion-item?

Related: https://github.com/driftyco/ionic2/issues/294
cc @drewrygh
