### ISSUE TITLE
(broken) NavController.parent.parent is undefined in tabs page

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#714]
EXCEPTION: TypeError: **Cannot read property 'setRoot' of undefined**

```
constructor(private nav: NavController){}

signOut(){
        this.nav.parent.parent.setRoot(LoginPage, null, {animate: true, direction: 'back'});
}
```
Before it worked - trying to navigate from tab page to a login screen (*change root from tabs to login*).

By the way, how about to have a `nav.rootNav` property?

**Comment by adamdbradley** [comment]
Sure having a `root` property is a good idea, I can add that in. For `parent` being null I'm not sure what that could be, and going off of this example I'm not having any issues: https://github.com/driftyco/ionic2/blob/master/ionic/components/tabs/test/advanced/index.ts#L78

**Comment by astec** [comment]
@adamdbradley Thanks, I'll check it later today.

**Self-education question**: Taking into account that `@Optional() navCtrl: NavController` is optional for Tabs would it better to check that this.parent is presented?

Update https://github.com/driftyco/ionic2/commit/5793716b67d5c9f72d0b397b95791573e6327a69#diff-a08127cd672c2aeb9e167a062116743eR254 with:
```
get rootNav() {
   let nav = this.parent;
   if (nav) {
      while (nav.parent) {
        nav = nav.parent;
      }
   }
   return nav;
}
```

Or just to call rootNav of a NavController?
```
get rootNav() {
   let nav = this.parent;
   if (nav) {
      nav = nav.rootNav;
   }
   return nav;
}
```

**Comment by astec** [comment]
It works now after updating and rebuilding ionic-framework. Probably it was somehow linked to my dev environment. Thanks.
