### ISSUE TITLE
evaluating 'l_keyedAccess5.Entry' Error after enableSlidingItems - alpha40

### ISSUE THREAD

**Issue by richardshergold** [driftyco/ionic2#715]
I'm getting a whole bunch of errors (in the console these occur after the line enableSlidingItems debug msg).

I can't really fathom out what's causing it - is it some error with <ion-item-sliding> ?

[Debug] enableSlidingItems (app.bundle.js, line 70557)
[Log] EXCEPTION: TypeError: undefined is not an object (evaluating 'l_keyedAccess5.Entry') in [null] (app.bundle.js, line 48729)
[Error] EXCEPTION: TypeError: undefined is not an object (evaluating 'l_keyedAccess5.Entry') in [null]
	logError
	logGroup
	call
	(anonymous function)
	_notifyOnError
	onError
	run
	(anonymous function)
	run
	(anonymous function)
	(anonymous function)
	tryCatcher
	next
	_next
	next
	(anonymous function)
	run
	_notifyOnTurnDone
	(anonymous function)
	zoneBoundFn
[Error] ORIGINAL EXCEPTION: TypeError: undefined is not an object (evaluating 'l_keyedAccess5.Entry')
	logError
	call
	(anonymous function)
	_notifyOnError
	onError
	run
	(anonymous function)
	run
	(anonymous function)
	(anonymous function)
	tryCatcher
	next
	_next
	next
	(anonymous function)
	run
	_notifyOnTurnDone
	(anonymous function)
	zoneBoundFn
[Error] ORIGINAL STACKTRACE:
	logError
	call
	(anonymous function)
	_notifyOnError
	onError
	run
	(anonymous function)
	run
	(anonymous function)
	(anonymous function)
	tryCatcher
	next
	_next
	next
	(anonymous function)
	run
	_notifyOnTurnDone
	(anonymous function)
	zoneBoundFn
[Error] detectChangesInRecordsInternal
detectChangesInRecords@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:32454:49
runDetectChanges@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:32431:37
_detectChangesContentChildren@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:32516:35
runDetectChanges@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:32432:44
_detectChangesContentChildren@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:32516:35
runDetectChanges@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:32432:44
_detectChangesInViewChildren@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:32523:35
runDetectChanges@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:32435:43
_detectChangesContentChildren@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:32516:35
runDetectChanges@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:32432:44
_detectChangesInViewChildren@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:32523:35
runDetectChanges@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:32435:43
_detectChangesInViewChildren@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:32523:35
runDetectChanges@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:32435:43
_detectChangesContentChildren@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:32516:35
runDetectChanges@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:32432:44
_detectChangesInViewChildren@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:32523:35
runDetectChanges@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:32435:43
_detectChangesInViewChildren@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:32523:35
runDetectChanges@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:32435:43
detectChanges@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:32420:90
detectChanges@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:32665:87
file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:49973:98
forEach@[native code]
apply@[native code]
call@[native code]
call@[native code]
forEach@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:1152:21
tick@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:49973:46
file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:49898:128
run@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:8373:23
file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:40254:48
run@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:40203:44
file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:49898:103
file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:10446:57
tryCatcher@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:11501:37
next@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:11410:24
_next@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:17784:35
next@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:17745:20
file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:40096:84
run@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:8373:23
_notifyOnTurnDone@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:40096:24
file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:40268:62
zoneBoundFn@file:///var/mobile/Containers/Bundle/Application/6E5E038E-8243-4114-BF67-19179507ED9B/Support%20Rota.app/www/build/js/app.bundle.js:8346:23
	logError
	call
	(anonymous function)
	_notifyOnError
	onError
	run
	(anonymous function)
	run
	(anonymous function)
	(anonymous function)
	tryCatcher
	next
	_next
	next
	(anonymous function)
	run
	_notifyOnTurnDone
	(anonymous function)
	zoneBoundFn
[Error] ERROR CONTEXT:
	logError
	call
	(anonymous function)
	_notifyOnError
	onError
	run
	(anonymous function)
	run
	(anonymous function)
	(anonymous function)
	tryCatcher
	next
	_next
	next
	(anonymous function)
	run
	_notifyOnTurnDone
	(anonymous function)
	zoneBoundFn
[Error] _Context {element: <button class="item disable-hover">, componentElement: null, context: TodayCtrl, locals: Object, injector: Injector, …}
	logError
	call
	(anonymous function)
	_notifyOnError
	onError
	run
	(anonymous function)
	run
	(anonymous function)
	(anonymous function)
	tryCatcher
	next
	_next
	next
	(anonymous function)
	run
	_notifyOnTurnDone
	(anonymous function)
	zoneBoundFn

**Comment by richardshergold** [comment]
@adamdbradley I just noticed your latest commit.  Does that fix the problem I have?

**Comment by adamdbradley** [comment]
I'm not sure the change to enableSlidingItems is the problem. Within your `TodayCtrl ` component, can you comment out most of the lines and see if anything changes? It almost looks like something in there is causing an error.

**Comment by richardshergold** [comment]
Ok, I'll try that and let you know.

**Comment by richardshergold** [comment]
@adamdbradley I fixed it - you were right, I had a bad line of code in that controller. You can close this one.  Thanks!
