### ISSUE TITLE
Ensure avatar/thumbnail/icon sizes have min-width/height

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#719]
Make sure that when if an image or icon is not in the element, or it hasn't loaded yet, the wrapping element doesn't change size. 

Goal is to reduce jank from having elements re-adjust after an image/icon downloads. The wrapping container should already lock in it's size relative to its siblings. Best test is to inspect elements and delete the inner `<img>` and make sure there nothing moves after it's deleted.

**Comment by brandyscarney** [comment]
Confirmed deleting `img` from inside of an `avatar` and `thumbnail` does not cause the item to move at all. Checked the icons by removing the `content` property and the only jank was when the icon was large, so I'll look into fixing that.
