### ISSUE TITLE
Update "$ ionic start --v2 tabs" to use lates version of framework (angular2@52)

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#723]
@adamdbradley , @tlancina Any chance you guys can update the sample tabs project to use latest changes in framework (*e.g. latest fixes, TS compiling, angular2@52 case-sensitivity*) before weekend?

```$ ionic start --v2 tabs```

At the moment I'm having problem to do `ionic serve`: see https://github.com/driftyco/ionic2/issues/722#issuecomment-163887109

Some people have just weekends to work on side projects and would be pity to miss one. If not then my wife would be happy.

**Comment by vamsivarikuti** [comment]
@adamdbradley @tlancina 
Now we can update to Angular2@Beta.0

**Comment by astec** [comment]
@vamsivarikuti It's already updated to beta.0 in git/master but not in https://www.npmjs.com/package/ionic yet.
