### ISSUE TITLE
Popup close with timeout messes fast interactions

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic2#726]
Hi, i'm using the popup as an `improvised busy indicator` so i try to not use the modal, i'm having an issue with the `close` function, i show the modal (or at least try to) before a `http` call, i got the response too fast and then i call again the `showAlert` function, which should call `get` and `close` before showing the popup, but depending on the timeout `time`, either it try to close before the first one exist thus not closing the first and showing both, one over the other, or it closes after the second one instantiates and closes both.

With this `close` approach this behavior will fluctuate accordingly with the performance of the app:

>     closeDialog() {
      var this_ref = this;
      if (this.dialog) 
      {
        setTimeout(() => {
          var dialog = this_ref.popup.get();
          dialog.close && dialog.close();
          this_ref.dialog = null;
        }, 200);
      };
    }

>     showProgress(args) {
      this.closeDialog();
      args.title = args.title || 'Descargando...';
      args.subTitle = args.subTitle || '';
      args.template = args.template || '<i class="fa fa-refresh fa-spin fa-3x"></i>';
      this.dialog = true;
      return this.popup.alert({
        title: args.title,
        subTitle: args.subTitle,
        template: args.template,
        cssClass: 'progress',
        okText: '',
        okType: 'primary'
      });
    }

>     showAlert(args) {
      this.closeDialog();
      args.title = args.title || 'Error obteniendo datos';
      args.subTitle = args.subTitle || '';
      args.template = args.template || '';
      this.dialog = true;
      return this.popup.alert({
        title: args.title,
        subTitle: args.subTitle,
        template: args.template,
        cssClass: 'alert',
        okText: 'Cerrar',
        okType: 'primary'
      });
    }

In code i call `showProgress()` before the `http` call and on error or success i call `showAlert` which should close the first one even if it's still not in the DOM, and then show it's own popup, but the need for that timeout is messing the flow of this popups.

**Comment by adamdbradley** [comment]
Related: https://github.com/driftyco/ionic2/issues/793

**Comment by adamdbradley** [comment]
With the new Alert API this will no longer be an issue, and will land in the alpha47 release: https://github.com/driftyco/ionic2/blob/master/CHANGELOG.md#alert-refactor

**Comment by Luchillo** [comment]
@adamdbradley I don't see how the new Alert fixes this issue, i still have to `push (present)` manually to the nav component, and it will take some time before i can `pop` it out of the navStack, as i see it, it still depends on the push to the navController so if a dialog already exist forces some delay with `setTimeout()` at the time to call `pop()` to close the last alert.
