### ISSUE TITLE
No SCSS compilation on build?

### ISSUE THREAD

**Issue by dmackerman** [driftyco/ionic2#728]
Ionic CLI: `2.0.0-beta.11`

In the latest version, I generated a new project with `ionic start blahblah --v2`, and ran an `ionic serve`. It doesn't appear that a `css` folder is being generated under `build`.

Based on the change log instructions, I added these lines to `index.html`.

```html
<link ios-href="build/css/app.ios.css" rel="stylesheet">
<link md-href="build/css/app.md.css" rel="stylesheet">
```

But I'm not seeing any css folder?
![whoops](https://dl.dropboxusercontent.com/spa/pkr1d5uhq1t8wz1/8utxp2yc.png)

Am I missing something?

**Comment by mhartington** [comment]
With the latest release, we brought gulp back to handle sass.
So you'll need to update your package.json, add the gulp file and content of the `ionic.config.js` to your project form the base. 

https://github.com/driftyco/ionic2-app-base

https://github.com/driftyco/ionic2/blob/master/CHANGELOG.md#steps-to-upgrade-to-alpha42

**Comment by dmackerman** [comment]
I added the gulpfile, installed the depdencies, and ran `ionic serve`. Still no `css` folder.

I had to run `gulp build` manually to get it to compile. I'm guessing this isn't the expected behavior... :smile:

**Comment by mhartington** [comment]
Run gulp sass watch to watch and compile the sass (will be part of ionic serve in later release)

**Comment by Luchillo** [comment]
Gulp sass isn't using the `app.variables.scss` file in alpha.42, can't override color variables.
