### ISSUE TITLE
Update getting started to use beta CLI

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#733]
Update any uses of alpha CLI to beta: http://ionicframework.com/docs/v2/getting-started/installation/

**Comment by aanand1008** [comment]
@brandyscarney I have upgraded ionic to beta version. I have used below commands
ionic start cutePuppyPics --v2
cd cutePuppyPics
ionic serve

Then I am getting below error : 
====error start=====
G:\src\ionic2projects\ionicTest\cutePuppyPics\node_modules\.bin\gulp:4
case `uname` in
^^^^

SyntaxError: Unexpected token case
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
====error end =====

ionic serve is able to open web page even though getting above error. But it is showing only plain text without any styles and formats.

**Comment by brandyscarney** [comment]
Can you open a new issue for this? This issue is just for updating the documentation.

**Comment by mhartington** [comment]
Updated http://ionicframework.com/docs/v2/getting-started/installation/

Closing.

**Comment by brandyscarney** [comment]
:shipit:
