### ISSUE TITLE
Getting syntax error after upgrading to beta version

### ISSUE THREAD

**Issue by aanand1008** [driftyco/ionic2#735]
I have upgraded ionic to beta version. I have used below commands
ionic start cutePuppyPics --v2
cd cutePuppyPics
ionic serve

Then I am getting below error : 
====error start=====
G:\src\ionic2projects\ionicTest\cutePuppyPics\node_modules.bin\gulp:4
case uname in
^^^^

SyntaxError: Unexpected token case
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:413:25)
at Object.Module._extensions..js (module.js:452:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Function.Module.runMain (module.js:475:10)
at startup (node.js:117:18)
at node.js:951:3
====error end =====

ionic serve is able to open web page even though getting above error. But it is showing only plain text without any styles and formats.

**Comment by brandyscarney** [comment]
Thanks for the issue! We're looking into this currently, but in the meantime you can get this up and running by installing gulp:

```
npm install -g gulp
```

and running `gulp sass` to build the Sass, or `gulp sass watch` to watch for changes. Then in another terminal window you can run `ionic serve`.

**Comment by tlancina** [comment]
Also make sure to comment out the beforeServe hook in `ionic.config.js` for now :)

**Comment by aanand1008** [comment]
@brandyscarney  after running  gulp sass, It is showing webpage with proper style and format even after getting same syntax error.

@tlancina, I have commented beforeServe for now. Syntax error is not coming now.

Thanks both of you.

**Comment by tlancina** [comment]
Should be fixed in https://github.com/driftyco/ionic2-app-base/commit/8b1d2a53055a3963254375cfc167870a0d37cb33. Let us know if you're still having issues, thanks!
