### ISSUE TITLE
Slides property list are different in component and api document

### ISSUE THREAD

**Issue by 3dd13** [driftyco/ionic2#737]
the property list are different. the api one is correct, but I have no ability to update the component one, only the api page allows me to "Improve this doc"

http://ionicframework.com/docs/v2/components/#slides
http://ionicframework.com/docs/v2/api/components/slides/Slides/

**Comment by drewrygh** [comment]
hey @3dd13, just updated this section. Thanks for pointing this out!

**Comment by drewrygh** [comment]
Also, I'll be adding "Improve this Doc" links to the components section soon. [Here's the link](https://github.com/driftyco/ionic-site/edit/master/docs/v2/components/index.md) to edit that section in case you find any more things that are outdated before I get it live
