### ISSUE TITLE
API demos

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic2#739]
##### Sections that still need demos:
- [x] app
- [x] attr
- [x] events
- [ ] icon
- [x] idref
- [ ] input
- [ ] item
- [ ] itemsliding
- [ ] nav
- [ ] navbar
- [x] navrouter
- [ ] navcontroller
- [x] radiobutton
- [x] radiogroup
- [ ] searchbar
- [x] segment
- [x] segmentbutton
- [x] slides
- [ ] tab
- [ ] tabs
- [ ] viewcontroller

##### TBD
- [ ] animation
- [x] content
- [x] ~~ionicproviders~~
- [x] ~~ionic_directives~~
- [ ] keyboard (should be made private, eventually moved to "Platform" docs)
- [ ] refresher (icon is currently broken)
- [x] scroll

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5047
