### ISSUE TITLE
Using attr disabled on a button does not work

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#741]
Using this:

`<button [attr.disabled]="true ? '' : null">`

doesn't work because the `button-disabled` class isn't working, currently you have to use:

`<button [class.button-disabled]="true">`

**Comment by drewrygh** [comment]
Does `disabled` work as expected when it isn't set conditionally `<button disabled>`?

**Comment by brandyscarney** [comment]
No, we changed it to a class but we aren't adding that class when the attribute is applied.

**Comment by brandyscarney** [comment]
Added the `button-disabled` class when the `disabled` attribute is on the element. This is part of a larger issue where dynamic attributes on the buttons aren't applying any of the classes, so I created a separate issue to track that: #742
