### ISSUE TITLE
<ion-toggle> & <ion-radio> do not get focus on TAB keypress

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#745]
CLI v2.0.0-beta.12

**Comment by brandyscarney** [comment]
I added the ability to focus them on tab press but there is still a lot of logic that needs to be added such as using up/down arrows to move between radios. Leaving this open for that. 

https://github.com/angular/angular/blob/master/modules/angular2_material/src/components/radio/radio_button.ts

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5046
