### ISSUE TITLE
Android tabs are being placed at the bottom

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#746]
This is happening on e2e & conference app.

**Comment by ronanjia** [comment]
oh no, is this accidentally a bug?
i should keep this special "android bottom tabs" version!   =D

**Comment by brandyscarney** [comment]
Yes, but you can override it by placing the following on `ion-tabs`:

```
<ion-tabs tabbarPlacement="bottom">
```

**Comment by ronanjia** [comment]
This is what I'm looking for, thank you!
