### ISSUE TITLE
Closing the custom animation modal errors every other time

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#749]
[http://localhost:8000/dist/e2e/modal/basic/](http://localhost:8000/dist/e2e/modal/basic/)

1. Click "Modal: Custom Animation"
2. Click "Close"
3. Repeat until you see this error (should be every other try):

```
EXCEPTION: Error during evaluation of "click"BrowserDomAdapter.logError @ angular2-all.umd.js:29415BrowserDomAdapter.logGroup @ angular2-all.umd.js:29425ExceptionHandler.call @ angular2-all.umd.js:4473(anonymous function) @ angular2-all.umd.js:12469NgZone._notifyOnError @ angular2-all.umd.js:13103errorHandling.onError @ angular2-all.umd.js:13001run @ angular2-polyfills.js:141(anonymous function) @ angular2-all.umd.js:13016NgZone.run @ angular2-all.umd.js:12965outsideHandler @ angular2-all.umd.js:28140run @ angular2-polyfills.js:138zoneBoundFn @ angular2-polyfills.js:111
angular2-all.umd.js:29415 ORIGINAL EXCEPTION: TypeError: this.modal.get(...).close is not a function
...
```

**Comment by adamdbradley** [comment]
The close method is added to the instance after the animation has ended, so if you're too fast in closing the modal before it's done opening you'll get this error. Also, the test page's close method doesn't do any checking if the modal exists, which is where the error is coming from.

**Comment by adamdbradley** [comment]
Related: https://github.com/driftyco/ionic2/issues/793
