### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by massilva** [driftyco/ionic2#752]
Hi!

I followed the getting-started tutorial:
http://ionicframework.com/docs/v2/getting-started/installation/

When I run the command:
ionic serve

throw exception:
ReferenceError: Promise is not defined

And crash the layout.
The same happens when I tested the app:
https://github.com/driftyco/ionic-conference-app

How I fix it?
tk

**Comment by mhartington** [comment]
@massilva could you provide the output from `ionic info`? 
It sounds like a CLI issue

**Comment by massilva** [comment]
Cordova CLI: 5.1.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic CLI Version: 2.0.0-beta.12
Ionic App Lib Version: 2.0.0-beta.6
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.3 LTS 
Node Version: v0.12.9

**Comment by mhartington** [comment]
Hmm, could be the node version. Would you mind upgrading to node 4.2? Then reinstall the cordova and ionic beta cli

**Comment by tlancina** [comment]
Yeah looks like it might be https://github.com/sindresorhus/gulp-autoprefixer/issues/45.

**Comment by tlancina** [comment]
Actually I'm not sure, since I believe Promises are available in node 0.12. 

@massilva could you post a stack trace of the error?

**Comment by gsanjeevkumar** [comment]
@tlancina i read in a different post that I could not use new Promise(request, response) ... pattern any more ... but try and use $q. Actually I was using the "new Promise(.." in a .catch(function(err){...}

for now its working but wanted to correct my knowledge.... pls let me know

**Comment by tlancina** [comment]
@gsanjeevkumar is this in your browser? You should be able to, since es6-shim is bundled as well: https://github.com/driftyco/ionic-conference-app/blob/master/webpack.config.js#L7.

**Comment by mhartington** [comment]
@gsanjeevkumar or @massilva, any updates?

**Comment by massilva** [comment]
Hi! @mhartington , 

I run:

**npm rebuild node-sass**

I started other app and work.

**Comment by mhartington** [comment]
Is this still an issue then or is this ok to close?

**Comment by gsanjeevkumar** [comment]
@mhartington as I mentioned earlier "for now its working". I don't know if this is a bug. Or I am doing something wrong. Let me know if I am doing it wrong by calle a "new Promise()..." within a ".catch(.."

Thanks for all your help!

**Comment by mhartington** [comment]
do you mind posting an example

**Comment by Ionitron** [comment]
Greetings @massilva!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
