### ISSUE TITLE
bug: Keyboard not closing on page transition

### ISSUE THREAD

**Issue by frederikschubert** [driftyco/ionic2#754]
When I click in a text input field the keyboard opens. Now when I `push` a new page on the navcontroller's stack the keyboard closes. However when I press on the menuToggle or back button, i.e. `pop` a page from the stack, the keyboard stays open.
I tried injecting the Keyboard and closing it onPageWillLeave but the function is not called when the keyboard is still open.

**Comment by 0xE282B0** [comment]
update: 
`onPageWillLeave` is working when clicking the back button but `this.keyboard.close()` does not.
When `document.activeElement.blur()` is added to `onPageWillLeave`, the Keyboard closes.
