### ISSUE TITLE
[hidden] on a button in a page executes on mouse movement in Browser

### ISSUE THREAD

**Issue by av2k** [driftyco/ionic2#755]
Hello,

on the current ionic v2 beta, on nav-menu navigation-style app, I have the following simple code for a page called AuthenticatorPage.

Expected behaviour: the code for the [hidden] directives is executed when the page is rendered or the programmer explicitely asks for a page refresh.

Encountered behaviour: by merely moving the mouse, the console fires countless log messages due to repeated execution of the code for the [hidden] directives.

In this example case the method is quickly executed, but methods that perform larger calculations could severely affect the performance of the application in the browser.

JS:
https://gist.github.com/anonymous/b792272ce96138aa9ab1

HTML:
https://gist.github.com/anonymous/b9d985d75f3ce4e77d69

Log output (excerpt of the messages that appeared when I just moved the mouse through the browser window):
https://gist.github.com/anonymous/061de3ca4e232da93108

$ ionic info

Your system information:

Cordova CLI: 5.4.1
Ionic Version: 2.0.0-alpha.42
Ionic CLI Version: 2.0.0-beta.12
Ionic App Lib Version: 2.0.0-beta.6
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4
Node Version: v5.1.0

Browser: current Safari

**Comment by adamdbradley** [comment]
So it looks like mousemove is doing change detections, but I'm not able to reproduce the issue. Do any other directives have a mousemove event? Did you use hammer gestures anywhere?

**Comment by av2k** [comment]
In contrast to my code, the demo code provided by the ionic directly accesses the attributes, which is probably why the issue was not noticed yet.

e.g.
https://github.com/driftyco/ionic2/blob/068f3ceb29fe1054eb750dab1a44de372ebfb439/demos/attr/main.html

I can reproduce the issue with the files I provided. There are no other hooks, directives or gestures involved.

To me it seems that the issue always happens but was not noticed because nothing shows up in the browser debug console if the variables are directly accessed. As I am a JS/ionic/ionic2 novice, I do not yet know where to look and for what.

**Comment by av2k** [comment]
Here is a picture of the call stack:
<img width="313" alt="lower part of the call stack" src="https://cloud.githubusercontent.com/assets/8684223/11868743/704aab4e-a4ba-11e5-8a7d-1634b57dddcd.png">
<img width="314" alt="upper part of the call stack" src="https://cloud.githubusercontent.com/assets/8684223/11868744/706e1214-a4ba-11e5-9fd0-4b9950b36ba3.png">


in JS:

  isTANActive() {
    debugger;
    console.log( 'isTanActive' );
    return true;
  }

In HTML I only activated one [hidden]="!isTANActive()"

**Comment by av2k** [comment]
An easy way to reproduce:

1. Start a new project
ionic start HIDDENTEST sidemenu --v2

2. Add a new button below the already existing primary button in getting-started.html, with only button and the [hidden]="isHidden()" directive

3. Add a function isHidden() { console.log( "calling isHidden" ); return false; } to getting-started.js


Result just by moving the mouse:

serve  /app/getting-started/getting-started.html
0     709712   log      Platform ready
1     709755   log      isHidden called
2     709760   log      isHidden called
3     709761   log      isHidden called
4     709762   log      isHidden called
5     709777   log      isHidden called
6     709777   log      isHidden called
7     709817   log      isHidden called
8     709818   log      isHidden called
.......

**Comment by av2k** [comment]
Hi there, excuse my mistake with the call trace: I took a screenshot of the first breakpoint, but this is actually a correct call since it happens during the initial page draw.

Here is the correct trace where the breakpoint in the function called by the [hidden] directive is reached by just moving the mouse.

<img width="567" alt="upper function call stack" src="https://cloud.githubusercontent.com/assets/8684223/11897194/cf2257ec-a58d-11e5-9d34-5c0ef00c5533.png">
<img width="572" alt="lower function call stack" src="https://cloud.githubusercontent.com/assets/8684223/11897196/d0c9c698-a58d-11e5-811c-2fc85bfd47a3.png">

**Comment by adamdbradley** [comment]
Oh geez, you're absolutely right! It looks like it's the side menu listeners that's causing this. Thanks, I'll take a look.
