### ISSUE TITLE
ionic generators broken since update alpha.42

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic2#756]
I updated to alpha.42 from alpha.37 and the simplest generator for page is broken, before the ones that worked were:
 * component
 * directive
 * injectable
 * page

The ones that didn't even worked before update:
 * page-login
 * page-sidemenu
 * page-signup
 * pipe
 * tabs

My console output for the error for basic page generator (that worked before):
> ionic g page NewPage

Error log, please note the ionic version is `alpha.42` and error states i need `alpha.31` or later:
>You do not appear to have a compatible version of Ionic v2 installed.
Ionic Framework v2 version 2.0.0-alpha.31 or later is required to use the generators.
Please run: "npm install ionic-framework" (CLI v2.0.0-beta.12)

>Your system information:

>Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 2.0.0-alpha.42
Ionic CLI Version: 2.0.0-beta.12
Ionic App Lib Version: 2.0.0-beta.6
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v5.1.0
Xcode version: Xcode 7.2 Build version 7C68

**Comment by 3dd13** [comment]
has figured out the problem and it will be fixed when the latest ionic-framework is released.
details here:

https://github.com/driftyco/ionic-cli/issues/696

**Comment by Luchillo** [comment]
The generators works now, but since yesterday 23/12/2015 the folder for app is outside www, need to update the folder.
