### ISSUE TITLE
Fix tabbar scenarios

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#757]
http://localhost:8000/dist/e2e/tabs/tab-bar-scenarios/

**Comment by brandyscarney** [comment]
What's wrong with them?

**Comment by adamdbradley** [comment]
Nothing, i'm crazy. I was viewing material design's on nexus 5 preview which was too small. Nothing to see here, carry on.

**Comment by brandyscarney** [comment]
Carrying on.
