### ISSUE TITLE
Emit an event for Segment Changed

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#758]
Add an event `change` on the parent `ion-segment`. Right now you can add `click` events to each `ion-segment-button` but there isn't a way to find out from the top level if the value changed.

**Comment by adamdbradley** [comment]
Let's just make it `change` that goes on `ion-segment`. And let's also add `select` on `ion-segment-button`.

**Comment by brandyscarney** [comment]
Added in https://github.com/driftyco/ionic2/commit/0f57b1f64f7a59d09c8582ae369f752391409f94
