### ISSUE TITLE
navbars and tabs conflict

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic2#761]
If you use the tabs starter, and remove the navbar from page, there's still 
a navbar in the dom pushing the content down

**Comment by adamdbradley** [comment]
Not sure we want to support having tabs without navbars. Transitions betweens pages with navbars and pages without would be a challenge.

**Comment by brandyscarney** [comment]
I saw this happening on normal pages too. Not sure if it changed.

**Comment by flavordaaave** [comment]
+1

**Comment by obetomuniz** [comment]
I created an [issue on forum](https://forum.ionicframework.com/t/documentation-without-informations-about-the-controllers-attributes-of-header-content-and-footer-sections-when-used-with-tabs/40442) about with this behavior @mhartington and I think that implement more controls is an important approach to offer more flexibility in the framework. And I extend the problem to all main sections when used with tabs.
