### ISSUE TITLE
ionic is not defined when run ionic serve

### ISSUE THREAD

**Issue by nampdn** [driftyco/ionic2#763]
If I run `ionic serve` and then navigate to the link : http://localhost:8100/?ionicplatform=android it will show up `Uncaught ReferenceError: ionic is not defined` in the console.

Here is error details:
![capture](https://cloud.githubusercontent.com/assets/15364911/11872997/f4008080-a50a-11e5-808d-d8f5c58a7411.PNG)

p/s: everything work fine, except that message.

**Comment by mhartington** [comment]
@nampdn can you try `ionicPlatform` instead. `Config` expects the property that you wish to change through querystrings to be `ionic+<PropertyNamedCapitalized>`

**Comment by nampdn** [comment]
Great! I tried and there is not error.
`http://localhost:8100/?ionicPlatform=android` 
I think the link should be replaced for `--lab` in the next release.

**Comment by mhartington** [comment]
Noted. Closing.
