### ISSUE TITLE
ion-segment inside navbar for iOS

### ISSUE THREAD

**Issue by nampdn** [driftyco/ionic2#764]
If I add about 5 segments inside a navbar in android it look very nice.
I have side-menu button on the left and 2 button on the right.
![capture](https://cloud.githubusercontent.com/assets/15364911/11874311/986e2072-a511-11e5-903d-d0ee0b3eb9cf.PNG)
With iOS, the segment cover those button and not scale between the buttons
![capture2](https://cloud.githubusercontent.com/assets/15364911/11874317/9af500ea-a511-11e5-8784-8da7d01a0b10.PNG)

**Comment by brandyscarney** [comment]
For a temporary fix you should be able to add the following CSS:

```
.toolbar ion-segment {
    max-width: 70%;
    margin: 0 auto;
}
```

And manipulate the max-width however you like. This is something that needs to be fixed on the toolbar itself for title as well. I created an issue for this separately: https://github.com/driftyco/ionic2/issues/820
