### ISSUE TITLE
ionic build does not compile sass

### ISSUE THREAD

**Issue by nraboy** [driftyco/ionic2#767]
Doing the following results in an app with no styles:

```
ionic start ExampleProject --v2 --ts
cd ExampleProject
ionic platform add ios
ionic build ios
ionic emulate ios
```

Running `gulp sass` fixes this.

See https://github.com/driftyco/ionic2/issues/84 for reference.

**Comment by tlancina** [comment]
Thanks for the issue, as a workaround you can run `ionic serve` in another tab (or webpack --watch in one tab and `gulp watch` in a second tab! :))

**Comment by tlancina** [comment]
This was fixed in the last release, you can use the `-b` or `--nobundle` flags to opt out of the bundling, which runs by default before build now.
