### ISSUE TITLE
Tabs do not look correct in starter project

### ISSUE THREAD

**Issue by nraboy** [driftyco/ionic2#768]
See https://github.com/driftyco/ionic2/issues/84 for a reference.

Here is what the tabs look like:

![simulator screen shot dec 17 2015 8 50 16 am](https://cloud.githubusercontent.com/assets/983958/11875989/37d4869a-a49c-11e5-805b-7497e87f3858.png)

**Comment by tlancina** [comment]
Looks like you need to run `gulp fonts`, which didn't happen automatically as part of `gulp watch` because of https://github.com/driftyco/ionic2/issues/767.  

Closing as a dup, feel free to re-open if this is incorrect.

**Comment by nraboy** [comment]
What is the estimation on a fix to this?  Seems like I have to jump through hoops to get this working with the temp solutions.
