### ISSUE TITLE
Errors with SqlStorage

### ISSUE THREAD

**Issue by nraboy** [driftyco/ionic2#770]
I am getting the following error:

```
I/chromium( 2458): [INFO:CONSOLE(174)] "OPEN database: __ionicstorage", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (174)
V/SQLitePlugin( 2458): Android db implementation: sqlite4java (NDK)
V/info    ( 2458): Open sqlite db: /data/data/io.ionic.starter/databases/__ionicstorage
I/chromium( 2458): [INFO:CONSOLE(105)] "new transaction is waiting for open operation", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (105)
I/chromium( 2458): [INFO:CONSOLE(6110)] "CREATING TABLE", source: file:///android_asset/www/build/js/app.bundle.js (6110)
I/chromium( 2458): [INFO:CONSOLE(105)] "new transaction is waiting for open operation", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (105)
E/AndroidProtocolHandler( 2458): Unable to open asset URL: file:///android_asset/www/build/fonts/roboto-regular.ttf
E/AndroidProtocolHandler( 2458): Unable to open asset URL: file:///android_asset/www/build/fonts/roboto-medium.ttf
I/chromium( 2458): [INFO:CONSOLE(79)] "DB opened: __ionicstorage", source: file:///android_asset/www/plugins/cordova-sqlite-storage/www/SQLitePlugin.js (79)
E/AndroidProtocolHandler( 2458): Unable to open asset URL: file:///android_asset/www/build/fonts/roboto-regular.woff
E/AndroidProtocolHandler( 2458): Unable to open asset URL: file:///android_asset/www/build/fonts/roboto-medium.woff
W/System.err( 2458): java.sql.SQLException: sqlite3_bind_null failure: bind or column index out of range
W/System.err( 2458): 	at io.liteglue.SQLiteGlueConnection$SQLGStatement.bindNull(SQLiteGlueConnection.java:113)
W/System.err( 2458): 	at io.liteglue.SQLitePlugin$SQLiteDatabaseNDK.executeSqlStatementNDK(SQLitePlugin.java:452)
W/System.err( 2458): 	at io.liteglue.SQLitePlugin$SQLiteDatabaseNDK.executeSqlBatch(SQLitePlugin.java:384)
W/System.err( 2458): 	at io.liteglue.SQLitePlugin$DBRunner.run(SQLitePlugin.java:566)
W/System.err( 2458): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err( 2458): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err( 2458): 	at java.lang.Thread.run(Thread.java:818)
V/executeSqlBatch( 2458): SQLitePlugin.executeSql[Batch](): Error=sqlite3_bind_null failure: bind or column index out of range
W/System.err( 2458): java.sql.SQLException: sqlite3_bind_null failure: bind or column index out of range
W/System.err( 2458): 	at io.liteglue.SQLiteGlueConnection$SQLGStatement.bindNull(SQLiteGlueConnection.java:113)
W/System.err( 2458): 	at io.liteglue.SQLitePlugin$SQLiteDatabaseNDK.executeSqlStatementNDK(SQLitePlugin.java:452)
W/System.err( 2458): 	at io.liteglue.SQLitePlugin$SQLiteDatabaseNDK.executeSqlBatch(SQLitePlugin.java:384)
W/System.err( 2458): 	at io.liteglue.SQLitePlugin$DBRunner.run(SQLitePlugin.java:566)
W/System.err( 2458): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err( 2458): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err( 2458): 	at java.lang.Thread.run(Thread.java:818)
V/executeSqlBatch( 2458): SQLitePlugin.executeSql[Batch](): Error=sqlite3_bind_null failure: bind or column index out of range
I/chromium( 2458): [INFO:CONSOLE(6114)] "ERROR -> {"tx":{"db":{"openargs":{"name":"__ionicstorage","location":2,"createFromLocation":0,"backupFlag":2,"existingDatabase":false,"dblocation":"nosync"},"dbname":"__ionicstorage"},"txlock":true,"readOnly":false,"executes":[],"finalized":true},"err":{"message":"sqlite3_bind_null failure: bind or column index out of range","code":0}}"
```

This happens when I try to do the following:

```javascript
this.storage = new Storage(SqlStorage);
console.log("CREATING TABLE");
this.storage.query('CREATE TABLE IF NOT EXISTS people (id INTEGER PRIMARY KEY, firstname TEXT, lastname TEXT)').then((data) => {
    console.log("TABLE CREATED -> " + JSON.stringify(data));
}, (error) => {
    console.log("ERROR -> " + JSON.stringify(error));
});
```

Last I checked that is a perfectly fine statement for creating a SQLite table.

Any insight?

Thanks,

**Comment by nolanlawson** [comment]
Are you sure this isn't an error with https://github.com/litehelpers/Cordova-sqlite-storage? Good way to check is to see if it fails in both iOS and Android, or only in Android. If only in Android, it's probably a bug with the SQLite Storage plugin.

**Comment by nraboy** [comment]
So for iOS it does in fact work fine.

I hate to be Mr. Negative here, but I thought the Ionic guys were putting a lot of emphasis that in Ionic Framework 2, certain plugins would be better.  Sounds like to me that Ionic Framework 2 is still at the mercy of the Apache Cordova community.

This is the bug report for Android: https://github.com/litehelpers/Cordova-sqlite-storage/issues/393

**Comment by shprink** [comment]
Ionic2 is still in alpha version... Seems understandable at this point of the project don't you think @nraboy ?

**Comment by nraboy** [comment]
I won't dig too deep into this since a GitHub issue ticket probably isn't the best place.  I'm just interested to know how it would be different as beta or stable.  Are there plans to snapshot certain plugins to prevent installing a potentially broken build?

**Comment by shprink** [comment]
Yeah you are right, it is a problem with the cordova plugin not Ionic. Did you install a particular version or the master branch? By experience always use versions when installing cordova plugins otherwise you end up with problems like that.

**Comment by mlynch** [comment]
Testing to see what's going on here

**Comment by nraboy** [comment]
Should we have to worry about specific plugin versions as a user?  What if these plugins don't have release tags?  Thanks @mlynch for having a look.

**Comment by mlynch** [comment]
Okay, the issue with this was semantics of default arguments. Looks like the underlying implementation is really sensitive about the number of arguments in the params array, and using `...params` created an array with one undefined item: `[undefined]` when it should have been empty. Changed that to a default of an empty array and it resolved the issue for me. Also: you were missing the error in your console logs, try dumping error.err.

To answer the plugin question, with NPM this is easier, since we'll be able to say "this version of Ionic Native uses 0.4.5 of sqlite" (or a similar semver). 

Yes, the Cordova plugin ecosystem is unweildy right now. I think having the plugins project more closely embedded in Ionic will help us help the rest of the ecosystem by tightening the feedback loop. We didn't do that well enough with ngCordova because most Ionic users didn't even know that project existed. ngcordova became a decent repository for issues with other plugins, but it was often difficult to know if that issue was with the plugin wrapper, or the plugin itself. Hoping to remove any question about the former in the upcoming release.

Thanks for the help on this Nic!

**Comment by nraboy** [comment]
Thanks!

**Comment by nraboy** [comment]
Forgot to ask, will this commit show up in the next alpha release?

**Comment by mlynch** [comment]
Yep! Should be out in the next few days though @brandyscarney is controlling releases so better question for her

**Comment by mlynch** [comment]
@nraboy she just told me it's released in alpha.44 :)

**Comment by brodybits** [comment]
> Looks like the underlying implementation is really sensitive about the number of arguments in the params array, and using `...params` created an array with one undefined item: `[undefined]` when it should have been empty.

I just raised litehelpers/Cordova-sqlite-storage#398 to test this case on the Cordova plugin and will test it when I get a chance. The sqlite plugin should either handle this like an empty parameters array (like `[]`) or throw an exception, and it should be the same for all supported platforms.

**Comment by mlynch** [comment]
Cool, part of me thinks we've also uncovered a typescript bug in handling splat params

**Comment by mlynch** [comment]
Err, "spread" operators
