### ISSUE TITLE
CLI: livereload isn't working on Sass changes

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#772]
FWIW the live reload works with any JS changes

**Comment by 3dd13** [comment]
Hi @adamdbradley, want to get some idea if you have any plan how to include that ?
would love to help

from what I see in the code, the file change watch https://github.com/driftyco/ionic-app-lib/blob/v2-beta/lib/v2/build.js#L74 depends on the webpack config
and the ionic2 project webpack.config.js now only have js in the entry

some options I can think of:
- utilize webpack watch to watch css file change as well, and trigger the same Serve._postToLiveReload
- add another watch to do hot replace css without reloading the webpage

**Comment by 3dd13** [comment]
@brandyscarney
@adamdbradley 

just tested ionic-conference-app with the latest cli (beta-15) and ionic & webpack config
both js and scss changes will got updated without refreshing browser

**Comment by tlancina** [comment]
Was a bad glob pattern, should be fixed in the latest release, please re-open if it's not.
