### ISSUE TITLE
Updating ionic breaks serve command in ubuntu

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic2#777]
Hi, i was working in Mac and all right, then i had to change to Ubuntu and the serve command wasn't detecting the changes in source, i did an update with the following command:
>npm uninstall -g ionic && npm uninstall -g cordova && rm -rf node_modules && npm cache clear && npm cache clean && npm i -g cordova ionic@beta && npm i && ionic serve -s -c

At the end of this long operation this was the output of the terminal with the ionic serve command, it didn't even open the browser window for the app:
![image](https://cloud.githubusercontent.com/assets/9698639/11904324/55832ba0-a58d-11e5-94fd-382572a5f23b.png)

My ionic info:
>Your system information:

>Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 2.0.0-alpha.42
Ionic CLI Version: 2.0.0-beta.12
Ionic App Lib Version: 2.0.0-beta.6
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.04 
Node Version: v4.0.0

**Comment by tlancina** [comment]
Shot in the dark, but does this work: https://github.com/gulpjs/gulp/issues/217#issuecomment-61039024 ?

**Comment by Luchillo** [comment]
Ok it actually did, can you explain why so i avoid breaking it again?

**Comment by tlancina** [comment]
No idea, I just googled the error :)

**Comment by tlancina** [comment]
From that SO question: http://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached%E2%80%8C%E2%80%8B.
