### ISSUE TITLE
Option buttons of the ion-item-sliding doesn't work on real devices

### ISSUE THREAD

**Issue by ivanbtrujillo** [driftyco/ionic2#778]
The option buttons of the item-sliding doesn't work (the click events) in android (nexus 5 with Android 6.1). I have tested it on a AVD Android 5.1 with the same result.

On the IOS simulator directly the animation to swipe doesn’t work (maybe a simulator problem?).

On the browser with ionic serve works like a charm.  

I ran my app on the device with -l -c to see if there are any error but nothing happens. Didn’t see any issue on github for this. Is a bug?
My code is pretty simple and on the browser works perfectly:
```
<ion-content class="background">
  <ion-list>
    <ion-item-sliding class="item-sliding" *ngFor="#item of items"  (click)="viewItem(item)">
      <ion-item class="item-list">
        {{item.title}}
      </ion-item>
      <ion-item-options>
        <button primary (click)="editItem(item)"><icon create></icon>Edit</button>
        <button danger (click)="removeItem(item)"><icon trash></icon> Delete</button>
      </ion-item-options>
    </ion-item-sliding>
  </ion-list>
</ion-content>
```

**Comment by adamdbradley** [comment]
The `viewItem(item)"` event should go on `<ion-item>`, not `<ion-item-sliding>`. Please let me know if that fixes your issue.

**Comment by ivanbtrujillo** [comment]
It doesn't work. i have the same result :-/

**Comment by educatedrisk** [comment]
Adam,  I have tried to do this sliding with the edit / delete icons.  

Works fine in my google chrome browser but when I upload to Ionic View and open on my Samsung Galaxy Note 3 running android version 5.0.   

The sliding to the left works, it shows the two buttons, but you cannot click on the Edit or Delete.  As I close it and tap furiously it will fire the click event.  

It is like something is overlaying on the buttons and not allowing it to work properly

**Comment by ivanbtrujillo** [comment]
@drew As i see, it's fixed for thr next release
