### ISSUE TITLE
(docs) Simple instructions on how to update project to use latest ionic-framework

### ISSUE THREAD

**Issue by astec** [driftyco/ionic2#780]
Sorry if I bother you with too stupid questions but,

I don't get how to update my current project to use latest ionic-framework published to npm.

I ran: 
`$ npm -g update ionic-framework` and also tried `$ npm -g install ionic-framework`
Then ran in project directory 'npm install'.

But still in package.json I have
```
{
  "name": "ionic-framework",
  "version": "2.0.0-alpha.42",
```

I think it would be good to have a section at: http://ionicframework.com/docs/v2/getting-started/installation/

**Comment by mhartington** [comment]
This is covered here
http://ionicframework.com/docs/v2/getting-started/concepts/

Though I should mention it out more clearly in the getting started guides. 

Note for self: Rename concepts to NPM Packages.

**Comment by astec** [comment]
@mhartington, tried `npm update` as advised at http://ionicframework.com/docs/v2/getting-started/concepts/ and it did not help:
```
Alex-MacBook:ionic2-app astec$ npm outdated
Package                 Current          Wanted          Latest  Location
ionic-framework  2.0.0-alpha.42  2.0.0-alpha.42  2.0.0-alpha.44  ionic-framework
Alex-MacBook:ionic2-app astec$ npm update
Alex-MacBook:ionic2-app astec$ npm outdated
Package                 Current          Wanted          Latest  Location
ionic-framework  2.0.0-alpha.42  2.0.0-alpha.42  2.0.0-alpha.44  ionic-framework
```

**Comment by 3dd13** [comment]
@astec since the package.json generated specified the particular version, so it won't get updated with npm update.

if you want to update the version number in your package.json, you need something like https://www.npmjs.com/package/npm-check-updates

**Comment by astec** [comment]
@3dd13 Thanks, just docs there say simply to use `npm update` and it did not work on a project generated by ionic.

http://ionicframework.com/docs/v2/getting-started/concepts/

**Comment by drewrygh** [comment]
Hey @astec - just updated and moved these docs: http://ionicframework.com/docs/v2/resources/using-npm/

Basically you have three options:
  - 1. `npm install ionic-framework@latest`
  - 2. `npm install ionic-framework@2.0.0-alpha.45`(or whatever the latest version happens to be)
  - 3.  as @3dd13 mentioned, update `package.json` to require the latest ionic version, so `"ionic-framework": "2.0.0-alpha.45"` at the moment
