### ISSUE TITLE
How to add parameters in tab

### ISSUE THREAD

**Issue by zengchuan** [driftyco/ionic2#782]
I want to use params in tab. How to do?
<ion-tab tab-title="Angular2"  [root]="RootComp" [params]="{}"></ion-tab>

**Comment by ivanbtrujillo** [comment]
hi @zengchuan, i think here is not the right place for doubts. If you have a question, you can ask on the ionic-worldwide slack group. The ionic developers answers really fast and you can talk with other developers that are making the same things like you. Also, you have the ionic2 section on the Ionic Forum.

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5043
