### ISSUE TITLE
popup, actionsheet api consistency

### ISSUE THREAD

**Issue by AgDude** [driftyco/ionic2#788]
These components are all very similar, but the APIs for configuring similar options have annoying discrepancies. Please take the opportunity of a major version bump to rework these APIs.
I have not used ionic 2, but just checked the docs and I don't see major changes here. This is an annoyance every time I use one of these components in ionic 1.

For example to close an action sheet, one returns `true` or `false` from a function. To "not close" a popup one must use e.preventDefault`.

**Comment by adamdbradley** [comment]
Related: https://github.com/driftyco/ionic2/issues/788
