### ISSUE TITLE
Docs: Tabs do not need a [root] and now have a select event

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#789]
Document that tabs do not need to have a root page, and can use the `(select)` event to open up a modal, sign out, etc.

https://github.com/driftyco/ionic2/blob/0dd6b2f4bd43c5074abf71560f192b9f7a1a8c58/ionic/components/tabs/test/advanced/tabs.html#L6

**Comment by mhartington** [comment]
Updated and live.
http://ionicframework.com/docs/v2/api/components/tabs/Tab/
