### ISSUE TITLE
sqlstorage create table query

### ISSUE THREAD

**Issue by meeximum** [driftyco/ionic2#791]
Hi,

when I run following code
```javascript
		this.storage = new Storage(SqlStorage, { name: 'testdb' });
        // statement A
		this.storage._strategy._db.transaction((tx) => {
            tx.executeSql('CREATE TABLE IF NOT EXISTS address (id text primary key, description text, address text, lat text, lon text)', [], (tx, res) => {
            }, (tx, err) => {
                console.error('Storage: Unable to create initial storage tables', tx, err);
            });
        });
		// statement B
        this.storage.query('CREATE TABLE IF NOT EXISTS address2 (id text primary key, description text, address text, lat text, lon text)')
            .then((result) => {
                console.log(result);
            }, (err) => {
                console.error(err);
            });
```

statement is execuded without any problems, but statement B throws an error
**err: SQLError
code: 5
message: "number of '?'s in statement string does not match argument count"**

**Comment by mlynch** [comment]
This was fixed last week, which version of ionic?

**Comment by meeximum** [comment]
My system information:

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 2.0.0-alpha.42
Ionic CLI Version: 2.0.0-beta.12
Ionic App Lib Version: 2.0.0-beta.6
OS: Windows 8.1
Node Version: v0.12.7

**Comment by mlynch** [comment]
Yep, should be fixed in beta.44

**Comment by meeximum** [comment]
hmm, after
**npm install -g ionic@beta**

I got

Cordova CLI: 5.4.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 2.0.0-alpha.42
Ionic CLI Version: 2.0.0-beta.14
Ionic App Lib Version: 2.0.0-beta.7
OS: Windows 8.1
Node Version: v0.12.7

still alpha.42??

**Comment by tlancina** [comment]
@meeximum that's confusing and should be changed, but Ionic Version refers to the framework, so the `ionic-framework` npm package.

You can update it by doing `npm install ionic-framework@latest`.

**Comment by meeximum** [comment]
perfect! thx
