### ISSUE TITLE
Overlay Controller API

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#793]
Since v2, under the hood we already have a common OverlayController, which extends NavController, so that we can push and pop our different types of overlays: ActionSheet, Alert, Confirm, Prompt, Modal, Loading, etc. The biggest requirement with ng2 is that we have an "anchor" which these overlays can be attached to, which is what OverlayController handles and makes sure the correct providers/directives are available to the overlay.

However, each overlay API is slightly different, and the way they're setup now the dev does not have immediate control of their new overlay until it has finished animating in, basically because the `open` method returns a promise that resolves when the open animation finished. I think this is restricting, and we should change it around to allow to give devs more control, but hopefully still keeping it pretty simple to wire up.

So instead of every overlay provider being injected in the constructor, we only inject an `OverlayController`, like you would with `NavController`. This would be the same controller all overlays would reuse, and I think it'd help understand how overlays stack on top of one another, they'd all work the same way, and you'd have just as much power by pushing, popping, removing by index, inserting, etc as NavController.

Some ideas below. Notice how `ActionSheet` is not injected in the constructor, but is used to create a new actionSheet instance, which is then pushed onto the OverlayController. Additionally, the dev now has more control of programmatically closing any instance, and there's no confusion how to get ahold of the instance, versus `this.app.getComponent('some-id')` or getting ahold of the reference after the actionsheet has finished animating in. Also, `ActionSheet` itself could be given some great individual methods to help the dev set it up, but the shorthand could still use a map of options.

```
import {ActionSheet} from '../action-sheet/action-sheet';
import {OverlayController} from '../overlay-controller/overlay-controller';

@App(...)
class MyApp {
    constructor(overlay: OverlayController) {
        this.overlay = overlay;
    }
    openActionSheet() {
        let actionSheet = new ActionSheet(opts);
        this.overlay.push(actionSheet);
    }
}
```

Popups could even be just one class, and the options decide if it's an alert, confirm or prompt (haven't decided if that's good or bad). And now the dev has more control of exactly what should happen, what to do with things have closed or opened, etc.

```
import {Popup} from '../popup/popup';
import {OverlayController} from '../overlay-controller/overlay-controller';

@App(...)
class MyApp {
    constructor(overlay: OverlayController) {
        this.overlay = overlay;
    }
    openPopup() {
        // open two popups then immediately close them
        let alertPopup = new Popup(opts);
        this.overlay.push(alertPopup).then( () => {
            let confirmPopup = new Popup(opts);
            this.overlay.push(confirmPopup).then( () => {
                this.overlay.pop().then( () => {
                    this.overlay.pop();
                });
            });
        });
    }
}
```

```
import {MyModalPage} from './my-modal';
import {Modal} from '../modal/modal';
import {OverlayController} from '../overlay-controller/overlay-controller';

@App(...)
class MyApp {
    constructor(overlay: OverlayController) {
        this.overlay = overlay;
    }
    openModal() {
        this.modal = new Modal(MyModalPage);
        this.overlay.push(this.modal, params);
    }
    closeModal() {
        this.overlay.pop();
        // or be more specific and remove an exact overlay
        this.overlay.remove(this.modal);
    }
}
```

Related code in swift. The `UIAlertController` is our `Popup` class, and `presentViewController` is our `OverlayController`. 

```
@IBAction func actionSheetButtonPressed(sender: UIButton) {
    let alert = UIAlertController(title: "My Alert", message: "This is an action sheet.", preferredStyle: .Alert)
    let firstAction = UIAlertAction(title: "one", style: .Default) { (alert: UIAlertAction!) -> Void in
        NSLog("You pressed button one")
    }   
    let secondAction = UIAlertAction(title: "two", style: .Default) { (alert: UIAlertAction!) -> Void in
        NSLog("You pressed button two")
    }
    alert.addAction(firstAction)
    alert.addAction(secondAction)
    presentViewController(alert, animated: true, completion:nil)
}
```

So this helps form a common way to do things that devs are already doing for NavController, and gives us an API we can keep adding to (Loading indicators, progress bars, etc). It also allows devs to use the OverlayController for whatever they'd like, and not have to hack one of the existing Ionic providers.

Thoughts?
@mlynch @brandyscarney @tlancina @drewrygh @mhartington @AgDude @Luchillo

**Comment by mlynch** [comment]
It's great, I just wish we could get rid of having to do anything with the `OverlayController`. Is there not a way to get rid of that, or have the `Alert`, `ActionSheet`, etc. inject it themselves?

**Comment by adamdbradley** [comment]
The overlays need to have some reference to the actual app's instance, and some anchor to append the overlay next to. Without something being injected in the constructor, our new overlay instances wouldn't know where and how to attach themselves to the app, and all of the existing providers that have been made available would not be available to the overlays. There still might be a way, just haven't thought of it yet.

**Comment by adamdbradley** [comment]
Also, we'll be removing `Popup` in place of `Alert`. And an `Alert` has the options for additional buttons (confirm), and having an input (prompt).

**Comment by Luchillo** [comment]
This is a great idea, i'm having a lot of issues dealing with the popup's close function, as i have to wait for the popup to render to get a proper reference to it before closing it, if i need to cancel the show of the popup before it even shows or in the middle of the transition, i have to wait using a timeout, which makes it unstable accordingly to the power of the devise.

**Comment by drewrygh** [comment]
:+1: 

It might also be useful to have a `state` property on the ActionSheet/Alert instance (eg: `initialized`, `opening`, `open`,`closing`, `closed`). Or maybe events could be emitted when this property changes? This seems like it could help w/ @Luchillo's use case.

**Comment by brandyscarney** [comment]
I like it, but I agree with Max, I think exposing the overlay this much may be too low level.

Also, what do you mean by renaming Popup to Alert? Confirm & Prompt are being removed?

**Comment by AgDude** [comment]
I'll add to the chorus that this should be simpler. It is nice to expose the low-level api, as long as there is a pretty wrapper around it for the simple cases.

Here is an example of what I have done with the actionSheet api in V1, because the current api was too cumbersome.

```
/**
   * @ngdoc service
   * @name myUtils.service:myActionSheet
   * @description an extension of $ionicActionSheet to implement a sane api. Takes a buttons array like the example below.
   * Only one button in the array should have the cancel or destructive properties. Also closes the actionSheet by
   * default, unless the button action function returns false.
   * @example
   * <pre>
   *   {
   *     text: 'some text',
   *     action: function(){ return something },
   *     destructive: false,
   *     cancel: false,
   *   }
   * </pre>
   */
  .factory('myActionSheet', function($ionicActionSheet){

    return {
      show: function(options){
        var newOptions = angular.copy(options);
        newOptions.buttons = [];

        newOptions.buttonClicked = function(index){
          var result = newOptions.buttons[index].action();
          if (result || angular.isUndefined(result) ){
            return true;
          }
          return result;
        };

        angular.forEach(options.buttons, function(button){
          if ( button.cancel ){
            newOptions.cancel = button.action || angular.noop;
            newOptions.cancelText = button.text || 'Cancel';
          }
          else if ( button.destructive ){
            newOptions.destructiveButtonClicked = button.action || angular.noop;
            newOptions.destructiveText = button.text || 'Delete';
          }
          else {
            if ( angular.isUndefined(button.action)) { button.action = angular.noop; }
            newOptions.buttons.push(button);
          }
        });
        return $ionicActionSheet.show(newOptions);
      }
    };
  });
```

**Comment by adamdbradley** [comment]
Latest plan: https://github.com/driftyco/ionic2/blob/overlay-refactor/CHANGELOG.md#overlay-refactor

**Comment by AgDude** [comment]
That looks great! Thanks for the update.

**Comment by Luchillo** [comment]
As now we can hold references to the popups we open, now will be able to close or cancel the opening of a popup without using timeouts?

**Comment by adamdbradley** [comment]
Overlay refactor merged into master: https://github.com/driftyco/ionic2/blob/master/CHANGELOG.md#200-alpha47-2016-1-4
