### ISSUE TITLE
Deployement on Android 4.0.x up to 4.2.2 (?) gives a blank screen

### ISSUE THREAD

**Issue by krz37** [driftyco/ionic2#794]
By default the configuration allows to deploy on 4.x.x devices however with 2 phones, people beta testing my app have the same issue : The screen stays blank after launching.
I believe this is due to the webview included in their depreciated phone version not supporting the new functions used by ionic 2.
If I compiled my app with --release tag, can I see any logging of the issue right now? If not I will be able to give more details on Wednesday the 30th

Here are the 2 models : 
 Xiaomi mi2 running MIUI-JLB20.0
 Samsung "Trends Plus" running stock ROM 4.2.2

**Comment by mhartington** [comment]
Confirmed, seeing this as well. 
Had to install crosswalk for this to work.

**Comment by tlancina** [comment]
Should be fixed in https://github.com/driftyco/ionic2/commit/faee5fcdba76de026d83ffff8629bfd7916e9be3.

**Comment by rafasegat** [comment]
Cool! Waiting, thanks!
