### ISSUE TITLE
webpack merge all js files in to one big file

### ISSUE THREAD

**Issue by mashaly100200** [driftyco/ionic2#796]
one of best future in hybrid application that i can update my application without using app store.
but webpack merge all javascript file to one big file , so it's difficult to update coz it becom a big file  , and also it's very difficult to debug

how i can use ionic2 without webpack , like i'm using angular2  

also i want to know why all ionic examples rename typescript files from .ts  to .js , i feel some confusion when use ionic2 although  it was easy to use angular2

**Comment by mhartington** [comment]
1) Will bundled code be easy to update on the fly
3) Ionic 2 without webpack
4) TS vs JS


Bundled code is no different than code that you would concatonated together, so it's still easy to update on the fly.

Currently Ionic 2 is going to use webpack. It's the best solution for what Ionic needs. 

The starter apps all use Javascript, not typescript. Though if you want to use typescript, you can pass
 a `--ts` flag when starting a project

```ts
ionic start myApp --v2 --ts
```

http://ionicframework.com/docs/v2/getting-started/tutorial/

**Comment by mashaly100200** [comment]
many many thanks @mhartington  for your reply  ,

the bundle file include all dependency libraries  therefore its size up to 5 MB , so it will take long time to transfer from server to mobile device , but if it separated then it will be small size   , also i can update my own code only, no need to update these dependency libraries .


one more question plz ,  why ionic2 use properties without define it for example 
class myclass
{
constructor(app: IonicApp, platform: Platform)  {  
         this.rootPage = HelloIonicPage;
    }
}

, it gives me error " Property 'rootPage ' does not exist on type 'myclass'. "

sorry for my Many beginner questions , but you are generous man :)

**Comment by Luchillo** [comment]
Are you using the ts version? if not that's pretty weird as js version allow to set that property on the class, maybe ts version needs to implement an interface.

**Comment by mashaly100200** [comment]
i use ts v1.7   also it was happen when i was use v1.6  with visual studio and webstorm 

all typescript libraries that i saw,  define all properties before use it , like this in my previous example


class myclass
{
rootPage:any ;

constructor(app: IonicApp, platform: Platform) {

this.rootPage = HelloIonicPage;
}
}

**Comment by Luchillo** [comment]
Sorry, can't help about ts, i'm mostly using ES2015.

**Comment by mashaly100200** [comment]
i was not know that i can use source-map of typescript files with webpack by adding  devtool: 'source-map'   to webpack config file

afte i become familiar with webpack  , i think webpack is a excellent choice 
thanks ionic team

**Comment by Luchillo** [comment]
You mean was an excellent choice, the next release uses `babel-loader`, still wan't to know the reason they decided to drop webpack (even if `babel-loader` has webpack as dependency.
