### ISSUE TITLE
Improve this doc link for translation goes to 404

### ISSUE THREAD

**Issue by webprofusion-chrisc** [driftyco/ionic2#797]
Wanted to improve the docs for translation util:

http://ionicframework.com/docs/v2/utils/translation/
'Improve this doc' link goes to 404 (https://github.com/driftyco/ionic-site/edit/ionic2/docs/v2/utils/storage/index.md)

**Comment by mhartington** [comment]
that link is an old page before the docs were reorganized

If you want to improve the docs, you could make a PR and edit these files.
https://github.com/driftyco/ionic2/tree/master/ionic/translation

Cheers
