### ISSUE TITLE
Split gulp package and publish ?

### ISSUE THREAD

**Issue by 3dd13** [driftyco/ionic2#799]
@adamdbradley

Can we split the gulp publish into
* package
* publish(['package'])

https://github.com/driftyco/ionic2/commit/d15fdcf7fc6873fb043b6d5adcdb0115c8e8b569#diff-b9e12334e9eafd8341a6107dd98510c9

wanna make changes on my local machine and then package for npm link ionic-framework
so in this case, npm publish should not be run (although we won't have permission to publish to public npm registry anyway)
hopefully that won't slow down the core team release iteration speed

**Comment by adamdbradley** [comment]
:+1:

**Comment by 3dd13** [comment]
wow it was quick !

I did try to submit a pull request on that ...
https://github.com/3dd13/ionic2/tree/split-gulp-publish-package

thanks !
