### ISSUE TITLE
Latest starter with alpha.45 compile error

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic2#805]
I had an app that compiled and run to android from ubuntu, after update to alpha.45 from alpha.42 the run and build command broke, even the sidemenu starter is broken with error:
> √ Webpack complete

>Running command: /home/carlos/Carlos/Programming/OSGroup/buildTest2/hooks/after_prepare/010_add_platform_class.js /home/carlos/Carlos/Programming/OSGroup/buildTest2
add to body class: platform-android
Running command: /home/carlos/Carlos/Programming/OSGroup/buildTest2/platforms/android/cordova/run 
ERROR: TypeError: Cannot read property '1' of null
ERROR running one or more of the platforms: Error: /home/carlos/Carlos/Programming/OSGroup/buildTest2/platforms/android/cordova/run: Command failed with exit code 2
You may not have the required environment or OS to run this project

**Comment by mhartington** [comment]
can you provide the output from your ionic info

**Comment by Luchillo** [comment]
Ok i just ripped out ionic and cordova and reinstalled with:
>rm -rf buildTest2 && npm uninstall -g ionic && npm uninstall -g cordova && npm cache clear && npm cache clean && npm i -g cordova ionic@beta && ionic start buildTest2 sidemenu --v2 && cd buildTest2 && npm i webpack && npm i && ionic build android

Didn't work, same output, here's the info:

>Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 2.0.0-alpha.45
Ionic CLI Version: 2.0.0-beta.15
Ionic App Lib Version: 2.0.0-beta.8
OS: Distributor ID:	Ubuntu Description:	Ubuntu 15.10 
Node Version: v4.0.0

**Comment by mhartington** [comment]
Get an ubuntu vm setup, got a similar error. From the output it looks like an issue on cordova's side of thing, not ionic.

May need to open an issue here
https://issues.apache.org/jira/browse/CB/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':CordovaLib:processDebugResources'.
> java.io.IOException: Cannot run program "/home/mharington/.linuxbrew/Cellar/android-sdk/24.4/build-tools/23.0.2/aapt": error=2, No such file or directory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.847 secs

/home/mharington/Github/test/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: /home/mharington/Github/test/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/mharington/Github/test/platforms/android/build.gradle,-Dorg.gradle.daemon=true
Command finished with error code 1: /home/mharington/Github/test/platforms/android/cordova/build 
ERROR building one of the platforms: Error: /home/mharington/Github/test/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /home/mharington/Github/test/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (/home/mharington/.linuxbrew/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/src/superspawn.js:139:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by Luchillo** [comment]
I think maybe it has to do with my java version, as i have both java 8 and 9 installed, i tried with a ionic 1 project that worked before and the error is the same, tried with cordova 5.3.3, 5.4.0 and 5.4.1 and same result.

Also testing with the v1 cli with: 
>npm uninstall ionic -g && npm uninstall cordova -g && npm cache clear && npm cache clean && npm i cordova -g && npm i ionic -g

So it probably is an issue with cordova or my java setup.

**Comment by Luchillo** [comment]
I'm confused about how to generate an issue in the cordova page, is there a github page for it?

**Comment by Luchillo** [comment]
Nailed it, it was either my Java or Android, wiped them both and reinstalled, set env variables and now it works again in my Ubuntu.
