### ISSUE TITLE
slider template expression not shown

### ISSUE THREAD

**Issue by arashbi** [driftyco/ionic2#806]
When I use a expression on a slider, it is invisible until I touch it, and move a bit. Then it appears.
Is it a bug or I am doing something wrong?

**Comment by 3dd13** [comment]
could you post the code to reproduce the problem ?

**Comment by msaelices** [comment]
I can reproduce the same thing with this code:

    <ion-content padding class="home">
        <ion-slides (change)="onSlideChanged($event)" index="0" loop="false" autoplay="false">
          <ion-slide>
            <h2>Slide1</h2>
          </ion-slide>
          <ion-slide>
            <h2>Slide 2</h2>
          </ion-slide>
          <ion-slide>
            <h2>Slide 3</h2>
            <ion-card *ngFor="#event of events">
                <img src="{{ event.poster }}"/>
                <ion-card-content>
                  <h2 class="card-title">
                    {{ event.name }}
                  </h2>
                </ion-card-content>
            </ion-card>
          </ion-slide>
        </ion-slides>
    </ion-content>

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5041
