### ISSUE TITLE
Can’t serve new TypeScript project: Problems with webpack.config

### ISSUE THREAD

**Issue by DustinJSilk** [driftyco/ionic2#809]
Getting an error when trying to start a new TypeScript project. Tried playing around with the Webpack.config file - which mixes things up but doesn't resolve to a successful launch. A new JavaScript project works fine if I remove this line for some reason: `var webpack = require('webpack');`

Heres the error I get when serving a new TypeScript project:

> multi main
> Module not found: Error: Cannot resolve 'file' or 'directory' /Users/[user]/Repos/ionic-app/ionicApp/app/app in /Users/[user]/Repos/ionic-app/ionicApp
> resolve file
/Users/[user]/Repos/ionic-app/ionicApp/app/app doesn't exist
/Users/[user]/Repos/ionic-app/ionicApp/app/app.js doesn't exist
/Users/[user]/Repos/ionic-app/ionicApp/app/app.ts doesn't exist
resolve directory
/Users/[user]/Repos/ionic-app/ionicApp/app/app doesn't exist (directory default file)
/Users/[user]/Repos/ionic-app/ionicApp/app/app/package.json doesn't exist (directory description file)
[/Users/[user]/Repos/ionic-app/ionicApp/app/app]
[/Users/[user]/Repos/ionic-app/ionicApp/app/app.js]
[/Users/[user]/Repos/ionic-app/ionicApp/app/app.ts]
@ multi main (CLI v2.0.0-beta.15)

> Your system information:

> Cordova CLI: 5.4.1
Gulp version: CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-alpha.45
Ionic CLI Version: 2.0.0-beta.15
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: 3.1.1 
OS: Mac OS X Mavericks
Node Version: v4.2.3
Xcode version: Xcode 6.1.1 Build version 6A2008a

Ive tried with the latest versions of Node as well. Reinstalling just about everything on each attempt. Nothing works.
Heres my webpack.config if you don't wish to download the latest one

```javascript
var path = require('path');


module.exports = {
  entry: [
    path.normalize('es6-shim/es6-shim.min'),
    'reflect-metadata',
    'web-animations.min',
    path.normalize('zone.js/dist/zone-microtask'),
    path.resolve('app/app')
  ],
  output: {
    path: path.resolve('www/build/js'),
    filename: 'app.bundle.js',
    pathinfo: false // show module paths in the bundle, handy for debugging
  },
  module: {
    loaders: [
      {
        test: /\.ts$/,
        loader: 'awesome-typescript',
        query: {
          'doTypeCheck': false
        },
        include: path.resolve('app'),
        exclude: /node_modules/
      },
      {
        test: /\.js$/,
        include: path.resolve('node_modules/angular2'),
        loader: 'strip-sourcemap'
      }
    ],
    noParse: [
      /es6-shim/,
      /reflect-metadata/,
      /web-animations/,
      /zone\.js(\/|\\)dist(\/|\\)zone-microtask/
    ]
  },
  resolve: {
    alias: {
      'web-animations.min': path.normalize('ionic-framework/js/web-animations.min')
    },
    extensions: ["", ".js", ".ts"]
  }
};
```

**Comment by DustinJSilk** [comment]
I compared the folder structure of the JavaScript and TypeScript projects. Seemed the TypeScript App folder was in the www folder. I took it out to match the Javascript version and it started up but showed a blank screen in browser. There are now a few 404 errors on these files:

`http://localhost:8101/build/css/app.ios.css `
`http://localhost:8101/app/app.html `
`http://localhost:8101/favicon.ico `
`http://localhost:8101/build/css/app.ios.css `

There was also this error in the terminal:
`
 ✗ app/app.ios.scss
Error: File to import not found or unreadable: ../../node_modules/ionic-framework/ionic.ios
       Parent style sheet: stdin
        on line 19 of stdin
@import "../../node_modules/ionic-framework/ionic.ios";
  `

**Comment by DustinJSilk** [comment]
Fixed it! 

So after moving the App folder out from the build folder and into the root. I just had to fix all the 404s.
That meant changing the templateUrls on the three pages it starts with from "app/..." to "build/.." and then also remove one level of "../" in the scss files that call for the node_modules folder.

**Comment by mhartington** [comment]
This should be fixed. The typescript branches of the starter projects weren't update. Please try them out and let me know.
