### ISSUE TITLE
Design: mobile web adaptation

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic2#810]
In order to make Ionic 2 apps work *really* well on the mobile web, there are a few design considerations we should keep in mind. I think we could have a "mobile web" mode flag that adds a few additional configuration options to scrolling, side menus, and tabs.

I should note, however, that Ionic apps already work really well in the mobile web, so some of these might not be worth the trouble. Worth thinking through regardless.

### Scrolling 

Perhaps the most important is not relying on sub scroll regions with `-webkit-overflow-scrolling: touch`, and letting the whole page scroll naturally. Unfortunately, inner overflow regions have intermittent issues, like having the whole webpage scroll instead of the inner content (you can see this on Ionic 1 and 2 today). Sometimes scrolling will stop working completely for a bit, and the whole page will rubber band instead.

Additionally, if scrolling doesn't bubble up to the body, Safari's address bar shrinking no longer works.

A way around these issues would be to use the whole body as the scroll area, and add padding or a "shim" element to offset any top nav bars. For example, Google's league standing web apps scroll the whole page, with the top nav being fixed and the inner content having a shim that matches the background color of the nav bar:

<img width="370" alt="screenshot 2015-12-24 14 26 28" src="https://cloud.githubusercontent.com/assets/11214/11997745/5aade018-aa4a-11e5-9fae-6923b2a950b8.png">

One positive to this is that Android "rubber banding" effects work (see the top of the screenshot):

<img width="507" alt="screenshot 2015-12-24 14 29 09" src="https://cloud.githubusercontent.com/assets/11214/11997761/cc124532-aa4a-11e5-9a37-6198c5fd70a4.png">

### Side Menu

Side menu apps don't work well with dragging in the mobile web, because safari/chrome take over the drag gesture for their own use (regrettably). One way we could make them work fine is just disable dragging while in `mobileweb` mode.

### Tabs

Tabs on the footer may or may not work depending on how we address the scrolling issue. If we scroll the whole page, I think tabs will work best sitting at the top, as in the example above.

### Material Design

I think we should default our `mobileweb` look to Material, regardless of the platform. This makes it easy to have taps on top, a design that relies less on owning the whole viewport (like iOS does especially with tab-based designs).

### Others

Any other considerations I might be missing when adapating a native app UI for the mobile web?

**Comment by nihgwu** [comment]
:+1:

**Comment by robwormald** [comment]
Might find addy's notes on PWA's useful btw http://addyosmani.com/blog/getting-started-with-progressive-web-apps/

**Comment by adamdbradley** [comment]
So there are some large challenges with scrolling just the body. If Ionic wasn't a single page app, or it didn't have page transitions this would be easy. However, when transitioning from page1 to page2 (just two divs), they would share the same scrollable area, the body. There would have to be a lot of magic to switch page1 to use a fixed or absolute positioning, and remember it's scroll position. Then page2 would have to be set at the top of the body. Then when transitioning back from page2 to page1, it'd have to switch page1 back to position static, set page2 to position fixed, and place page1 back in the scroll position it was left off at. This is all still doable, but it's going to cause some huge flickers as we're updating the body and changing the position property, causing the entire app to repaint for every transition. Next, page1 and page2 do not just move over at the same rate. For example, iOS will move page1 33% off to the left, and bring in page2 all the way from the right side, both moving at different rates. Material design will come in from the bottom, which is a lot easier, but still a completely different beast.

We'll also have to have each page's header and footer position fixed, and the content is scrollable within the body. That'll work just fine as it does in most simple examples. However, we'll either have to lock in an exact size of a header (same font size, same icon sizes, same button sizes), or dynamically calculate the heights of headers and footers before they come in (DOM read causing potential jank) and adjust the content's padding dynamically (DOM write on the body). And it gets even more complicated with tabs, which can be on the bottom, or top, and can have only text, only icons, text and icons stacked, text and icons with the icons on the left, etc. So again our headers are not just one size, but there are many different sizes that can happen just on a default ionic app, well before users start to adjust it on their own.

We also have to deal with the scrollbar, which we have zero control of, especially for iOS. The scrollbar is going to go bonkers from us changing the body's size, and often times it'll go up over the header and footer which looks pretty ugly. We can hide the scrollbar and provide our own, but then we're adding in another hack of adding padding to the right of the content to get it out of view. What about views that have no padding, or custom padding? Requires a getComputedStyle (DOM read) and padding update (DOM write). Additionally we'll need to have a scroll listener on the body to know where to show our own scrollbar which is another source of jank.

All this aside, we need to make these tricks work for both material design, iOS transitions, modals with child navs, and for both with tabs on top and tabs on bottom (and tabs within tabs within tabs, within a sidemenu within tabs within a modal, etc).

Google's league standing web app is a customized to their one known design, but its transitions are just empty white pages with sometimes animating headers, which I don't think is something Ionic users would accept or looks very native like. It's scrollbars go over the header, and their markup and JS to accomplish these tricks is far from simple.

So, I'd love to scroll just the body, but in practice I'm not sure the pros outweigh the cons.

**Comment by mlynch** [comment]
The main point is that we'd have to change the layout significantly for the best mobile web behavior. It'd be another "mode."

In this mode, tabs on bottom would be disabled, we would use material design only (no iOS styles), we'd maybe change transitions, etc.

Scrollbar going over top is fine IMO, in practice it's not really noticeable on the mobile web (not the case while running as an app).

The transitions seem like the most challenging thing but not insurmountable.

It would change what an ionic app running in the mobile browser "is" for sure

**Comment by jgw96** [comment]
@mlynch We could probably add the mobile web as another platform?
