### ISSUE TITLE
Platform documentation has incorrect links

### ISSUE THREAD

**Issue by Yagger** [driftyco/ionic2#813]
Ionic 2 platform documentation page has incorrect links. It links to */plugins/{plugin-name}, and not */platform/{plugin-name}. Also from this page http://ionicframework.com/docs/v2/ it is not possible to go to platforms plugins. It tries to expand platform plugins, but shows only one - "Storage".

**Comment by mhartington** [comment]
See https://github.com/driftyco/ionic2/issues/301#issuecomment-167262525
