### ISSUE TITLE
Plugins not working

### ISSUE THREAD

**Issue by Yagger** [driftyco/ionic2#815]
Platform plugins are not working. I do exactly as docs spec, for example Camera plugin: http://ionicframework.com/docs/v2/platform/camera/
1. $ ionic plugin add cordova-plugin-camera
2. import {Camera} from 'ionic/ionic'
3. Camera.getPicture({...})

The error is this: "Cannot read property 'getPicture' of undefined".
This is not specific to Camera plugin, because same happens with other plugins, like Vibration for example.

The only plugin that worked for me is Keyboard, but it did not require a plugin, it just importable from 'ionic/ionic' and injectable in constructor. I found the Keyboard using sample in forums somewhere, while according to docs http://ionicframework.com/docs/v2/platform/keyboard/ it is not injectable. So is the plugin supposed to be injectable or not? If not, then how do we test such code?

How exactly Camera is supposed to be exported by 'ionic/ionic'? Where 'plugin add' command places the Camera code so that it is available via 'ionic/ionic'.

My ionic-cli version is 2.0.0-beta.12
Ionic Framework version is 2.0.0-alpha.42
Angular version is 2.0.0-alpha.52

P.S. Platform docs need fixes. It is not possible to get from http://ionicframework.com/docs/v2/ to http://ionicframework.com/docs/v2/platform. And if you do get to http://ionicframework.com/docs/v2/platform/, then link won't work.

**Comment by Yagger** [comment]
I see this one is related to https://github.com/driftyco/ionic2/issues/531.
Does anybody have a sample on how to write custom wrapper, i.e. how to use installed plugin inside Ionic 2 project?

**Comment by mhartington** [comment]
You shouldn't need a custom wrapper for the moment. You can use the raw plugin API, so `window.Camera`.

**Comment by mhartington** [comment]
Note that we are working on a better solution for the future, but that is still a work in progress

**Comment by Yagger** [comment]
Sounds good! Haven't used raw API before, so that hint helped, thanks!
One thing for someone looking for similar solution in future, seems that its `navigator.camera`, not `window.Camera`. But refer to docs for exact usage of certain plugin: https://cordova.apache.org/plugins/?q=camera

**Comment by trucle** [comment]
+1
