### ISSUE TITLE
How to pinch to zoom image in the Slider?

### ISSUE THREAD

**Issue by kitkimwong** [driftyco/ionic2#816]
i am using the example in :
https://github.com/driftyco/ionic2/tree/master/ionic/components/slides/test/basic

And i want to pinch to zoom the image in the Slider so that i add the class  ion-scroll-zoom  in the slides. But it seems not work. 

    <ion-slides [options]="extraOptions" id="slider" style="background-color: black" class="ion-scroll-    zoom">
      <ion-slide *ngFor="#image of images">
        <img data-src="{{getImageUrl(image)}}" slide-lazy>
      </ion-slide>
    </ion-slides>

**Comment by brandyscarney** [comment]
This is not added yet, but the way to do it would be to add the `zoom` property to the `ion-slides`:

```
<ion-slides [options]="extraOptions" id="slider" zoom>
```

**Comment by kitkimwong** [comment]
@brandyscarney  I have test "zoom" with the example:
https://github.com/driftyco/ionic2/tree/master/ionic/components/slides/test/basic

But it is not work, test in android 4.4.4 and 5

**Comment by brandyscarney** [comment]
*This is not added yet*, so it will not work. We have to implement it still.

**Comment by kitkimwong** [comment]
Ok, thank you for your reply. Wait your team's good news.

**Comment by brandyscarney** [comment]
:+1: I'm going to reopen this issue to get it added.

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5039
