### ISSUE TITLE
Error: `libsass` bindings not found. Try reinstalling `node-sass`?

### ISSUE THREAD

**Issue by herve1976** [driftyco/ionic2#817]
After upgrading to ionic2 I get this error:

Error: `libsass` bindings not found. Try reinstalling `node-sass`?

$ ionic info

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.0
Ionic CLI Version: 2.0.0-beta.15
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.2 Build version 7C68

**Comment by mhartington** [comment]
Looks like you need to bump your node version to 4.2x.
Please update node and reinstall ionic@beta.

**Comment by mhartington** [comment]
Any luck on updating your node version?

**Comment by Ionitron** [comment]
Greetings @herve1976!

My sensors indicate a reply was requested, but as we have not received one yet, I am using my robot powers to close this issue. However, if you are still experiencing this issue, please feel free to reopen it by creating a new issue, and include any examples or necessary information.

Thank you for allowing me to assist you.
