### ISSUE TITLE
Segment is not getting correct value when clicked

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#819]
![screen shot 2015-12-28 at 3 35 28 pm](https://cloud.githubusercontent.com/assets/6577830/12025045/a8f69900-ad78-11e5-98a8-d099ef737f3f.png)

**Comment by zakir2k** [comment]
agreed. and the segment the user switches to gets the css class 'activated' instead of 'segment-activated'

**Comment by brandyscarney** [comment]
This is fixed in the latest release - alpha.46. 

`npm install ionic-framework@latest --save` to get the latest **or** 

`npm install ionic-framework@2.0.0-alpha.46 --save` to get the exact version.

**Comment by rejithomas** [comment]
Please get this patched to beta as well

**Comment by brandyscarney** [comment]
@rejithomas We are not yet in beta. Ionic 2 is still in alpha. You may be thinking of the CLI as that is on a beta version in order to work with Ionic 2. There's a general overview here: http://ionicframework.com/docs/v2/resources/using-npm/

**Comment by rejithomas** [comment]
@brandyscarney thanks for clarifying. The framework update works. :+1:
