### ISSUE TITLE
Tooling doesn't reflect new project structure

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic2#824]
Generating a new page uing `ionic g page` will generate a new page in www/app, not app/
Should be a simple fix.
Also add abaility to generate typescript equivalent code.

**Comment by Luchillo** [comment]
I put an incomplete pull request for this and saw other pull reques facing this issue better:
https://github.com/driftyco/ionic2/pull/802 => mine, incomplete.
https://github.com/driftyco/ionic2/pull/822
https://github.com/driftyco/ionic2/pull/825

**Comment by mhartington** [comment]
Yes, I know. 
There was no issue to track.

**Comment by tlancina** [comment]
This should be fixed in the next release, opened a separate issue for typescript generators: https://github.com/driftyco/ionic2/issues/892
