### ISSUE TITLE
How to integrate Native components in Ionic2

### ISSUE THREAD

**Issue by ajaybeniwal** [driftyco/ionic2#828]
Hi There is no guide about integration to Native Cordova Plugins like camera in the official docs site , so can you explain how we could integrate Third party cordova plugins to the app

**Comment by nihgwu** [comment]
native cordova plugins have nothing to do with ionic, why cant you just follow the official docs of the plugins, or you can wrap your own plugin service just like ngCordova does

**Comment by ajaybeniwal** [comment]
I know Ionic has nothing to do with cordova,  but I read there blog that they are creating a new service for wrapping Cordova APIS  https://github.com/driftyco/ionic-native, so I just wanted to confirm is it correct way to wrap Cordova layers in Ionic 2 , I do not want to reinvent the wheel by creating my own wrappers

**Comment by mlynch** [comment]
Yes, that is going to be our official library going forward. We'd love any pull requests to add new plugins!
