### ISSUE TITLE
Add Right To Left Support

### ISSUE THREAD

**Issue by mashaly100200** [driftyco/ionic2#832]
kindly add support rtl to animation and the components

**Comment by adamdbradley** [comment]
Yes this is on our roadmap to complete and we would love to get more feedback from experienced RTL dev's to help us point out where we need to improve. Would you be able to provide a checklist of certain parts of ionic2 that do not work well with RTL. Our goal would be to provide an additional RTL css file, and have any JS adjust accordingly depending if the html element has `dir="rtl"` or not. Thanks

**Comment by mashaly100200** [comment]
It's my pleasure to help ionic2 team to support RTL 
firest it's easy to watch what are the bad effects if we use rtl direction
we can add this attr to html tag that will convert all website to to rtl 
<html dir="rtl" lang="ar">
or
we can use it in the body as a style like this
style="direction:rtl" 

if ionic team plan to support rtl

thay will need to add the target direction in App configurations , because the application will need to know what is the direction on the start up 
, and if the developer need to change the app language to rtl language in runtime then we should refresh all app (like native android,windows phone app , ios need to restart the application to change it's direction)


now when i try to change ionic2 html direction i found that there are things aleady support rtl direction coz pure html konw how to deal with rtl direction
but thare are things need to be support rtl direction
first thing is animation
i donn't know if ionic team do the animation with css or javascript code , in both cases all animation witch have rtl or ltr  will need to add another animation direction , not only change varialbe but add another one coz many things will need to change


I would like to provide assistance as i can to ionic team to help in this great library 

i know my English is not good , but i hope you understand my words :)

**Comment by mashaly100200** [comment]
plz change this goal  " Our goal would be to provide an additional RTL css file "
because we need the two direction in the same application , based on the user's choice , some time it will be in runtime

**Comment by adamdbradley** [comment]
> we need the two direction in the same application , based on the user's choice , some time it will be in runtime

Ionic itself will be able to dynamically add this css file for you, depending on the `<html dir="rtl">`

**Comment by mashaly100200** [comment]
these imgs from trying to change direction of onic-conference-app example
if ionic team cover the rtl direction in this example  i think it will be ont less than 90% of rtl support

![Image of Yaktocat](http://imageshack.com/a/img903/3/BO4pib.png)

**Comment by mashaly100200** [comment]
![Image of Yaktocat](http://imageshack.com/a/img910/6199/m4CPLa.png)

**Comment by mashaly100200** [comment]
![Image of Yaktocat](http://imageshack.com/a/img905/3990/IB20Mo.png)

**Comment by mashaly100200** [comment]
![Image of Yaktocat](http://imageshack.com/a/img633/2823/dKcEMJ.png)

**Comment by mashaly100200** [comment]
any icon which are right,left,back or forward arrow like back-button icon will need this style
{
    -webkit-transform: rotate(180deg);
    -moz-transform: rotate(180deg);
    -o-transform: rotate(180deg);
    -ms-transform: rotate(180deg);
    transform: rotate(180deg);
}

**Comment by adamdbradley** [comment]
So @brandyscarney had a good idea that we create all the RTL scss files within the repo and get them ready to be filled. 

I was thinking that instead of dynamically adding another rtl css, we could have a default `$rtl-support: false` sass variable that can be updated in each app's sass variables. So in most cases the extra rtl css wouldn't be added to apps, but for those who require the rtl css they can set `$rtl-support: true`.

Then within our new rtl scss files, the css can be wrapped with `@if $rtl-support`. This way we can keep the css files separated and easier to edit, and provide rtl support out of the box. Think this will work @mashaly100200 ?

**Comment by mashaly100200** [comment]
yes load rtl  dynamically is a good idea ,

let us start with animation , coz it may be need more effort 

- i want to know is it personal to add specific page transition animation when do  push and pop  pages ?
- and how developer add this specific animation to the tow pages witch enter and leave ?

- can developer watch back button event then add his specific animation also to the two pages ?

if your answer are yes for the previous three questions , then i  can congratulate my self coz animation topic don't need any effort and full support rtl direction and ionic team deserve a very big thanks  :)

**Comment by adamdbradley** [comment]
This is the transition animation for ios: https://github.com/driftyco/ionic2/blob/master/ionic/animations/ios-transition.ts

Not sure if this should add logic for RTL, or if there should be a new animation instead. You can however add your own transition, and override the `pageTransition` config: https://github.com/driftyco/ionic2/blob/master/ionic/config/modes.ts#L24

**Comment by mashaly100200** [comment]
hi @adamdbradley , merry christmas

i finished a custom animation class which reverse the default animation class behavior depend on documen.dir  
https://gist.github.com/mashaly100200/bf713f2b558285322155
 i tested it , and i will test it in real projects soon (inshaa allah) 

also i finished some of css classes that was need to be reversed 
https://gist.github.com/mashaly100200/dc23529e570034b0dfb9

and if i face more classes need to be reversed , i will add it to this file until i finish one or two real project  

also rtl need these configurations in app constructor
https://gist.github.com/mashaly100200/692160b036422d7b018c

i was trying to add all configuration in one place so i found that i can add all things in the app contractor

hope these things can help to make ionic2 fully support rtl    

Please feel free to add any corrections or suggestions .

**Comment by adamdbradley** [comment]
Cool, so it looks like the RTL transition is pretty darn close to the LTR transition, which makes me think it should be an `isRTL` option that gets passed into the transition's options and we only have one transition. I can update ionic so it has a common `isRTL` property that can be referenced throughout the app (with webworkers we want to avoid doing `document` reads within ionic's logic).

**Comment by adamdbradley** [comment]
Added `isRTL() to `Platform': https://github.com/driftyco/ionic2/blob/0b4b8628bf87cabab92d6563bf9878db8b86c885/ionic/components/modal/test/basic/index.ts#L16

**Comment by adamdbradley** [comment]
All transitions are now passed `isRTL` within the `opts`: https://github.com/driftyco/ionic2/blob/da986a5fb0ee2c7660ad4494731b5fe98b393812/ionic/components/nav/nav-controller.ts#L798

So now the ios-transition can add the logic for RTL transitions.

**Comment by adamdbradley** [comment]
Added how we can include RTL css so it correctly builds within ionic.css (which includes both md and ios css) and ionic.ios.css (just ios). The thought is that apps which want to include both RTL and LTR css within the same file can set `$include-rtl: true` in their sass variables, otherwise it'll default to only include LTR css. https://github.com/driftyco/ionic2/blob/f38ad4a7d2d8c527a3bc64fd8569b11eb659c290/ionic/components/item/item.ios.scss#L231

**Comment by MatanYed** [comment]
Just you to know: RTL apps in iOS are partly LTR:
Primary navbar button side is left, side menu is left, transition animation is from left to right.

**Comment by adamdbradley** [comment]
Added new methods to platform to get and set language and direction: https://github.com/driftyco/ionic2/commit/942bd9b93b97a88554aafc9972c1c2d86de9273f

**Comment by mashaly100200** [comment]
update
for anyone flow this topic 
replace 
 config.set('backButtonIcon', 'ion-ios-arrow-forward');
with
 config.set('backButtonIcon', 'arrow-forward');

also i update the animation class
https://gist.github.com/mashaly100200/bf713f2b558285322155

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5035
