### ISSUE TITLE
Add angular dependency to changelog in ionic-framework.apha45

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic2#834]
`ionic-framework.alpha45` uses `angular2-beta.0` which now forces `di` to be used like this:
Before: import http from 'angular2/angular2'
After: Before: import http from 'angular2/core'

This should be stated in changelog or in the docs, i know ionic 2 is changing quick but this could save some time to noobs basing their work on other people's outdated tutorials or posts.

**Comment by mhartington** [comment]
Good idea, thanks! Once things become a lot more stable, this should be an issue, but can definitely see it causing some confusion. Going to close this for now though.

@brandyscarney something to note for when we setup automatic changelog generation.
