### ISSUE TITLE
navController not available in callback

### ISSUE THREAD

**Issue by PierrickI3** [driftyco/ionic2#836]
I am using a fork of the conference sample app (https://github.com/driftyco/ionic-conference-app).

I added some logic to login to my system from the login page and I use a callback when the login succeeds. However, I can't use this.nav.push from that callback. I get the following error:

```
9     978340   error    EXCEPTION: TypeError: Cannot read property 'nav' of undefined
```

My code is as follows:

```javascript
login() {
  this.icws.init('ionic test app', 'http://', 'test-windows', '8018', 'vagrant', 'vagrant');
  this.icws.login('vagrant', '1234', this.success, this.error);
}

success(status, response) {
  console.log('Success');
  this.nav.push(TabsPage);
}
```

The error occurs at this.nav.push(TabsPage);

If I move that line to login(), it works. I am guessing this is because the callback is on a different thread. How can I use the navController from a callback function?

Thanks.

**Comment by Luchillo** [comment]
Wow that's totally weird, maybe being called from a callback breaks `this` context, that's a thing with js closures, maybe try calling the callback function with bind to set the `this` context correctly?

**Comment by Luchillo** [comment]
A possible fix is to use promises to avoid using callbacks so that the `success` function can be called inside the login class and not inside the `icws.login()` function.

**Comment by adamdbradley** [comment]
Yes I think @Luchillo is right and the same `this` context isn't being used. I'd recommend `bind` or having your callback arguments within `login` wrap your `success` method with another function using a reference to the correct `this`.

**Comment by PierrickI3** [comment]
Thanks guys. I haven't had a chance to test this yet due to heavy workload but I will update this when I am done. This does make sense so this should work.
