### ISSUE TITLE
ionic build --release android now gives a parse error after installation on device

### ISSUE THREAD

**Issue by krz37** [driftyco/ionic2#837]
On beta 15, when I compile with ionic build --release android and install the package, the package won't install and I get a "parse error".
This did not happen in the beta 2 weeks back.
ionic build android debug output works normally.

**Comment by tlancina** [comment]
Are you signing your apk? I don't believe you can install an unsigned release apk to the device.

**Comment by krz37** [comment]
Oh my bad, it's true I have never done that before, for the purpose of quick testing I made this mistake
