### ISSUE TITLE
SqlStorage WebSQL select queries are not working

### ISSUE THREAD

**Issue by phavre** [driftyco/ionic2#839]
When using SqlStorage (WebSQL) there's an issue in the query function but only for the select queries. Indeed, create table and insert statements are well executed, but select queries always return empty resultset. Whatever the query format it's impossible to get a resultset not empty.

Here the example code:
`    this.storage = new Storage(SqlStorage, {backupFlag:"BACKUP_LIBRARY"});`
`    this.storage.query("select key from kv", []).then (response => console.debug("select: "+JSON.stringify(response)));`
`    this.storage.get("ABATIS").then (response => console.debug("get ABATIS key: "+JSON.stringify(response)));`

And the console output:
`Storage: SQLite plugin not installed, falling back to WebSQL. Make sure to install cordova-sqlite-storage in production!`
`app.bundle.js:5221 Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.`
`select: {"tx":{},"res":{}}`
`get ABATIS key: "1"`

The content of the kv table:
![image](https://cloud.githubusercontent.com/assets/16475287/12068967/cf3431e6-b01a-11e5-8240-8f67c9271162.png)

versions:
Cordova CLI: Not installed
Ionic Version: 2.0.0-alpha.45
Ionic CLI Version: 2.0.0-beta.15
Ionic App Lib Version: 2.0.0-beta.8
OS: Windows 7 SP1
Node Version: v5.3.0

**Comment by mlynch** [comment]
You have my word this will get fixed 🍻

**Comment by mlynch** [comment]
Although, read this quick, maybe you're using the API incorrectly? https://blog.nraboy.com/2015/12/use-sqlite-in-ionic-2-instead-of-local-storage/

If not I'll check it out when I'm more sober

**Comment by phavre** [comment]
Please take time to enjoy the new year (happy one by the way) for I'm not sure if the issue comes from not actually using sal lite but web SQL. Misconfiguration on my side ? Or it is s actually only usable when installed on the phone ? last of all I have to make sure my calls are made after the platform has been initialised but as all the other queries where functioning I guessed it was not the origin of the issue. 
cheers.

**Comment by phavre** [comment]
Hi, I've followed the blog but still have the same issue here. The last difference is that I'm not on my phone, just on my browser with ionic serve (and hence with WebSQL instead of sqllite). Is it related ?

**Comment by mlynch** [comment]
I tested this and it works for me. You want to grab the rows object like this:

```javascript
        this.sql.query('SELECT name FROM test_table').then(resp => {
          console.log('SELECT REST', resp.res.rows);
        })
```

Does that fix it for you?

**Comment by TheBosZ** [comment]
@phavre Make sure you're using a browser that supports WebSQL. For example, Firefox doesn't.

**Comment by phavre** [comment]
yeah @mlynch it did fixed it. Thanks a lot. Still have the warning message about the sqlite missing but I guess this is normal when testing it on the browser without the cordova sqlite plugin
