### ISSUE TITLE
Create a TSD file for editors

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic2#84]
We may have to make a PR to add this once V2 gets further along.

https://github.com/borisyankov/DefinitelyTyped

Trying to use typescript with the stater project requires a definition file.

**Comment by v4results** [comment]
What is the status on this one?

**Comment by tlancina** [comment]
@v4results still on our list of things to do, but doesn't have priority at the moment.

**Comment by vovikdrg** [comment]
Any news on that?

**Comment by mhartington** [comment]
>still on our list of things to do, but doesn't have priority at the moment.

**Comment by vovikdrg** [comment]
I did not see that comment was posted 2 hours ago. But still would like to see this done too :+1:

**Comment by prolink007** [comment]
I keep getting "TS2307: Cannot find module 'ionic/ionic'" when trying to use `tsc` with my project. I am assuming this is related to this issue. Is there a current work around?

**Comment by jksoftpro** [comment]
For anyone looking for Ionic2 Type Definition please follow this link:
https://github.com/jksoftpro/ionic2-seed/blob/master/tools/typings/ionic2.d.ts

I created this one for version "ionic-framework": "2.0.0-alpha.36". It works well for me. I hope it will help.

**Comment by robwormald** [comment]
Creating a complete `d.ts` bundle is probably a bad idea, fwiw. See https://github.com/angular/angular/issues/5248#issuecomment-156886060 for a bit of detail on why.

**Comment by mhartington** [comment]
Thanks @robwormald, wasn't aware of these changes either. 

@jksoftpro thanks for the attempt, but we would rather have the typings come from us so that way there is no confusion once v2 is released.

**Comment by vovikdrg** [comment]
@mhartington but as I understand for now there is no d.ts yet ?:) so its better to have unofficial than have nothing :)

**Comment by tobiasmuecksch** [comment]
So - as @prolink007 asked: is there a current work around? I'd love to not rely on the ionic2 starter.

**Comment by prolink007** [comment]
@tobiasmuecksch I just updated to "ionic-framework": "2.0.0-alpha.38". This seems to have resolved the issue for me.

**Comment by tobiasmuecksch** [comment]
@prolink007: Im using this exact version and I still get the error described above.

**Comment by prolink007** [comment]
@tobiasmuecksch Can you post your package.json? Maybe something else is different.

**Comment by vovikdrg** [comment]
Just to note in angular now tsd are part of npm package. I am not sure about latest ionic did not checked that.

**Comment by tobiasmuecksch** [comment]
@prolink007 

{
  "name": "app",
  "version": "1.0.0",
  "description": "",
  "main": "gulpfile.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "none",
  "devDependencies": {
    "gulp": "^3.9.0",
    "gulp-clean": "^0.3.1",
    "gulp-compass": "^2.1.0",
    "gulp-concat": "^2.6.0",
    "gulp-shell": "^0.5.1",
    "gulp-tsc": "^1.1.4",
    "typescript": "^1.7.3"
  },
  "dependencies": {
    "ionic-framework": "^2.0.0-alpha.38"
  }
}

**Comment by prolink007** [comment]
@tobiasmuecksch Try dropping down to `"typescript": "1.5.3",`. That is the version i am using. Upgrading to 1.7.3 caused other issues for me. Not saying it will fix the issue, but that is what is working for me. =)

**Comment by tobiasmuecksch** [comment]
Well, typescript 1.5.3 did the trick as far as I can see. But this shouldn't be a permanent solution I guess.

**Comment by prolink007** [comment]
@tobiasmuecksch I agree. I was hoping to update to the new version, but that does not appear to be possible at the moment.

**Comment by tlancina** [comment]
Latest `ionic-framework` ships with `.d.ts` files alongside their CommonJS sources.

**Comment by nraboy** [comment]
I'm still experiencing the problem.  I tried dropping my typescript to 1.5.3, but it didn't resolve it.  Were there other things that had to be done on my end?

Thanks,

**Comment by tlancina** [comment]
Hey @nraboy, `npm install -g ionic@beta`, then `ionic start myapp --v2 --ts` should get you up and running with a Typescript version of the tabs starter.  Keep in mind a lot of the framework typings are still a WIP, but you can open that project up in something like VSCode or using the atom-typescript plugin and get code completion, error checking, etc.

**Comment by nraboy** [comment]
Hey @tlancina that is the approach I took.  My atom-typescript plugin is complaining about several lines.

I figured what the hell and tried to build the project anyways.  Got a bunch of errors.  Here is my setup.

Cordova CLI: 5.4.1
Ionic Version: 2.0.0-alpha.42
Ionic CLI Version: 2.0.0-beta.12
Ionic App Lib Version: 2.0.0-beta.6
ios-deploy version: Not installed
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.2 Build version 7C68 

Anything look questionable?

**Comment by tlancina** [comment]
Doesn't sound like you're doing anything wrong.  The starters haven't been completely typed yet, so some of the types are missing, which will make atom-typescript complain.  I believe the most type complete starter is the conference app: `ionic start myapp conference --v2 --ts`.

A big issue is that there are errors (break the build) and then there are type errors.  Both look scary, but type errors are just the typescript compiler yelling at you (which it likes to do), but really are more like warnings and don't actually affect the output of the build.

They will get fixed eventually, but are lower priority since, although annoying, they don't break anything and we have plenty of broken things to be fixing still :)

**Comment by nraboy** [comment]
Here is my full log:

```
macbookpro:ExampleProject nraboy$ ionic build ios
∆ Compiling and bundling with Webpack...
√ Using your webpack.config.js file: /Users/nraboy/Desktop/ExampleProject/webpack.config.js 
Unhandled rejection TypeError: Cannot read property 'NodeJs' of undefined
    at buildEnumMap (/Users/nraboy/Desktop/ExampleProject/node_modules/awesome-typescript-loader/dist.babel/tsconfig-utils.js:48:48)
    at Object.rawToTsCompilerOptions (/Users/nraboy/Desktop/ExampleProject/node_modules/awesome-typescript-loader/dist.babel/tsconfig-utils.js:63:29)
    at Object.ensureInstance (/Users/nraboy/Desktop/ExampleProject/node_modules/awesome-typescript-loader/dist.babel/instance.js:127:32)
    at _callee2$ (/Users/nraboy/Desktop/ExampleProject/node_modules/awesome-typescript-loader/dist.babel/index.js:64:47)
    at tryCatch (/Users/nraboy/Desktop/ExampleProject/node_modules/awesome-typescript-loader/node_modules/babel-polyfill/node_modules/babel-regenerator-runtime/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/nraboy/Desktop/ExampleProject/node_modules/awesome-typescript-loader/node_modules/babel-polyfill/node_modules/babel-regenerator-runtime/runtime.js:329:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/nraboy/Desktop/ExampleProject/node_modules/awesome-typescript-loader/node_modules/babel-polyfill/node_modules/babel-regenerator-runtime/runtime.js:94:21)
    at step (/Users/nraboy/Desktop/ExampleProject/node_modules/awesome-typescript-loader/dist.babel/index.js:30:41)
    at /Users/nraboy/Desktop/ExampleProject/node_modules/awesome-typescript-loader/dist.babel/index.js:33:9
    at tryCatcher (/Users/nraboy/Desktop/ExampleProject/node_modules/awesome-typescript-loader/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/nraboy/Desktop/ExampleProject/node_modules/awesome-typescript-loader/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/Users/nraboy/Desktop/ExampleProject/node_modules/awesome-typescript-loader/node_modules/bluebird/js/main/promise.js:70:37)
    at __awaiter (/Users/nraboy/Desktop/ExampleProject/node_modules/awesome-typescript-loader/dist.babel/index.js:8:12)
    at compiler (/Users/nraboy/Desktop/ExampleProject/node_modules/awesome-typescript-loader/dist.babel/index.js:51:12)
    at Object.loader (/Users/nraboy/Desktop/ExampleProject/node_modules/awesome-typescript-loader/dist.babel/index.js:47:14)
    at WEBPACK_CORE_LOADER_EXECUTION (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
√ Compiling files complete.

./www/app/app.ts
Module build failed: Error: Final loader didn't return a Buffer or String
    at DependenciesBlock.onModuleBuild (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:299:42)
    at nextLoader (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at runSyncOrAsync (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:159:13)
    at nextLoader (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:76:16
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16
    at fs.js:334:14
    at /Users/nraboy/Desktop/ExampleProject/node_modules/awesome-typescript-loader/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:42:10
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/webpack/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:42:10
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/ionic-cordova-lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:42:10
    at FSReqWrap.oncomplete (fs.js:95:15)
 @ multi main (CLI v2.0.0-beta.12)
```

It appears the ts files are only being compiled if I do so manually since Atom doesn't like what's going on.

Should I ditch TypeScript or wait?  I only want to learn one way of doing things when coming to Angular 2.

**Comment by tlancina** [comment]
@nraboy that error looks like it's coming from here: https://github.com/s-panferov/awesome-typescript-loader/blob/master/src/tsconfig-utils.ts#L67, which would make me guess you downgraded your Typescript version in your project.

If you want to use Typescript 1.5 I believe it still works, but you'll need to install an earlier compatible version of awesome-typescript-loader.

**Comment by nraboy** [comment]
Ah you're right about that one.  I did downgrade incorrectly.

It did build and deploy the tabs project when I started fresh, even with the TypeScript errors, however, it is not correct.  See the attached image:

![simulator screen shot dec 17 2015 8 36 41 am](https://cloud.githubusercontent.com/assets/983958/11875449/7ab9e9d0-a499-11e5-95f9-352a1802edb5.png)

**Comment by mhartington** [comment]
@nraboy could you tell me what steps you did to get to this point?

**Comment by nraboy** [comment]
```
ionic start ExampleProject --v2 --ts
cd ExampleProject
ionic platform add ios
ionic build ios
ionic emulate ios
```

Seem correct?

**Comment by mhartington** [comment]
Could you run `gulp sass` before emulating. Seems that `ionic build` doesn't run gulp as well as webpack. This should be fixed.

**Comment by nraboy** [comment]
That seems to be better, however it still looks wonky.

Look a the tabs.  Is that how they should look?

![simulator screen shot dec 17 2015 8 50 16 am](https://cloud.githubusercontent.com/assets/983958/11875807/5005b7ee-a49b-11e5-909b-f023c65ce334.png)

**Comment by mhartington** [comment]
@nraboy can you make a new issue. This isn't relevant to the original thread anymore.

Thanks,

**Comment by tlancina** [comment]
Yeah starters don't ship with a build hook, only serve. Opened a new issue: https://github.com/driftyco/ionic2/issues/766.

Closing and locking.
