### ISSUE TITLE
Clicking a radio button in a group without values selects all options visually

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#843]
```
<ion-list radio-group>
   <ion-list-header>
       Options
   </ion-list-header>
   <ion-radio>
      Option 1
   </ion-radio>
   <ion-radio>
       Option 2
   </ion-radio>
   <ion-radio>
       Option 3
   </ion-radio>
   <ion-radio>
      Option 4
  </ion-radio>
</ion-list>
```

![screen shot 2016-01-01 at 3 19 07 pm](https://cloud.githubusercontent.com/assets/6577830/12072054/1cfcf932-b09b-11e5-8a7a-dc50794a5d46.png)

**Comment by drewrygh** [comment]
After setting a `value` on each toggle, now whenever any toggle is tapped, the last toggle in the list will always be selected.

I checked out the e2e tests and (assuming they work), the only difference is they have an `ngControl` `attribute. Is this required now? I'll look in to it more tomorrow.

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5033
