### ISSUE TITLE
ion-menu is hanging app when closing (type=overlay)

### ISSUE THREAD

**Issue by KabluBR** [driftyco/ionic2#844]
Just open and close menu in ANDROID and it hangs

This sample have the same issue:
http://ionicframework.com/docs/v2/api/components/menu/Menu/

It freezes just when type is OVERLAY, when type is set to REVEAL it works fine

**Comment by brandyscarney** [comment]
Is the backdrop there? Possible duplicate of #803

**Comment by KabluBR** [comment]
Yes maybe this is the same issue.

In 803 you mention:
" I didn't see any negative results of removing this code in any of my tests, so it will be in the next release."

But I think you'd tested only with type=reveal and not overlay.

If you use type=reveal in menu it works, it is a bug with overlay type.

**Comment by brandyscarney** [comment]
That was a comment about removing the animation transform CSS which fixed the overlay. I tested on all menu types and it worked fine removing that code. The issue is fixed but we haven't created a new release yet, so the bug will remain until we release.

**Comment by KabluBR** [comment]
ok thanks
