### ISSUE TITLE
Add Chip UI Component

### ISSUE THREAD

**Issue by swarthout** [driftyco/ionic2#846]
I was wondering if you would consider adding the chip ui component to ionic 2. As described below, this component is very useful for making messaging apps or for adding tags to posts or comments. It can be approximated in Ionic right now using a round button and an icon, but it does not come with useful properties like a delete behavior. Below are links to the material design spec detailing the chip and a less implementation from framework7. If you are interested in this feature I could possibly provide a pull request with an initial angular2 implementation. What do you think?

Material Design Spec:
https://www.google.com/design/spec/components/chips.html#
Framework7 implementation:
https://github.com/nolimits4web/Framework7/blob/master/src/less/material/chips.less

Thank you!

**Comment by brandyscarney** [comment]
I think it's a great idea. It can go in `/ionic/components/chip`. If you'd like to provide a PR with an initial implementation that would be extremely helpful. :smile: We have some docs on running the source code here: https://github.com/driftyco/ionic2/blob/master/scripts/README.md#building--running-ionic-source

**Comment by jgw96** [comment]
I think this is an awesome idea! @swarthout would you like some help on that PR?

**Comment by swarthout** [comment]
I am glad you all have been so positive about this suggestion! As far as implementation, I have looked at the work done by @3dd13 and I support it and feel like our time should be spent reviewing their pull request. I plan on testing it and giving more comments there
