### ISSUE TITLE
Popup input field does not auto focus

### ISSUE THREAD

**Issue by joshuamorony** [driftyco/ionic2#847]
When a popup is triggered using the following code:

```javascript
  	let options = {
  		title: 'test',
  		subTitle: 'test',
  		okText: 'test'
  	};

  	this.popup.prompt(options).then((result) => {

  	});
```
The input field is not auto focussed, the user must tap the input field to trigger the input and keyboard to appear.

**Comment by adamdbradley** [comment]
Alert has been updated to auto-focus and will be in alpha47: https://github.com/driftyco/ionic2/blob/master/ionic/components/alert/alert.ts#L288

**Comment by joshuamorony** [comment]
Auto focus works in the browser in alpha47, but not when running on iOS (Android not tested).

**Comment by tlancina** [comment]
@joshuamorony you may need to set the `KeyboardDisplayRequiresUserAction` Cordova preference to 'false' in your config.xml: https://cordova.apache.org/docs/en/5.4.0/guide/platforms/ios/config.html.

I don't believe Android allows autofocus without a user touch, so you'll need to use the Keyboard plugin to force show the keyboard.  If you need a keyboard type that isn't the default like tel or number, you may want to take a look at the discussion in https://github.com/driftyco/ionic-plugin-keyboard/issues/45. I believe someone came up with a plugin that faked touches natively to focus any kind of input programmatically.

**Comment by joshuamorony** [comment]
Excellent, that did it. Thanks Tim.
