### ISSUE TITLE
Search bar icon overlaps with placeholder

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#853]
![image](https://cloud.githubusercontent.com/assets/452425/12096010/010a0d66-b2d8-11e5-91a9-483930d3ba17.png)

**Comment by brandyscarney** [comment]
I was able to reproduce this in a new test `nav`. It is caused by the searchbar icon width being 0 when it is called.

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5029
