### ISSUE TITLE
Rename <icon> to <ion-icon>

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#855]
Personally not a huge fan, cuz it's longer, but `<icon>` is the only directive without the `ion-` prefix. Additionally, standards state that components like this should always have a dash `-` in it, whereas standardized HTML elements will never have a dash in it.

Next, I think we'll have to always go with a `name` or `svg` attribute with a value, rather than just `<icon star></icon>`. Basically it become impossible to tell which attribute is the actual icon when you start adding other attributes to icon, such as color attributes which users could use any name. https://github.com/driftyco/ionic2/pull/703

Same for when we start using SVGs, we'll want to use a property instead of an attribute. `<ion-icon svg-file="/imgs/star.svg"></ion-icon>` or `<ion-icon svg="star"></ion-icon>`

So, `<icon home></icon>` becomes `<ion-icon name="home"></ion-icon>` (hate it cuz it's longer, but it is more clear). Additionally, it makes it easier for devs to dynamically set the icon, such as `<ion-icon [name]="iconName"></ion-icon>`.

Thoughts? @mlynch @brandyscarney

**Comment by brandyscarney** [comment]
Yeah I think it should be renamed to be more consistent. We could always call it `<ion-ionicon>`. :trollface:

But seriously, I think it's more clear and better since there are issues knowing which attribute does what. So yeah, :+1:

**Comment by mlynch** [comment]
Ship it

**Comment by phavre** [comment]
agree. The first time I needed an icon I used the <ion-icon> tag and didn't understand why nothing where redered lol
