### ISSUE TITLE
Give elements inside of an item a unique class based on the element

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#856]
For example, if a button is inside of an item it should get the `item-button` class (similar to how toolbar adds a `bar-button` class). 

* button/[button] - `item-button`
* icon - `item-icon`

This way we can style them based on this class, and only use `item-left` or `item-right` for placement.

**Comment by adamdbradley** [comment]
Child icons now receive `.item-icon` and child buttons get `.item-button` in this branch:

https://github.com/driftyco/ionic2/tree/item-buttons

**Comment by brandyscarney** [comment]
This is done. We only added the classes for buttons & icons which cleaned up a lot of the CSS.
