### ISSUE TITLE
Can't dynamically change icon once it is rendered

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#864]
If you try to change an icon after it has already been rendered (such as on a button click) the proper class doesn't get added and it doesn't change. To reproduce:

1. open up [http://localhost:8000/dist/e2e/item/icons/#](http://localhost:8000/dist/e2e/item/icons/#)
2. modify / add the following in the html:

  ```
  <a ion-item href="#">
    a[ion-item] w/ right side large icon
    <icon large [name]="myIcon" item-right></icon>
  </a>

  {{myIcon}}

  <button (click)="changeToCheck()">Change Icon</button>
  ```

3. add the following JS:

  ```
  constructor() {
    this.myIcon = "information-circle";
  }

  changeToCheck() {
    this.myIcon = "checkmark";
  }
  ```

**Comment by adamdbradley** [comment]
This should be fixed with this: https://github.com/driftyco/ionic2/issues/855
