### ISSUE TITLE
Menu component issue in a device's debug apk

### ISSUE THREAD

**Issue by phavre** [driftyco/ionic2#865]
Hello,
 
   I've built my app in debug mode for android. While it worked well localy, in my browser (chrome) with ionic serve, it failed when executed on my android lolipop 5.1.

__What happened__
My application is built from the tutorial Hello-iconic starter.
* The home page is well displayed
* When clicking on the menu icon, the left pane opens correctly
* A page is selected and navigated to successfully
* The App becomes then unresponsive to any action

At the beginning I've suspected the cordova plugins so I removed them all, but had still the same issue.

*Is there's something I've missed in the building steps in order to have the app functioning in my device ?*

__The build command__ 
`cordova build android`

__The logs__
Through the android debug console I have not error trace. The only log produced at each tap on the screen is the following:
`I/chromium(24611): [INFO:CONSOLE(49171)] "backdrop clicked", source: file:///android_asset/www/build/js/app.bundle.js (49171)`

__The versions__
Cordova CLI: 5.4.1
Ionic Version: 2.0.0-alpha.45
Ionic CLI Version: 2.0.0-beta.15
Ionic App Lib Version: 2.0.0-beta.8
OS: Windows 7 SP1
Node Version: v5.3.0

**Comment by brandyscarney** [comment]
Can you run this on the browser while emulating as an Android device and see if it happens there. I believe you are running into issue #803 which is fixed in `alpha.46`. Some steps to upgrade can be found near the bottom here: http://ionicframework.com/docs/v2/resources/using-npm/

**Comment by phavre** [comment]
@brandyscarney you rock ! I followed the instructions in commenting out some line and now my app is behaving correctly on my android yohoo :) (my first ime app here).

**Comment by brandyscarney** [comment]
@phavre Awesome. :smile: That fix was released in `alpha.46` though so if you upgrade the `ionic-framework` you shouldn't need to comment that line out! You can run this to install the latest version:

```
npm install ionic-framework@latest
```
