### ISSUE TITLE
docs: Add docs on the text alignment and transformation attributes

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#867]
We should have a `util` section that includes the different attributes you can use, possibly include the padding attributes:

https://github.com/driftyco/ionic2/blob/master/ionic/components/app/typography.scss#L101-L137
https://github.com/driftyco/ionic2/blob/master/ionic/util/util.scss#L15-L54

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5026
