### ISSUE TITLE
Look into icon-only buttons having no padding 

### ISSUE THREAD

**Issue by brandyscarney** [driftyco/ionic2#869]
These should probably have padding if they aren't in an item but need to look into it:

![screen shot 2016-01-05 at 5 27 53 pm](https://cloud.githubusercontent.com/assets/6577830/12129439/b0525e46-b3d1-11e5-9867-9f434d9cc642.png)

**Comment by drewrygh** [comment]
:+1:

**Comment by bensperry** [comment]
![image](https://cloud.githubusercontent.com/assets/519526/12213055/86cb3ca6-b637-11e5-8ae7-a83a44541b20.png)

![image](https://cloud.githubusercontent.com/assets/519526/12213058/8abfbe68-b637-11e5-9c12-a3d095bd48d9.png)

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5024
