### ISSUE TITLE
Side Menu not working in Android

### ISSUE THREAD

**Issue by vaibhavch** [driftyco/ionic2#870]
Side menu works fine in ios. but it is not working in android.
-> when  we swipe to open menu, It only works for first time.
-> console says "backtrack clicked."

**Comment by brandyscarney** [comment]
Please update to the latest version of Ionic (currently alpha.47) this was fixed in alpha.46 on issue #803 

Steps to update are at the bottom here: http://ionicframework.com/docs/v2/resources/using-npm/

**Comment by vaibhavch** [comment]
Thanks for the Information

**Comment by brandyscarney** [comment]
Going to close this. Let me know if that doesn't fix it!

**Comment by vaibhavch** [comment]
Yes. It fixed. Thankyou.
