### ISSUE TITLE
Slide animation through Segments

### ISSUE THREAD

**Issue by vaibhavch** [driftyco/ionic2#871]
I would like to know if Ionic V2 consists something like  Sliding segments or tabs

https://github.com/saravmajestic/ionic/tree/master/tabbedSlideBox

-> So that we can swipe left or right to jump into the anothyer Tab or Segment.

**Comment by 3dd13** [comment]
Hi @vaibhavch 

since the Ionic v2 Slides component is using Framework7 Swiper.js, you can use the slidesPerView options to achieve that.
something like this:

    // html
    <ion-slides [options]="slideOptions">
      <ion-slide *ngFor="#slide of slidingTabs">
        <a class="slide-title">{{ slide.title }}</a>
      </ion-slide>
    </ion-slides>

    // js
    this.slideOptions = {
      slidesPerView: 3
    };
    this.slidingTabs = [
      {
        title: "Tab1"
      },
      {
        title: "Tab2"
      },
      {
        title: "Tab3"
      },
      {
        title: "Tab4"
      },
    ];

     // css
    .page-sample ion-slides {
      height: 50px;
    }

**Comment by vaibhavch** [comment]
I mean sliding through Tabs component in ionic.  So you can browse through content of the tabs just by sliding.= without clicking on each tab.

**Comment by vaibhavch** [comment]
Something like swipable tabs in framework 7

**Comment by mhartington** [comment]
If you'd like to provide a PR with an initial implementation that would be extremely helpful.

**Comment by 3dd13** [comment]
submitted a PR to demonstrate how to implement Swipeable Tabs in framework7 with existing Ionic 2 components and API

just as a base to discuss how this pattern should be implemented into the Ionic 2 core:
- is it a segment or tabs ? (segment makes more sense to me, cause tabs is usually a different nav stack and user workflow)
- should we implement it as a dedicated component or combine multiple existing components ?
