### ISSUE TITLE
NavController.present(modal) throws error

### ISSUE THREAD

**Issue by flavordaaave** [driftyco/ionic2#877]
Using the default ionic2 starter (Tabs) with alpha.47 release:

```
export class Page3 {
  constructor(nav: NavController) {
	  this.nav = nav;
  }

  showModal() {
	  let modal = Modal.create(Page1);
	  this.nav.present(modal);
  }
}
```

=> when the `showModal()` function is called, an error is thrown in the console and the Modal does NOT show up.

```
TypeError: rootNav.getActive is not a function
```

**Comment by tomsun** [comment]
Just updated a project to alpha.47 by following the [CHANGELOG](https://github.com/driftyco/ionic2/blob/41b2d61b4ce1cd44d86743ea0b9e11fc650d7a40/CHANGELOG.md#modal-refactor) and reproduced `TypeError: rootNav.getActive is not a function` when `this.nav.present(modal)` is called

**Comment by mhartington** [comment]
@tomsun or @flavordaaave are you importing `Modal` in the file?

**Comment by tomsun** [comment]
@mhartington yes 

(i.e. the file that creates the modal object and calls `this.nav.present(modal)` does import Modal from ionic)

**Comment by mhartington** [comment]
Are you by chance doing this inside of a tabs base project?

**Comment by tomsun** [comment]
@mhartington  yes :-)

**Comment by tomsun** [comment]
@flavordaaave also it seems: "Using the default ionic2 starter (Tabs)..."

**Comment by tomsun** [comment]
successfully reproduced with the minimal amount of changes after `ionic start --v2 testapp`

**Comment by brandyscarney** [comment]
This is happening because the starters don't have an `ion-nav`. We will work on updating the starters to include this. You can see how the conference app does it if you want to update your projects now:

https://github.com/driftyco/ionic-conference-app/blob/master/app/app.html#L25
https://github.com/driftyco/ionic-conference-app/blob/master/app/app.js#L22

**Comment by tomsun** [comment]
@brandyscarney thanks - works fine now!

( Was unclear to me at first what the relation of <ion-nav> and <ion-tabs> was supposed to be, until I realized that they are contained normal page to be used as the root https://github.com/driftyco/ionic-conference-app/tree/master/app/pages/tabs )

**Comment by brandyscarney** [comment]
I checked the other starters and they all have an `ion-nav` element, but please let us know if you see issues with any of them. The [tabs starter](https://github.com/driftyco/ionic2-starter-tabs/) is updated so this should work now. Thanks for the issue! :smile:

**Comment by flavordaaave** [comment]
THX! Adding an `<ion-nav>` works.

**Comment by jet2686** [comment]
The Typescript version of the starter could use this fix as well could use this fix as well.
