### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic2#878]
The Ionic 1 and 2 doesn't include RTL support. You can't choose LTR or RTL app in the configuration.
It would be nice to config direction of app; for arabic and hebrew apps.
Right now I can fix direction from css and dir attribute but some components not working well.

**Comment by brandyscarney** [comment]
Duplicate of https://github.com/driftyco/ionic2/issues/832

Please add any input you have on that issue. Thanks! :smile:
