### ISSUE TITLE
Icon property names

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#879]
What was `<icon home></icon>` is now `<ion-icon name="home"></ion-icon>`. Now that icon names will no longer work as attribute names, and we're now using attribute values instead, such as `name="home"`, this frees us up to come up with a better naming system. 

Currently, if you want to use the "home" icon for the platform they're on you use the following:

```
Markup:
<ion-icon name="home"></ion-icon>

On iOS it becomes:
<ion-icon class="ion-ios-home"></ion-icon>

On Material Design it becomes:
<ion-icon class="ion-md-home"></ion-icon>
```

If you want to use two different icons depending on platform you use the following:

```
Markup:
<ion-icon ios="ion-social-apple" md="ion-social-android"></ion-icon>

On iOS it becomes:
<ion-icon class="ion-social-apple"></ion-icon>

On Material Design it becomes:
<ion-icon class="ion-social-androidr"></ion-icon>
```

(also up for debate, do they need the `ion-` prefix in the above example anymore??)

What should they do when the app wants to always use the exact same icon, every time, all platforms?

Thoughts? @mlynch @brandyscarney @drewrygh @mhartington @tlancina

**Comment by adamdbradley** [comment]
I'm starting to think that `name` should be the property for ALWAYS use this icon, such as `name="social-twitter` would always use the same twitter icon for both iOS and MD.

But we still need a name for "adjust the icon depending on the mode".

**Comment by brandyscarney** [comment]
I say get rid of the `ion` prefix to keep it consistent with `name`.

What if we did something like
`strictName` - always use this icon name
`platformName` - change the icon based on the platform

-or- by default it can do platform specific but they can add a strict attribute to force it to use the exact name:
`<ion-icon name="home" strict="on">`

throwing things out there

**Comment by adamdbradley** [comment]
What about by dashes and prefixes of the icons themselves (we can change up ionicons all we want).

So the directive looks for these prefixes: `ios-`, `md-`, and...some word for common icons that aren't platform specific. Like the twitter icon needs a prefix so that the directive knows not to try to look it up a version for ios and a version for md.

```
name="home" : on iOS would load "ios-home", on MD would load "md-home"
name="ios-home" : Always load "ios-home" because it started with `ios-`
name="md-home" : Always load "md-home" because it started with `md-`
name="social-twitter" : Always load "social-twitter" because it started with `social-`
```

But not a huge fan of `social` to begin with. These are all the examples of our social icons, which aren't all social icons (like yen or xbox).

```
android
angular
apple
bitcoin
buffer
chrome
codepen
css3
designernews
dribbble
dropbox
euro
facebook
foursquare
freebsd-devil
github
google
googleplus
hackernews
html5
instagram
javascript
linkedin
markdown
nodejs
octocat
pinterest
playstation
python
reddit
rss
sass
skype
snapchat
steam
tumblr
tux
twitch
twitter
usd
vimeo
whatsapp
windows
wordpress
xbox
yahoo
yen
youtube
```

What if they all had a `-logo` suffix? @bensperry

**Comment by brandyscarney** [comment]
:+1: everything above +1 +1 +1

![vaultboyfo3](https://cloud.githubusercontent.com/assets/6577830/12156589/c4d0acb0-b499-11e5-9543-152d76dcc880.png)

**Comment by bensperry** [comment]
I'm cool with this.
