### ISSUE TITLE
Wrong ion-tab highlighted momentarily after re-orientation of device

### ISSUE THREAD

**Issue by tomsun** [driftyco/ionic2#880]
When testing an application with three ion-tabs on an android device, re-orientation of the device (portrait -> landscape or landscape -> portrait) causes the selected-tab indicator (md) to behave somewhat funky.

When the middle tab is selected, either the left or the right tab is momentarily underlined instead, then a semi-slow animation brings the selection back to where it belongs (see this video: [ionic2-activetab-reorient.mov.zip](https://github.com/driftyco/ionic2/files/80340/ionic2-activetab-reorient.mov.zip) )

When the rightmost tab is selected, either the middle tab is momentarily underlined - or the underlining momentarily disappears and then reapperas from the right side of the screen.

When the leftmost tab is selected,  either both the left tab and the middle tab are underlined - or half of the left tab is underlined.

Using 2.0.0-alpha.47
Using crosswalk

**Comment by adamdbradley** [comment]
A slight delay will probably be unavoidable, but I can look into speeding up its response, thanks.

**Comment by tomsun** [comment]
@adamdbradley that smooth animation almost feels like its intentional (except the behavior doesn't make too much logical sense).

if the animation was removed entirely, would the highlighting be in sync with the rest of the page's re-flow, or would it still lag behind for some reason (perhaps due to being js-controlled, not a css-behavior?) and cause an even more quirky feel? if so, perhaps the current behavior is a decent compromise...
