### ISSUE TITLE
new NavController API doesn't work with Tabbed UI

### ISSUE THREAD

**Issue by mallowigi** [driftyco/ionic2#881]
Actionsheet does not work with tabbed views.

Works fine with `<ion-nav>` but not with `<ion-tabs>`; trying to click to an action sheet trigger button creates an error with `rootNav.getActive is not a function`

Problem is in `NavController`; somehow it looks like you didn't handle the case.

**Comment by brandyscarney** [comment]
This was discussed in this issue: https://github.com/driftyco/ionic2/issues/877

Currently an `<ion-nav>` is required and the tabs starter has been updated to include it. Please reference the tabs starter for an example of how to include it in your app: https://github.com/driftyco/ionic2-starter-tabs/tree/master/app
