### ISSUE TITLE
iOS: Input fields don't loose focus when clicking outside

### ISSUE THREAD

**Issue by flavordaaave** [driftyco/ionic2#885]
How to reproduce:
1) Run the ionic-conference-app on a native iOS device (or emulator)
2) Open the login form from the side-menu
3) Tap into one of the inputs (e.g. username)
4) Tap on the ionic logo above (or anywhere outside the input)
=> Input remains focused and keyboard stays up

Expected behavior:
=> Input looses focus and keyboard slides out.

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5020
