### ISSUE TITLE
Select broken on Android in alpha46/47

### ISSUE THREAD

**Issue by richardshergold** [driftyco/ionic2#886]
My Ionic 2 app has a form that the user fills in to book a room.  I have been using select to allow the user to select the room and this worked fine up to alpha40. I then moved onto alpha46.   In alpha46 and alpha47 it still works but only in iOS.  On my Android device if I click on the field, nothing happens.  Is there anything I can do to get this working in the latest version ?

```
<ion-input fixed-label *ngIf="data.bookingType=='Room'>
      <ion-label>Room</ion-label>
      <select [(ngModel)]="data.resource">
        <option selected>Room 1</option>
        <option>Room 2</option>
        <option>Room 3</option>
        <option>Room 4</option>
        <option>Room 5</option>
      </select>
    </ion-input>
```

**Comment by adamdbradley** [comment]
Gahh, that darn select element! We've had these same issues with Ionic1 (and continue to). Problem is each browser, browser version, platform, OS, etc. all have a different interpretation of what should happen on click and preventing default, for both the select element itself and the option element. In the short term, can you not put the select element in an ion-input, but rather an ion-item?

**Comment by richardshergold** [comment]
I will give it a try - thanks!

**Comment by richardshergold** [comment]
@adamdbradley it didn't work inside ion-item either but it does work if I put it inside nothing i.e
~~~
<ion content>
<ion-label>Room</ion-label>
    <select [(ngModel)]="data.resource">
      <option selected>Ash</option>
      <option>Bay</option>
      <option>Beech</option>
      <option>Cedar</option>
      <option>Redwood</option>
    </select>
<ion-content>
~~~
I'm using Crosswalk by the way.  Thanks.
