### ISSUE TITLE
Missing back button on nav-bar

### ISSUE THREAD

**Issue by mrpatiwi** [driftyco/ionic2#891]
I just updated to 2.0.0-alpha.48 and did the migrations declared on CHANGELOG.md, but suddenly the back button of a `Page` when pushed with `this.nav.push(MyPage, { data: data });` disappeared.

![image](https://cloud.githubusercontent.com/assets/7570744/12186383/d726ad5a-b580-11e5-9552-f5e73bd856c7.png)

My page `.html`:
```html
<ion-navbar *navbar>
  <ion-title>...</ion-title>
</ion-navbar>

<ion-content class="page-content">
  ...
</ion-content>
```

Any help?

**Comment by adamdbradley** [comment]
Good catch, thanks. This will be fixed in the next release, and in the interim you can update your config so the icon doesn't have an `ion-` prefix.
