### ISSUE TITLE
EXCEPTION: Cannot resolve all parameters for NavController(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?). Make sure they all have valid type or annotations.

### ISSUE THREAD

**Issue by tdehaeze** [driftyco/ionic2#893]
When I'm trying to import NavController into an "Injectable" component, I get this error :

> EXCEPTION: Cannot resolve all parameters for NavController(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?). Make sure they all have valid type or annotations.

```javascript
import {Page, NavController}          from 'ionic/ionic';
import {HttpInterceptor}              from '../../services/http_interceptor';

@Page({
  templateUrl: 'build/pages/login/login.html',
  providers: [NavController]
})

export class Login {

  constructor(nav: NavController)
  {
    this.nav = nav;
  }
}
```

```javascript
import {NavController}  from 'ionic/ionic';
import {Injectable}  from 'angular2/core';

@Injectable()

export class HttpInterceptor {

  constructor(nav: NavController)
  {
    this.nav = nav;  
  }
}
```

I'm using ionic alpha.48

I'm on this since yesterday, and I can't find why this happens.

**Comment by brandyscarney** [comment]
You're passing `NavController` in the providers of the page. Did you mean to pass `HttpInterceptor`?

**Comment by tdehaeze** [comment]
Oh no, or maybe I didn't get how does this works.

But I can't import NavController into the app.js :

```javascript
import {App, NavController} from 'ionic/ionic';

@App({
  templateUrl: 'build/app.html',
})

class MyApp {
  constructor(nav: NavController)
  {
    this.nav = nav;
  }
}
```

This doesn't work.

But now i updated to alpha 48, I messed up my config, `ionic serve` doesn't work and send me :
> Install `babylon` as a top-level package.

**Comment by Luchillo** [comment]
When i update i do this:
    1. Create new project with latest framework.
    2. Verify if there's changes in any config files, lately there has been a lot of changes like going from webpack to babel and back to webpack.
    3. If changes in config files i copy the changes no specific to the app, like configs, but keep changes like `dependencies` like `moment` in `package.json` that i need in the app.
    4. Lastly remove `node_packages` and re-install.

That way i'm sure that if it doesn't work is my logic, not the framework.

**Comment by adamdbradley** [comment]
Injecting NavController into an injectable will probably not work, since an injectable really isn't a child of any ion-nav component. I'd recommend not trying to use NavController within an injectable, and if you do have to, the actual `nav` instance that your `@Page` component can correctly get, can be passed into the method your calling on your injectable.

**Comment by Luchillo** [comment]
What you can also do if you need the nav component in the injectable is to inject `IonicApp` and use it to get the nav component where you need it, just like the openPage method in the sidemenu starter:

>     import {IonicApp} from 'ionic/ionic'
    @Injectable({....})
    class MyInjectable {
      constructor(private app: IonicApp){}
      useNav(){
        let nav = this.app.getComponent('nav')
        nav.push(RandomPage)
      }
    }
