### ISSUE TITLE
Ionic documentation page issue

### ISSUE THREAD

**Issue by shashidharhr** [driftyco/ionic2#894]
http://ionicframework.com/docs/v2/components/navigation

and few other routes in documentation are not processing GET requests and gives this error

"Cannot GET /docs/v2/components/navigation"

**Comment by adamdbradley** [comment]
cc @perrygovier @mhartington

**Comment by mhartington** [comment]
@shashidharhr looks like the link you're trying to reach was removed once we reorganized our v2 docs.

The link you want is http://ionicframework.com/docs/v2/components/#navigation
