### ISSUE TITLE
Using TabsController's select

### ISSUE THREAD

**Issue by mallowigi** [driftyco/ionic2#895]
I'm trying to use the Ionic framework v2 and I'm still struggling with most basic tasks, such as select a tab when the app is loading.

I've tried to inject the `Tabs` controller and call `select` on the `onPageLoaded` event, but to no avail.

Can someone help maybe?

**Comment by adamdbradley** [comment]
So within a page that is a child of `Tabs` (which is the component class of the tabs markup), you can inject `Tabs` in to the page: https://github.com/driftyco/ionic2/blob/4d0d2a5d4d0a10bf4e63a814cd0842cc6347c7e9/ionic/components/tabs/test/advanced/index.ts#L106

Once you inject `Tabs` and assign it to `this.tabs`, you can then use that reference later to call `select()` or any method on tabs: https://github.com/driftyco/ionic2/blob/4d0d2a5d4d0a10bf4e63a814cd0842cc6347c7e9/ionic/components/tabs/test/advanced/index.ts#L116

Additionally, within the actual page that contains the `<ion-tabs>`, you can also get a references to the `Tabs` component instance by using `@ViewChild`: https://github.com/driftyco/ionic2/blob/4d0d2a5d4d0a10bf4e63a814cd0842cc6347c7e9/ionic/components/tabs/test/advanced/index.ts#L61

One gotcha is that you cannot use the instance of Tabs until the view is initialized, within `ngAfterViewInit`: https://github.com/driftyco/ionic2/blob/4d0d2a5d4d0a10bf4e63a814cd0842cc6347c7e9/ionic/components/tabs/test/advanced/index.ts#L70

Hope that helps

**Comment by mallowigi** [comment]
I see, thanks for your help. However you should improve your documentation about that @ViewChild directive, since I haven't seen in the docs at all...
