### ISSUE TITLE
Local Notificacions

### ISSUE THREAD

**Issue by mrpatiwi** [driftyco/ionic2#896]
Is there any plans for Local Notifications? Like http://ionicframework.com/docs/v2/platform/push-notifications.

I had no luck with https://github.com/katzer/cordova-plugin-local-notifications

**Comment by richardshergold** [comment]
What happens when you try that plug-in?  I was about to try myself but if there are issues, I will leave it for now.  I was hoping it would just work as it did in Ionic 1 ?

**Comment by mrpatiwi** [comment]
Maybe it's my fault, because I install it with:
```sh
ionic plugin add https://github.com/katzer/cordova-plugin-local-notifications.git
```

But I don't know how to get a instance of the dependency.

**Comment by mhartington** [comment]
So the plugins were from ionic2 core and moved to another project. But if you need to access the plugin directly, you can do 

```
window.PLUGINNAME
```

**Comment by mrpatiwi** [comment]
I'm trying with `window.notification.local` and `window.plugins.notification.local` with no result :(

**Comment by additv** [comment]
I believe it's cordova.plugins.notification.local you're looking for.

Something like this works for me:
cordova.plugins.notification.local.schedule({
    title: "Title",
    text: "Message!",
    sound: "file://sounds/reminder.mp3",
    icon: "http://icons.com/?cal_id=1",
});

Note: on iOS at least, your app needs to be in the background for the notification to show.

**Comment by mhartington** [comment]
To use the plugin, you can call via 

```
window.cordova.plugins.notification.local.
```
