### ISSUE TITLE
New Alert component is not opening with ion-tabs

### ISSUE THREAD

**Issue by phavre** [driftyco/ionic2#897]
Hello,

   I've updated to alpha 48 and tried the new Alert component as described in the changelog.md.
   I've deleted the ion-overlay tag.

   But on NavController `present(alert)` call I have the following error (and no alert is opening):

> app.bundle.js:33822 EXCEPTION: Error during evaluation of "click"
> app.bundle.js:33813 EXCEPTION: Error during evaluation of "click"BrowserDomAdapter.logError @ app.bundle.js:33813BrowserDomAdapter.logGroup @ app.bundle.js:33823ExceptionHandler.call @ app.bundle.js:7943(anonymous function) @ app.bundle.js:16925NgZone._notifyOnError @ app.bundle.js:17566collection_1.StringMapWrapper.merge.onError @ app.bundle.js:17461run @ app.bundle.js:1186(anonymous function) @ app.bundle.js:17479NgZone.run @ app.bundle.js:17428outsideHandler @ app.bundle.js:32173run @ app.bundle.js:1183zoneBoundFn @ app.bundle.js:1156
> app.bundle.js:33813 ORIGINAL EXCEPTION: TypeError: rootNav.getActive is not a functionBrowserDomAdapter.logError @ app.bundle.js:33813ExceptionHandler.call @ app.bundle.js:7952(anonymous function) @ app.bundle.js:16925NgZone._notifyOnError @ app.bundle.js:17566collection_1.StringMapWrapper.merge.onError @ app.bundle.js:17461run @ app.bundle.js:1186(anonymous function) @ app.bundle.js:17479NgZone.run @ app.bundle.js:17428outsideHandler @ app.bundle.js:32173run @ app.bundle.js:1183zoneBoundFn @ app.bundle.js:1156
> app.bundle.js:33813 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ app.bundle.js:33813ExceptionHandler.call @ app.bundle.js:7955(anonymous function) @ app.bundle.js:16925NgZone._notifyOnError @ app.bundle.js:17566collection_1.StringMapWrapper.merge.onError @ app.bundle.js:17461run @ app.bundle.js:1186(anonymous function) @ app.bundle.js:17479NgZone.run @ app.bundle.js:17428outsideHandler @ app.bundle.js:32173run @ app.bundle.js:1183zoneBoundFn @ app.bundle.js:1156
> app.bundle.js:33813 TypeError: rootNav.getActive is not a function
 >   at Tab.NavController.present (http://localhost:8100/build/js/app.bundle.js:47158:36)
 >   at SettingsPage.clearAll (http://localhost:8100/build/js/app.bundle.js:62357:19)
>    at AbstractChangeDetector.ChangeDetector_SettingsPage_0.handleEventInternal (eval at <anonymous> (http://localhost:8100/build/js/app.bundle.js:14713:17), <anonymous>:414:33)
 >   at AbstractChangeDetector.handleEvent (http://localhost:8100/build/js/app.bundle.js:14027:25)
 >   at AppView.dispatchEvent (http://localhost:8100/build/js/app.bundle.js:18907:46)
 >   at AppView.dispatchRenderEvent (http://localhost:8100/build/js/app.bundle.js:18901:22)
>    at DefaultRenderView.dispatchRenderEvent (http://localhost:8100/build/js/app.bundle.js:33725:39)
  >  at eventDispatcher (http://localhost:8100/build/js/app.bundle.js:33391:22)
 >   at http://localhost:8100/build/js/app.bundle.js:33462:40
>    at http://localhost:8100/build/js/app.bundle.js:32828:37

**Comment by adamdbradley** [comment]
To use overlays there must be an ion-nav, which in most cases there always is. However, with tabs it doesn't have to be within an ion-nav, which causes the issue. This probably can be avoided in future angular2 releases: https://github.com/angular/angular/issues/5481

**Comment by phavre** [comment]
Thanks a lot. It works. I've reverted back to menu toggle. But still struggle with #910 :/
