### ISSUE TITLE
Special Characters not supported (Scandinavian chars)

### ISSUE THREAD

**Issue by Doehl** [driftyco/ionic2#900]
The Danish and Swedish characters **æøå** and **öä** as an exsampel is not supported in Ionic 2.

I am using the charset UTF-8.
```html
<meta charset="UTF-8">
```

I add some of the Danish and Swedish characters, will it be shown as the following �.
I have tried to add the characters outside the ```<ion-app></ion-app>```, and then is it show correctly.

**Comment by Doehl** [comment]
Workaround is to use the HTML special character value like **&auml;* to get **ö**.

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5017
