### ISSUE TITLE
Add Types, round 1

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#901]
Start adding types:

 - [ ] components/app/app.ts
 - [ ] components/app/id.ts
 - [ ] components/icon/icon.ts
 - [ ] components/label/label.ts
 - [ ] components/list/list.ts
 - [ ] components/option/option.ts
 - [ ] components/show-hide-when/show-hide-when.ts
 - [ ] components/slides/slides.ts
 - [ ] platform/platform.ts
 - [ ] platform/registry.ts
 - [ ] platform/storage.ts

**Comment by jgw96** [comment]
Looking for community contributions on this? Id love to help!

**Comment by adamdbradley** [comment]
@jgw96 actually yes, we'd love to get some help with this issue: https://github.com/driftyco/ionic/tree/2.0

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5016
