### ISSUE TITLE
ios tabs lost their correct styling

### ISSUE THREAD

**Issue by bensperry** [driftyco/ionic2#904]
![image](https://cloud.githubusercontent.com/assets/519526/12213072/c846558a-b637-11e5-8237-de62fa80b96e.png)

the unselected tab items should not be colored at all. They should look like this:
![image](https://cloud.githubusercontent.com/assets/519526/12213084/e8a211c0-b637-11e5-9c8f-e3a852497563.png)

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5014
