### ISSUE TITLE
Passing parameters to a modal

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic2#906]
Currently to pass parameters to a modal, you have to pass them in `Modal.create`

```
  presentModal(image) {
   let viewerModal = Modal.create(Viewer, {
     'image': image
   });
   this.nav.present(viewerModal);
 }
```

I feel like this should be done during present instead. Since we moved towards using `navCtrl` to show a modal, it feels more natural, like push a page with some data. 

```
  presentModal(image) {
   let viewerModal = Modal.create(Viewer);
   this.nav.present(viewerModal, , {
     'image': image
   });
 }
```

Thoughts?

**Comment by brandyscarney** [comment]
Ooh yeah that's a good idea.

**Comment by adamdbradley** [comment]
With `present` your giving the nav a `ViewController` instance, which has the component class and param data. With `push` you're giving it a component class with param data. Under the hood, `push` is doing the same thing where creates a ViewController from a component class and param data, it doesn't separate them.

With overlays, we want to immediately have a reference to the instance of the `Alert`, `ActionSheet` and `Modal`. This way they can take a completed instance and change it up as they please, close it the millisecond is starts to animate in, etc. 

Of we did break them apart where the View controller instance really was just an instance, but without any data, it would make things more difficult. Also present is for more than just modal. For example, our `Alert` and `ActionSheet` wouldn't be able to do this:

```
let alert = Alert.create();
alert.setTitle('My Title');
this.nav.present(alert);
```

I think the way it is now allows us to be more flexible.
