### ISSUE TITLE
md navicon wrong color

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic2#91]
The navicon should be grey or black or even white by default in md mode, not the primary blue

**Comment by brandyscarney** [comment]
Can I get some more information on this? Maybe a screenshot? Are all icons in the nav-bar supposed to be a different color?

**Comment by brandyscarney** [comment]
Seems all MD buttons should be a dark color on a light toolbar and white on a dark toolbar:
![screenshot_2015-10-30-13-36-18](https://cloud.githubusercontent.com/assets/6577830/10853187/4663c7a4-7f0b-11e5-90f5-af5f76ca985c.png)


![screenshot_2015-10-30-13-30-37](https://cloud.githubusercontent.com/assets/6577830/10853157/1051510e-7f0b-11e5-9665-c11a4576c3ff.png)
![screenshot_2015-10-30-13-29-35](https://cloud.githubusercontent.com/assets/6577830/10853163/1b2622ee-7f0b-11e5-8916-dd19ca9ed7ed.png)
