### ISSUE TITLE
Unable to use translatePipe in app.html

### ISSUE THREAD

**Issue by phavre** [driftyco/ionic2#910]
Hello, I ran into this issue when internationalizing my app. Everything was translated with TranslatePipe in html files except for the menu titles in app.html. The keys are not translated and are rendered as is.

I've defined everything exactly as the other pages. Something special with this app page ?

**Comment by mlynch** [comment]
Closing as the Angular team is planning on providing a better translate API and we'd rather defer to them.

**Comment by phavre** [comment]
Hi, I'm aware that this translate class is somewhat temporary until angular 2's translate is available. But in between would you not just look into this issue to acknowledge it at least, for I could do something wrong instead. Or direct me in another path to achieve my goal until angular 2 class is ready ?
This issue is the last one (so forth) in my application. 
Thanks anyway for your reply.

**Comment by mlynch** [comment]
Could be the way we handle menu titles does not properly go through Angular. Do you have some example code and what you're seeing? We might want to open a separate issue

**Comment by phavre** [comment]
Well, I used the ionic Hello starter app and instead of `{{ p.title }}` in the app.html, I used `{{ p.title | translate }}` as with the other pages which function properly. 
* Translate and TranslatePipe classes have been added in app.ts import section
* Translate class has been added in the constructor's parameters and affected to class a property
* TranslatePipe has been added as a provider to the app.html template. 
* Translate content is set as soon as possible (in the constructor)
What is shown are the p.title values (the keys) and not their translation

I found this as a workaround: 
* perform the translation directly in the app.ts' platform ready part with the translate function
