### ISSUE TITLE
default md back button icon needs to be renamed

### ISSUE THREAD

**Issue by drewrygh** [driftyco/ionic2#912]
`ion-md-arrow-back` is still the default back button icon, even though it doesn't exist.

Also, the [API doc for this should be updated](https://github.com/driftyco/ionic2/blob/master/ionic/config/config.ts#L84)

**Comment by adamdbradley** [comment]
![image](https://cloud.githubusercontent.com/assets/452425/12219691/343af9c6-b714-11e5-9df6-202ec24e1ec3.png)

Where are you not seeing it exist?
