### ISSUE TITLE
PNG images do not get copied to the build directory

### ISSUE THREAD

**Issue by krz37** [driftyco/ionic2#914]
On "ionic serve" and other commands I suppose, png images and their directory do not get copied to the build directory.
Resulting in this type of error in the console and the image not to get displayed : 
GET http://localhost:8100/img/image.png 404

**Comment by kitkimwong** [comment]
Put your png into YourProject\www\img

**Comment by krz37** [comment]
Of course this can be done by hand by putting images into www. But the development is supposed to be solely in /app right?

**Comment by joshuamorony** [comment]
I think this is the intended behaviour. If you check out the Ionic conference app: https://github.com/driftyco/ionic-conference-app/tree/master/www 

You can see that resources that are called from the app (like images, and the data.json file) are placed directly inside the www folder.

**Comment by krz37** [comment]
Alright, thank you. I will close the issue.
