### ISSUE TITLE
Alpha 48 breaks the navigation tutorial example

### ISSUE THREAD

**Issue by krz37** [driftyco/ionic2#915]
When compiling my app in alpha 48 I get the following issue:
\<icon\> has been renamed to <ion-icon>
      app.bundle.js:48519 <ion-icon> requires the "name" attribute w/ a value
      app.bundle.js:48520 <icon home></icon> should now be <ion-icon name="home"></ion-icon>

due to 

    <ion-navbar *navbar>
      <button menuToggle>
        <icon menu></icon>
      </button>
      <ion-title>Group Finder</ion-title>
    </ion-navbar>

Step to reproduce : 
ionic start MyIonic2Project tutorial --v2
cd MyIonic2Project/
ionic serve

**Comment by krz37** [comment]
problem : the navigation icon is not anymore displayed. I tried to change 
<icon menu></icon> with <ion-icon name="menu"></ion-icon> but it doesn't work

**Comment by mhartington** [comment]
Should be all good now.

**Comment by krz37** [comment]
Oh this does work, I might have mistyped it since for me things got broken when doing this earlier. Thanks
