### ISSUE TITLE
Child component click event within ion-item not working

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic2#917]
Hi, i have a component inside a ion-item with a `(click)` event attached but it doesn't works, the `(click)` ones attached directly to the other `ion-item`'s works, it's just the one in the component, why?, i think it's the ion-item catching the click events before the component does, maybe has to do with `z-index`?:
>Parent html:

>     <ion-item [ngClass]="{'primary-disabled': sync}">
      <syncServ (synced)="onSync($event)" (click)="syncServer()"></syncServ>
    </ion-item>
Child html:

>     <div>
      <i class="fa fa-refresh fa-2x"></i>
      <div>
        P: {{ orders }} V: {{ visits }}
      </div>
    </div>
Child component js:

>     import {Component, Output, EventEmitter} from 'angular2/core';

>     import {Config, DB} from '../../services/services';

>     @Component({
>       selector: 'syncServ',
>       templateUrl: 'build/components/sync/sync.html',
>     })
>     export class SyncComponent {
>       orders = 0
>       visits = 0
>       tryIt = true

>       @Output() synced = new EventEmitter();

>       constructor(
>         conf: Config,
>         db: DB
>       ) {
>         this.conf = conf
>         this.db = db
>         console.log('Test')
>       }

>       ngOnInit() {
>         this.synced.emit({value: true})
>       }

>       syncServer() {
>         console.log('SyncServ')
>         this.tryIt = !this.tryIt
>         if (this.tryIt) {
>           this.synced.emit({value: true})
>         } else {
>           this.synced.emit({value: false})
>         }
>       }
>     }

**Comment by Luchillo** [comment]
Also if i attach the click to the `ion-item` it tries to call the method but as it exist in the child component it can't find it, i really think the `ion-item` is messing with the `(click)` events in the child component.

**Comment by TheBosZ** [comment]
I think this is the same problem I'm having: https://forum.ionicframework.com/t/nested-lists-losing-click/40801

**Comment by Luchillo** [comment]
It's probably related, as i cant even reach the item inside of the `ion-item`, did you filled an issue too?

**Comment by TheBosZ** [comment]
I didn't file an issue, just posted on the forums.

**Comment by Luchillo** [comment]
This is a bug (i think), and as i'm not the only one that has this error this issue should work to let them know, aside i think my use case is easyer to understand and replicate, btw which version of ionic and angular are you using?

**Comment by TheBosZ** [comment]
My info:
```
Cordova CLI: 5.4.1
Gulp version:  CLI version 3.8.11
Gulp local:
Ionic Version: 2.0.0-alpha.48
Ionic CLI Version: 2.0.0-beta.15
Ionic App Lib Version: 2.0.0-beta.8
OS: Windows 10
Node Version: v5.3.0
Angular2: 2.0.0-beta.0
```

**Comment by Luchillo** [comment]
That's your info but is the info version the same as the `package.json`?

**Comment by mhartington** [comment]
Thanks, I can confirm this.

**Comment by Luchillo** [comment]
@mhartington this beats the purpose of the component i'm making, for the moment i can do it in the parent component but then it isn't reusable any more, do you know what the issue could be? is it `z-index` as i suspected or is something else?
