### ISSUE TITLE
Create a Dark Theme

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#923]
Ionic comes with a default theme, which is mainly a white background and black foreground:
https://github.com/driftyco/ionic2/blob/master/ionic/themes/default.scss

However, Ionic2's folder structure, Sass imports and variables have all been setup to allow other themes to be easily added, and allow end developers to choose which theme they want to start from. For example, an app could start with the dark theme, but they could still customize all the colors to fit their brand.

If anyone is looking to help create the dark theme we'd really appreciate the assistance. A lot of the work is just making sure all of the css and sass variables are in place to allow the entire app's theme to switch out, and allow many other themes to be easily created with minimal sass variable changes. If interested please let us know, thanks!

**Comment by alexbainbridge** [comment]
I know you know this, but v2 docs suggests the dark theme already exists http://ionicframework.com/docs/v2/theming/theming-your-app/ 

I tried to use it then found it was docs only :)

**Comment by adamdbradley** [comment]
Yeah sorry, it did at one point. But as we were building our the sass files it got to be a pain to keep updating. But now that things are solidifying we can start building it out again.

**Comment by matheusrocha89** [comment]
I wanna help with that :+1:

**Comment by adamdbradley** [comment]
@matheusrocha89 Awesome thanks! I'll assign it to myself so for now so know it's being worked on. Any questions please let us know and we can help make sure the files are setup correctly. The new `dark.scss` file should go in here: https://github.com/driftyco/ionic2/tree/master/ionic/themes

Thanks!

**Comment by jgw96** [comment]
@matheusrocha89 are you working on this? Id love to help if needed?

**Comment by matheusrocha89** [comment]
@jgw96 I will start to do something today, I will create a branch. Any help is welcome :+1:

**Comment by adamdbradley** [comment]
Heads up, we JUST moved `ionic2` to be in a different branch in the `ionic` repo: https://github.com/driftyco/ionic/tree/2.0

**Comment by jgw96** [comment]
@adamdbradley yep saw that today. Are all these bugs moved over to the main repo too?

**Comment by jgw96** [comment]
@adamdbradley or are all the bugs still gonna be handled in this repo?

**Comment by adamdbradley** [comment]
Currently being moved over, we've got some work to do to clean up the process for creating and managing issues.

**Comment by jgw96** [comment]
Got ya, is there gonna be an official set of contributing guidelines set up for v2?

**Comment by adamdbradley** [comment]
This issue was moved to driftyco/ionic#4967
