### ISSUE TITLE
When the keyboard is closed after write inside a ion-input the content doesn't comes back to the original position

### ISSUE THREAD

**Issue by ivanbtrujillo** [driftyco/ionic2#925]
hi all! i’t seems that on android (i haven't checked it on IOS) when you start to write inside an input, the keyboard is opened and moves the content to top (it's ok). 

The problem is that when you close it, the content doesn't comes back to the original position, and we have a margin-bottom.

**Comment by adamdbradley** [comment]
This will probably stay a default for a while, as the code to know when the keyboard has closed, and animating the content back to its original position is quite heavy and janky, and results in many other issues.
