### ISSUE TITLE
Visual Studio 2015 Typescript intellisense support

### ISSUE THREAD

**Issue by xxsodapopxx5** [driftyco/ionic2#926]
Currently if you start a project via the CLI via ionic start TestProj1 tutorial --v2 --ts and create a project with those generated files in Visual Studio 2015 Community Edition, the typescript intellisense does not work correctly.

**Comment by tlancina** [comment]
Thanks for the issue! When you say 'not correctly', do you mean that it doesn't work at all or that there specific problems?

**Comment by xxsodapopxx5** [comment]
there are specific problems, definitions aren't coming through, for instance when I open app.ts any of the class properties are highlighted in red. After looking at it, this could be fixed fairly easily by adding private or public into the constructor parameters and defining the class properties for the additional missing ones. 
If fixed the below code, except for "StatusBar", which I am unsure about. 
![image](https://cloud.githubusercontent.com/assets/16467307/12246840/cd60906e-b87e-11e5-92ac-7529c2c1d8ad.png)

to this
![image](https://cloud.githubusercontent.com/assets/16467307/12247616/c635daa2-b882-11e5-890c-5f7098155be8.png)


I also cannot use visual studio build to compile everything correctly. The browser opens, ripple loads(with the phone screen), but the app does not load, it is just a blank white screen. The build from CLI works just fine with the code changes above.

**Comment by xxsodapopxx5** [comment]
I didn't note this, but all of the .ts application specific files have similar changes that are needed, missing class properties, that once created correctly don't throw visual studio errors. The files are list.ts, item-details.ts and hello-ionic.ts

**Comment by mhartington** [comment]
this should be taken care of soon. We're going through the process of making sure the framework has the correct types. Once this is done, we'll update the starters.

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5011
