### ISSUE TITLE
toggle.d.ts and checked.d.ts duplicate identifier

### ISSUE THREAD

**Issue by xxsodapopxx5** [driftyco/ionic2#927]
There is a duplicate property in both the toggle.d.ts and checked.d.ts files the "checked" property is declared twice.

![image](https://cloud.githubusercontent.com/assets/16467307/12248555/30c2e7f2-b888-11e5-8aef-d30eb6908168.png)

**Comment by adamdbradley** [comment]
Thanks. Yeah we're just starting to do some rounds of cleaning up the typescript errors, so we'll be able to start fixing these.
