### ISSUE TITLE
generate page CLI - 2 issues

### ISSUE THREAD

**Issue by alexbainbridge** [driftyco/ionic2#928]
A couple of bits of feedback on output from the following request

**ionic generate page test**

a) Filename / class name 

for the export class line, could you create it as TestPage rather than test  

Reasoning - seems that most of the classes have the word Page in (if they are a page class). And seems the capitlisation is different on the class to the filename 

e.g. see https://github.com/driftyco/ionic-conference-app/blob/master/app/pages/about/about.js which is on a file called about (lower case) - but has a class AboutPage (upper case, and with word Page) 

b) The template URL in the default .js for the newly created page

See the conference app, has templateUrl: 'build/pages/about/about.html'

i.e. in build/pages. However the generator is creating the templateURL as a link to a file in app 

Not quite sure which is right, but I am having to adjust and move to build/pages like the conference app, and that works.  

Thanks!

**Comment by adamdbradley** [comment]
Last time we reviewed this as a team these were the standards we created:

```
session
session.html
session.js
session.scss
css class=”session”
js class Session

Session
session.html
session.js
session.scss
css class=”session”
js class Session

SESSIONDETAIL
sessiondetail.html
sessiondetail.js
sessiondetail.scss
css class=”sessiondetail”
js class Sessiondetail

sessionDetail
session-detail.html
session-detail.js
session-detail.scss
css class=”session-detail”
js class SessionDetail

SessionDetail
session-detail.html
session-detail.js
session-detail.scss
css class=”session-detail”
js class SessionDetail

SesSionDetail
ses-sion-detail.html
ses-sion-detail.js
ses-sion-detail.scss
css class=”ses-sion-detail”
js class SesSionDetail

seSsionDeTail
se-ssion-de-tail.html
se-ssion-de-tail.js
se-ssion-de-tail.scss
css class=”se-ssion-de-tail”
js class SeSsionDeTail

session-detail
session-detail.html
session-detail.js
session-detail.scss
css class=”session-detail”
js class SessionDetail

---session-----detail----
session-detail.html
session-detail.js
session-detail.scss
css class=”session-detail”
js class SessionDetail

session_detail
session-detail.html
session-detail.js
session-detail.scss
css class=”session-detail”
js class SessionDetail

____session____detail____
session-detail.html
session-detail.js
session-detail.scss
css class=”session-detail”
js class SessionDetail

sessionthing (we can’t tell where the words are broken up so don’t try)
sessionthing.html
sessionthing.js
sessionthing.scss
css class=”sessionthing”
js class Sessionthing
```

Since that doc however, I think we also agreed on having `@Page` components have a `Page` suffix, like `TestPage`. cc @tlancina

**Comment by tlancina** [comment]
@alexbainbridge This has been updated in alpha.49:
https://github.com/driftyco/ionic2/blob/master/tooling/generators/page/index.js#L9
https://github.com/driftyco/ionic2/blob/master/tooling/generators/page/page.tmpl.js#L10

However the starters hadn't been updated to the latest framework version, which I've just done now, thanks!
