### ISSUE TITLE
Create ion-date / ion-datetime similar to ion-select

### ISSUE THREAD

**Issue by richardshergold** [driftyco/ionic2#931]
@adamdbradley I love the ion-select you have added to alpha49.  I think it looks great. 

On my form I have a bunch of select fields and also a date input field.  The date input now feels a little out of place as the date fields look different to the ion-selects and also when you click on the date field the selections appear at the bottom of the screen just like an old style select rather than in an alert box like your new ion-select i.e

~~~
  <ion-select >
    <ion-label>Gender</ion-label>
    <ion-option value="f" checked="true">Female</ion-option>
    <ion-option value="m">Male</ion-option>
  </ion-select>

  <ion-label>Date</ion-label>
  <input type="date">
~~~

Would it be possible to have the date input look and feel the same as the ion-select ?

**Comment by richardshergold** [comment]
I got round this by programatically building my date list and using a select for the date input.  Probably not the cleverest way but it will suit me for now.

**Comment by adamdbradley** [comment]
Absolutely, it's on our todo :)

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5010
