### ISSUE TITLE
"position: fixed" is NOT relative to browser window

### ISSUE THREAD

**Issue by flavordaaave** [driftyco/ionic2#932]
Steps to reproduce:

1) Use the current ionic-conference-app as a starting point
2) Open the `app/pages/schedule/schedule.html`file
3) Add the following inside `<ion-content>:
```
...
<ion-content class="schedule">
  <div style="position:fixed; top:0; left:0; width:100%; height:40px; background:red; z-index:999999;"></div>
...
```

=> The red div is now positioned fixed within the `<ion-content>` and NOT relative to the browser window as expected.

**Comment by adamdbradley** [comment]
Sorry this is a bug with fixed positioning and using translateZ. We do however require translateZ to be on ion-content so the animations are performant, so we can't remove it from ion-content.
