### ISSUE TITLE
Use d.ts for Hammer.js

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#933]
Currently the hammer file is hacked with TS. Rather leave the hammer.js as is, and let the d.ts file add the types.

**Comment by adamdbradley** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/hammerjs/hammerjs.d.ts

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5009
