### ISSUE TITLE
Discuss: Conventions

### ISSUE THREAD

**Issue by tlancina** [driftyco/ionic2#941]
Not that this is super pressing, but for consistency, what are everyone's thoughts on things like prefixing private/protected with `_`, explicitly writing public, order of declarations etc.

Right now here's what I've done:

```
export class Select {
  private selectedText: string = '';
  private labelId: string;

  @Input() cancelText: string = 'Cancel';
  @Input() okText: string = 'OK';
  @Input() value: string = '';
  @Input() alertOptions: any = {};
  @Input() checked: any = false;
  @Input() disabled: boolean = false;
  @Input() id: string = '';
  @Input() multiple: string = '';

  @ContentChild(Label) label: Label;
  @ContentChildren(Option) options: QueryList<Option>;

  constructor(
    private form: Form,
    private elementRef: ElementRef,
    private renderer: Renderer,
    @Optional() private navCtrl: NavController,
    @Optional() ngControl: NgControl
  ) 

  someMethod() //private
```

Do components really need to worry about visibility? They are injectable, but do we expect people to ever need to do so? Prefixing everything with `_` seems unnecessary if we don't.  Also I've been leaving `public` off since it's the default, except for the shorthand in constructors.

**Comment by adamdbradley** [comment]
WIthin `<ion-` components don't worry about it, and leave the code as is. Within classes that would be injected or used we can have `_` prefix for private and protected, and do not write `public`.
