### ISSUE TITLE
Ion-slides, passing through swiper options - direction doesn't work

### ISSUE THREAD

**Issue by DustinJSilk** [driftyco/ionic2#946]
I've been trying to implement vertical slides to the ion-slides component and found this issue which showed that you can in fact pass through options to the swiper plugin (Which is a great thing and should be reference in the documentation):

https://github.com/driftyco/ionic2/issues/871

Using this technique:

```javascript
    this.slideOptions = {
      slidesPerView: 3
    };
```

```
<ion-slides [options]="slideOptions">
```

I've tried passing through:

```
this.slideOptions = {
      direction: "vertical"
    };
```

But it doesn't work. If I go and change the direction directly on the plugin then it works perfectly. 

**EDIT**
I realise the repo has actually moved :/

**Comment by DustinJSilk** [comment]
I don't know why - but I stop ionic and reserved it and it started working. Seems like the app.bundle was being cached. Though when i changed other options they went through. Not sure what happened

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5004
