### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by manekinekko** [driftyco/ionic2#947]
Hi guys, I am having some issues with 2.0.0-alpha.49. Every time I build my app, I get a `Uncaught RangeError: Maximum call stack size exceeded`. I am using a default project configuration with the default Angular 2 (2.0.0.beta.0). Nothing fancy. 
My app is running on standard Genymotion emulator, Nexus 5 - 5.1.0 - API 22.

Here is a details vue about the error:
![image](https://cloud.githubusercontent.com/assets/1699357/12375610/92dd7ac4-bcca-11e5-9d1a-dacf805f1e1a.png)

Thanks.

**Comment by manekinekko** [comment]
Hi, I just noticed that this issue happens only when using `--livereload`. 
I was building using livereload: `ionic run android --livereload --device=192.168.59.102:5555`.

**Comment by Luchillo** [comment]
+1 i'm happening the same, also the changes aren't being re-loaded in the devise.

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic#5003
