### ISSUE TITLE
Remove console.debug statements when building for distribution

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic2#96]
Throughout the source code we'll be using `console.debug('hi tim!')` which is useful for local v2 development. But remove these when building the ionic-framework distribution files for npm and the cdn.

**Comment by adamdbradley** [comment]
Also auto-remove `console.time` and `console.timeEnd`

**Comment by tlancina** [comment]
Tracking in https://github.com/driftyco/ionic2/issues/724.
